### ISSUE TITLE
Category methods should be prefixed

### ISSUE THREAD

**Issue by ZevEisenberg** [pinterest/PINRemoteImage#1]
In order to avoid possible name collisions, category methods on Objective-C objects should be prefixed: [https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html](source) via [http://nshipster.com/namespacing/](NSHipster). Instead of:

```objc
[imageView setUpdateWithProgress:YES];
```

it should be:

```objc
[imageView pin_setUpdateWithProgress:YES];
```

**Comment by garrettmoon** [comment]
Sounds good! Want to submit a pull request :)

**Comment by ZevEisenberg** [comment]
I would be delighted. It's going to be a breaking change, but since you just released, you might be able to skirt the "breaking changes should bump the major version" guideline. Worth considering, though.

**Comment by garrettmoon** [comment]
It would, maybe mark the old versions as deprecated and we'll remove them in the next release?

**Comment by ZevEisenberg** [comment]
Good idea.

**Comment by garrettmoon** [comment]
Awesome! Looking forward to the PR

**Comment by jaredsinclair** [comment]
👍🏻
