### ISSUE TITLE
Raise 'processor' block also in case getting image cache

### ISSUE THREAD

**Issue by DmitryBulaienko** [pinterest/PINRemoteImage#100]
It would be nice if **processor** block would also get called on pulling image from cache using methods
**pin_setImageFromURL:processorKey:processor:**, etc. 

Image preprocessing block is great thing and would be cool if that can be applied for cached images.
Thanks in advance!

**Comment by garrettmoon** [comment]
@DmitryBulaienko the block doesn't get called because the image pulled from the cache will have already been processed. If it has to go through the processing block again you don't get the benefit of caching :)
