### ISSUE TITLE
How to add automatic detection of animated gifs?

### ISSUE THREAD

**Issue by andrewhavens** [pinterest/PINRemoteImage#118]
Sorry if this is the wrong place to post this. I notice that your library requires the developer to specify a `FLAnimatedImageView ` if the image is an animated gif. Since I only have a URL, I don't know the format of the image (jpeg, gif, other). Is it possible to add auto-detection so that the downloaded image automatically uses the correct image view?

**Comment by garrettmoon** [comment]
@andrewhavens I think this is actually supported already. FLAnimatedImageView is a subclass of UIImageView. The category which sets the results on it checks if it's an animated image and if it's not sets it as a regular image.

So! You don't need to detect if it's a GIF or not, just use an FLAnimatedImageView if it's possible you'll get a GIF back.

Hope this helps!

**Comment by cannyboy** [comment]
i was able to use FLAnimatedImageView for both animated and still images: https://github.com/Flipboard/FLAnimatedImage/issues/123#issuecomment-178555531
