### ISSUE TITLE
Manager is object is not used in cancelWithUUID

### ISSUE THREAD

**Issue by mRs-** [pinterest/PINRemoteImage#121]
When I wrote the support for nullability I discovered that the manager is not used or needed in `- (BOOL)cancelWithUUID:(NSUUID *)UUID manager:(PINRemoteImageManager *)manager`

Maybe this is a bug or it's not needed.

**Comment by garrettmoon** [comment]
I went through, it looks like the manager is used in PINRemoteImageProcessorTask? It needs it to call the manager to cancel the download task.

**Comment by mRs-** [comment]
I refer to PINRemoteImageTask.m line 76 https://github.com/pinterest/PINRemoteImage/blob/master/Pod/Classes/PINRemoteImageTask.m#L76

**Comment by garrettmoon** [comment]
Yeah, it's not used there, but its used by its subclass :) PINRemoteImageProcessorTask.

**Comment by mRs-** [comment]
Okay :)
