### ISSUE TITLE
Make tag for 1.2.3

### ISSUE THREAD

**Issue by rounak** [pinterest/PINRemoteImage#122]
The podspec latest version says 1.2.3 but there's no 1.2.3 tag so the latest version on cocoapods is still 1.2.2

**Comment by garrettmoon** [comment]
Dang, sorry about that! I'll try and get to it this weekend.

**Comment by garrettmoon** [comment]
Added!

**Comment by rounak** [comment]
Thanks @garrettmoon. Appreciate you being so swift!

**Comment by rounak** [comment]
Sorry to bother you again, but do you know if Cocoapods should automatically pick up this change, or there's something more to be done? Because it still shows the older version. https://cocoapods.org/pods/PINRemoteImage
