### ISSUE TITLE
How does the cache expire? Is it possible to check if a cached image has changed?

### ISSUE THREAD

**Issue by dev-mush** [pinterest/PINRemoteImage#123]
I find PINRemoteImage a great and stable library, and I really thank you guys for such a great work!

There's just one thing I can't seem to figure out, and I promise I'll dig down into the source code to figure it out, but meanwhile, I'd like to ask if this functionality is actually supported.
( _I did some googling about it and crunched your past issues, and even if I found some similar questions, I didn't manage to find something that was answering my question_).

Sometimes, even if URL of the image remains the same, the Image on the backend changes. I'm wondering if PINRemoteImage checks http cache headers to understand if the image has expired. As far  as I've understood it seems that, as long as the url key is cached by PINCache, the cached image is retrieved from the disk and the manager doesn't try any download, is this correct?

If so, is there a way to workaround it? Like by setting cache expiration or forcing a header check and redownloading?

**Comment by garrettmoon** [comment]
@dev-mush you're right, this is not currently supported by PINRemoteImage. There's currently a pull request attempting to implement TTL on PINCache, that could help. Looking at headers would certainly be a good option as well, the downloading of images is done in PINDataTaskOperation if you want to take a look on what it would take to add support.

**Comment by garrettmoon** [comment]
@dev-mush TTL is now supported on PINCache, does this resolve your issue?

**Comment by garrettmoon** [comment]
Closing this out since I haven't heard back.
