### ISSUE TITLE
FLAnimatedImageView not animating after setting UIImageView with same URL

### ISSUE THREAD

**Issue by cannyboy** [pinterest/PINRemoteImage#127]
I'm setting a `UIImageView` with `pin_setImageFromURL`. 

Later, I set a `FLAnimatedImageView` with the  same method and URL. 

```
imageView.pin_setImageFromURL(NSURL(string: "http://i.giphy.com/RqFXe34guTAAg.gif")!)
let dispatchTime: dispatch_time_t = dispatch_time(DISPATCH_TIME_NOW, Int64(0.1 * Double(NSEC_PER_SEC)))
dispatch_after(dispatchTime, dispatch_get_main_queue(), {
    self.flAnimatedImageView.pin_setImageFromURL(NSURL(string: "http://i.giphy.com/RqFXe34guTAAg.gif")!)
})
```

When I do this, the `FLAnimatedImageView` does not animate.

Perhaps the image is initially cached as a still image, so it will never appear animated?

**Comment by garrettmoon** [comment]
That's a good theory!

**Comment by garrettmoon** [comment]
@cannyboy is this still an issue with the latest beta? This logic has been rewritten.

**Comment by garrettmoon** [comment]
Closing this for now, but please reply back if you have more info!
