### ISSUE TITLE
Bitcode Support

### ISSUE THREAD

**Issue by justin** [pinterest/PINRemoteImage#132]
We have migrated our image processing and caching to PINRemoteImage + PINCache, so thank you very much for saving me from having to rewrite an 6 year old parsing library! 

One thing i've noticed since the migration is that I don't believe the releases you put out through Carthage support Bitcode. 

Is a fix for that a pull request you'd accept?

**Comment by garrettmoon** [comment]
@justin probably! Do you know if there's a way to support it optionally? Could I create two versions for each release? We don't currently use Carthage so I'm at the communities mercy as to how to best support Carthage users.

**Comment by justin** [comment]
I just sent a PR. If you are using Cocoapods, I don't believe this will have an effect. 

I'm not sure how you're building the release zips you are uploading to Github either, but if you're building those from the xcodeproj file, they'll have bitcode enabled.

**Comment by justin** [comment]
Actually it looks like PINCache would need to have Bitcode enabled too since it's bundled.

**Comment by garrettmoon** [comment]
@justin Yup, I cd into the PINRemoteImage directory and then carthage build --no-skip-current.

I'll also accept pull requests for PINCache :)

**Comment by justin** [comment]
OK. I took a peek at this and I think it's good to go.  PINCache already has bitcode enabled, so if you build new binaries for it things should be fine. 

You can test all this by doing this in the `PINRemoteImage` project on my `bitcode` branch.

```
cd ~/PINRemoteImage 
carthage update --no-skip-current --no-use-binaries
cd ./PINRemoteImage
carthage build --no-skip-current
```

Everything should be build and good to go now.

**Comment by garrettmoon** [comment]
Merged! Thanks for doing this! Let me know if anything else needs to be changed.
