### ISSUE TITLE
OS X Support Broke Carthage 

### ISSUE THREAD

**Issue by justin** [pinterest/PINRemoteImage#140]
When I try to use a freshly built copy of the framework from `master`, it gets mad about the `PINImage` defines saying it can't find them.

It builds fine in the `PINRemoteImage` project, but importing it into a third-party iOS app causes tons of errors around the define breaking down.

I wonder if frameworks can't deduce the `#define` values? I can't really find any documentation to validate or invalidate this.

**Comment by justin** [comment]
If you copy-pasta the defines into each class that use them rather than just the import of `PINRemoteImageMacros`, it's fine. Obviously not an ideal solution. Trying to see what else is feasible.

**Comment by garrettmoon** [comment]
@justin thanks for looking into it! Let me know if I can help in any way.

**Comment by justin** [comment]
Maybe @maicki can chime in with some thoughts since he spearheaded the OS X support.

**Comment by maicki** [comment]
@justin @garrettmoon Can we close that issue due to: #160 ?

**Comment by justin** [comment]
Let me dig into it today. I'll report back.

**Comment by justin** [comment]
This is still an issue, with the same errors coming back.

<img width="479" alt="screen shot 2016-03-15 at 12 32 53 pm" src="https://cloud.githubusercontent.com/assets/1384/13789512/136881d6-eaaa-11e5-8569-1c35e0c24d18.png">

**Comment by justin** [comment]
This branch fixes it I believe. 

https://github.com/justin/PINRemoteImage/tree/fix/osx-conditionals

I updated the conditionals to be more explicit and added an import of `TargetConditionals.h` in the macros file. Stuff compiles now.

Computers!

**Comment by garrettmoon** [comment]
Computers! Mind putting up a pull request?

**Comment by justin** [comment]
Yessir! https://github.com/pinterest/PINRemoteImage/pull/164

**Comment by garrettmoon** [comment]
Landed!

**Comment by justin** [comment]
Whoooo. Would be nice if it became a 2.1.1 so we could get back on mainline. We're still tagged at 1.2.3

**Comment by garrettmoon** [comment]
Absolutely, I'll try and get this released over the weekend (ping this thread if I forget).

**Comment by garrettmoon** [comment]
Published 2.1.1
