### ISSUE TITLE
Image downloading restarts when reusing UICollectionView cells

### ISSUE THREAD

**Issue by chika-kasymov** [pinterest/PINRemoteImage#142]
Hello! 

I have an issue when scrolling `UICollectionView`. When 'A' cells start to download their images, and UICollectionView scrolls to 'B' cells, 'A' ones stop downloading process. When I return to 'A' cells they start to download again, but 'B' cells stop. 

I see methods `setMaxNumberOfConcurrentOperations:` and `setMaxNumberOfConcurrentDownloads:`, but don't know if they will help me.

Can you help to solve scrolling issue?

**Comment by maicki** [comment]
@chika-kasymov Hey Kassymov would you be able to provide some sample project?

**Comment by chika-kasymov** [comment]
My `- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath` method:

```
- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *cellIdentifier = @"FlatDashboardCollectionViewCell";
    FlatDashboardCollectionViewCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:cellIdentifier forIndexPath:indexPath];
    
    MallObjects *mallObject;
mallObject = [self currentDashboardData][indexPath.item];
Offers *firstOffer = [mallObject.filteredOffers firstObject];
    
    [cell.imageView setPin_updateWithProgress:true];
    if (firstOffer) {
        PFFile *background = firstOffer.background;
        [cell.imageView pin_setImageFromURL:[NSURL URLWithString:background.url] placeholderImage:[UIImage new]];
    } else {
        PFFile *background = mallObject.background;
        [cell.imageView pin_setImageFromURL:[NSURL URLWithString:background.url] placeholderImage:[UIImage new]];
    }
    
    NSString *mallObjectTitle = mallObject.name;
    cell.mallObjectTitleLabel.text = mallObjectTitle;
    
    return cell;
}
```

Without `[UIImage new]` images are shuffled.

**Comment by danielgalasko** [comment]
@chika-kasymov you are correct. When you use the image category pin_setImageFromURL you will see that there is the line `[self cancelImageDownloadOnView:view]`.

My suggestion is, if you want to download the actual image and not cancel rather use

```
[[PINRemoteImageManager sharedImageManager] downloadImageWithURL:url
                                                                                            completion:completion]
```

make sure in your completion that you check if the cell is still visible by making the call to `collectionView.cellForItemAtIndexPath`

**Comment by chika-kasymov** [comment]
@danielgalasko ok, I will try.
