### ISSUE TITLE
Include image url in callback block

### ISSUE THREAD

**Issue by rounak** [pinterest/PINRemoteImage#145]
Callback blocks in PIN Remote Image include a result object. That object doesn't include the imageURL.

So when using the library from a cell (or any scenario where there's scope for reuse bugs) I can't tell if this callback block has been called for the latest image url or from a previous call.

I know I could cancel the download operations in prepareForReuse, but I want to let the download continue, and not restart it from zero for the previous URL.

So is it possible to add an imageURL property on `PINRemoteImageManagerResult`?

**Comment by garrettmoon** [comment]
Check out the UIImageView categories. They deal with the exact issue you're describing by looking at the NSUUID returned by downloadImage.
