### ISSUE TITLE
README has broken link to UIImageView+PINRemoteImage

### ISSUE THREAD

**Issue by cbttpaul** [pinterest/PINRemoteImage#146]
In the README, there is a link to [UIImageView+PINRemoteImage](https://github.com/pinterest/PINRemoteImage/blob/master/Pod/Classes/Image%20Categories/UIImageView+PINRemoteImage.h).  I believe this has to do with the category being changed to `PINImageView+PINRemoteImage.h`

**Comment by garrettmoon** [comment]
Addressed with #147, thanks!
