### ISSUE TITLE
PINURLSessionManager crash trying to get delegateQueue

### ISSUE THREAD

**Issue by dmauro** [pinterest/PINRemoteImage#149]
Crash occurred here: https://github.com/pinterest/PINRemoteImage/blob/master/Pod/Classes/PINURLSessionManager.m#L89

In PINRemoteImage 1.2.2. Happened to catch it in the debugger. It got a nil delegateQueue out of the delegateQueues dictionary.

**Comment by garrettmoon** [comment]
@dmauro Thanks for reporting! This was address in https://github.com/pinterest/PINRemoteImage/commit/21e69bcf809f27039d0bd28e157bedbff73fa119#diff-3a0c5e99470a5f988d8cd462abb141a2

You should update :)

**Comment by dmauro** [comment]
Sorry, will do. Thanks!
