### ISSUE TITLE
Wrong define-based iOS/OSX determination

### ISSUE THREAD

**Issue by k06a** [pinterest/PINRemoteImage#151]
Here is code to demonstrate this bug:
```
static int const aaa = __IPHONE_OS_VERSION_MIN_REQUIRED;
// Error: use of undeclared identifier '__IPHONE_OS_VERSION_MIN_REQUIRED'

#import <UIKit/UIKit.h>

static int const bbb = __IPHONE_OS_VERSION_MIN_REQUIRED;
// No error here
```

So this include will not work properly without importing UIKit:
```
#import <PINRemoteImage/PINRemoteImage.h>
```

And this code looks fun:
```
#ifdef __IPHONE_OS_VERSION_MIN_REQUIRED
#import <UIKit/UIKit.h>
#else
#import <Cocoa/Cocoa.h>
#endif
```

I'll try to describe this code literally: _if imported UIKit do import UIKit else import Cocoa_.

Maybe better to use this defines:
```
#if TARGET_OS_IPHONE || TARGET_OS_TV
#import <UIKit/UIKit.h>
#elif TARGET_OS_MAC
#import <Cocoa/Cocoa.h>
#endif
```

Found this solution here: https://github.com/SnapKit/Masonry/blob/master/Masonry/MASUtilities.h

**Comment by garrettmoon** [comment]
Please put up a pull request!

**Comment by k06a** [comment]
@garrettmoon no problem :) https://github.com/pinterest/PINRemoteImage/pull/155

**Comment by garrettmoon** [comment]
@k06a Thanks again for putting up the PR, I think #164 fixed this.
