### ISSUE TITLE
Ability to expose internal method and property for PINRemoteImageManager

### ISSUE THREAD

**Issue by rf10ster** [pinterest/PINRemoteImage#153]
Hello, I'm using PINRemoteImage in one of my project, and I'm really keen on with it - You've created great framework. 
But for my internal needs I need to be able to override method of `PINRemoteImageManager` - `downloadDataWithURL` which compose my own download process as part of result task and want to put it into tasks queue `urlSessionTaskQueue`.
So I've made fork of your repository and create helper category - You can find it here
https://github.com/BalaclavaLab/PINRemoteImage/commit/272e5bca6ed0b33b580829f722ea428cd009d90d

I think it could be wonderful if You can include it in some of future releases, hope it could be useful not only for me

Thanks in advance

**Comment by garrettmoon** [comment]
Hi @rf10ster,

Thanks for the feedback! I think if you want to implement your own downloading process, it might be better to make a delegate protocol and a default delegate which implements the current behavior? That way you don't have to expose internal methods which could change behavior at any time. And you can set up an explicit contract around what those delegate methods should do.

I'd happily accept a pull request that did that!
