### ISSUE TITLE
Unable to add PINRemoteImage to iOS 7.0 project

### ISSUE THREAD

**Issue by piechart** [pinterest/PINRemoteImage#154]
I've installed PINRemoteImage via Carthage
I followed all instructions:

<img width="476" alt="2016-03-03 11 16 15" src="https://cloud.githubusercontent.com/assets/17230738/13488300/697eafc8-e131-11e5-85de-1586680aa51c.png">
<img width="673" alt="2016-03-03 11 15 15" src="https://cloud.githubusercontent.com/assets/17230738/13488301/697f1e86-e131-11e5-841d-67b1daf76dce.png">
<img width="616" alt="2016-03-03 11 15 08" src="https://cloud.githubusercontent.com/assets/17230738/13488302/697fe05a-e131-11e5-9f23-eeba22c30355.png">

But after building got this error:
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/PINRemoteImage.framework/PINRemoteImage) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

What have I done wrong? I need to use this awesome library on iOS 7.0 project

**Comment by piechart** [comment]
By the way. I've also tried to install it via CocoaPods with such file:
xcodeproj "pinTestCocoa.xcodeproj"
pod "PINRemoteImage"
pod "PINCache"
Got result
<img width="568" alt="2016-03-03 11 27 21" src="https://cloud.githubusercontent.com/assets/17230738/13488549/f71ce3ee-e132-11e5-9b19-21f7b69a8e21.png">
But it can't find SDWebImage module on import

**Comment by piechart** [comment]
I've also tried installing with CocoaPods with such file:
xcodeproj "pinTestCocoa.xcodeproj"
pod "PINRemoteImage"
pod "PINCache"
Got result:
<img width="568" alt="2016-03-03 11 27 21" src="https://cloud.githubusercontent.com/assets/17230738/13488688/dde4b4aa-e133-11e5-91ed-50dae243c8e5.png">
But neither I can use it without any import nor with
import PINRemoteImage etc does not work, without it - properties *.pin_ImageWithURL can't be found. 
What the problem?

**Comment by garrettmoon** [comment]
@piechart I don't believe Carthage supports below iOS 8, so you'll have to use cocoa pods if you want to support iOS 7.

When you use cocoa pods, are you using the generated .xcworkspace instead of the .xcodeproj?

**Comment by piechart** [comment]
That was my mistake missing "use_frameworks!" in Podfile
Sorry
