### ISSUE TITLE
Availability framework not imported

### ISSUE THREAD

**Issue by bdorfman** [pinterest/PINRemoteImage#159]
You don't have `#import <Availability.h>` anywhere in your headers, so it is possible other apps importing your framework will not have `__IPHONE_OS_VERSION_MIN_REQUIRED` defined and thus will default to NSImage even on iOS deployment targets (causing build errors).

**Comment by maicki** [comment]
@garrettmoon That should be fixed with #164

**Comment by garrettmoon** [comment]
@bdorfman can you confirmed this is fixed 2.1.1?
