### ISSUE TITLE
Invalid detection of iOS vs OS X in source code

### ISSUE THREAD

**Issue by swisspol** [pinterest/PINRemoteImage#163]
This cannot work:
```
#ifdef __IPHONE_OS_VERSION_MIN_REQUIRED
#import <UIKit/UIKit.h>
#else
#import <Cocoa/Cocoa.h>
#endif
```

`__IPHONE_OS_VERSION_MIN_REQUIRED` is not defined by the compiler but by one of the system headers, so `#ifdef __IPHONE_OS_VERSION_MIN_REQUIRED` will always evaluate to false since no such system header is included beforehand, _unless_ you happen to be lucky and use a precompiled header.

Second of all, the best macro to use is `TARGET_OS_IPHONE` as in:
```
#if TARGET_OS_IPHONE
// On iOS device or simulator
#else
// On OS X
#endif
```

The reliably way to do this is therefore something like:
```
#import <TargetConditionals.h>
#if TARGET_OS_IPHONE
// On iOS device or simulator
#else
// On OS X
#endif
```

**Comment by garrettmoon** [comment]
Should be fixed by #164
