### ISSUE TITLE
Image from our CDN breaking due to 403 Error

### ISSUE THREAD

**Issue by riotcku** [pinterest/PINRemoteImage#166]
Hello Pinterest! I have a problem that I can't quite pin down and was hoping for some help here. I do hope this is the correct place to ask!

I'm fixing a bug on the site we manage (http://metallica.com). When we pin items, everything works fine until I try to view the picture itself on Pinterest, the image request gets a 403 forbidden access error and appears broken on the site. Here's some pictures below for your reference.

http://cl.ly/0h1k243r270z

http://cl.ly/1w2y1s0M0D3J

I'm unsure if this is an issue that can be fixed by changing stuff on our CDN to let a specific port through, missing an https tag somewhere... 

Metallica.com customers would love to pin stuff! Thanks for your time :)

**Comment by riotcku** [comment]
Oh. After a bit more testing it turns out Adblock for some reason blocks the image from showing up. I'm sorry! Working great now...

**Comment by garrettmoon** [comment]
Glad you got it working!
