### ISSUE TITLE
Consider calling completion and progress callbacks on the main thread

### ISSUE THREAD

**Issue by DavidNix** [pinterest/PINRemoteImage#169]
Line of interest:
https://github.com/pinterest/PINRemoteImage/blob/7ba1bee59c733f4e11267700e0d4a51f5a177404/Pod/Classes/PINRemoteImageManager.m#L176

It's very common for progress and completion callbacks to update UI elements.  Hence, as a library author, calling them on the main thread is typical.  I would even argue best practice.  I admit, I haven't had the time to fully understand the need for calling them on an arbitrary queue (instead of the main queue).  The documentation hints at optimization reasons.

I spent a good while banging my head because these callbacks were not updating the UI:

```
// From PINRemoteImageManager.h
- (nullable NSUUID *)downloadImageWithURL:(nonnull NSURL *)url
                                  options:(PINRemoteImageManagerDownloadOptions)options
                         progressDownload:(nullable PINRemoteImageManagerProgressDownload)progressDownload
                               completion:(nullable PINRemoteImageManagerImageCompletion)completion;
```

Then I read the documentation more closely (my fault) and noticed:

> Download or retrieve from cache the image found at the url. All completions are called on an arbitrary callback queue unless called on the main thread and the result is in the memory cache (this is an optimization to allow synchronous results for the UI when an object is cached in memory).

I was using the progress block to update a progress bar in the UI as well as the completion block to set an image on a UIImageView.

Perhaps a config option to force callbacks on the main queue?

Thanks for this great library.

**Comment by garrettmoon** [comment]
@DavidNix Thanks for the feedback!

Yeah, this is definitely something that snags a lot of devs. It's part of the reason all the default categories exist.

That said, there are very specific performance reasons to not use the main thread. Maybe a clearer warning in the README would help?

**Comment by DavidNix** [comment]
The reason I dipped into the Manager is to get at that progress callback.
Perhaps expose the progress block in a category method?

But a big warning in the README would definitely help.

Thanks!

On Mon, Mar 21, 2016 at 4:04 PM Garrett Moon <notifications@github.com>
wrote:

> @DavidNix <https://github.com/DavidNix> Thanks for the feedback!
>
> Yeah, this is definitely something that snags a lot of devs. It's part of
> the reason all the default categories exist.
>
> That said, there are very specific performance reasons to not use the main
> thread. Maybe a clearer warning in the README would help?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pinterest/PINRemoteImage/issues/169#issuecomment-199507829>
>
-- 
Thanks,

David

**Comment by danielgalasko** [comment]
One suggestion could be to follow suit with AFNetworking and allow for setting the callback and progress queues. That way they can default to main thread but gives more advanced applications the power to specify background queues...

**Comment by garrettmoon** [comment]
@danielgalasko It should be pretty straightforward to allow init'ing with another callback queue!

**Comment by danielgalasko** [comment]
Cool 🍌🍌🍌, don't mind making a PR as I can see the value of this. Only consideration is to go with `NSOperationQueue` or a GCD queue. Personally I prefer using a GCD queue in this instance because the API provided by NSOperationQueue might imply cancellation and dependencies which don't make sense in the context of completion and progress blocks. There is some good [conversation](http://stackoverflow.com/questions/10373331/nsoperation-vs-grand-central-dispatch) around this but either way its a trivial change.

AFNetworking went with GCD: [link](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFURLSessionManager.h#L160)

Thoughts @garrettmoon ?

**Comment by alexcohn** [comment]
I tend to agree with @DavidNix: there is zero cost if a completion is **nil**, and I cannot imagine a progress callback that is not on the UI thread

**Comment by danielgalasko** [comment]
Cool, submitted #222

**Comment by garrettmoon** [comment]
Going to close this out since I don't think we're probably going to implement this. There is a separate issue for calling back on the main thread for the UI* categories which makes more sense to me https://github.com/pinterest/PINRemoteImage/issues/207
