### ISSUE TITLE
Is there a way to disable caching temporarily? (For debugging purposes.)

### ISSUE THREAD

**Issue by christianselig** [pinterest/PINRemoteImage#176]
I'm curious if there's a way to disable the caching functionality of PINRemoteImage/PINCache temporarily. This doesn't make much sense in the real world, as that's a massive point of the library itself, but while debugging it can be really helpful to see a full image download performed each time.

Perhaps there's a way to do this and I haven't been able to find it, but I figured I'd ask.

(I know you can delete specific items from the cache after downloading them to achieve a similar effect, but tracking down each download point in the app's code and inserting deletion code is a lot more onerous than `PINRemoteImageManager.sharedImageManager.disableCaching()`.)

**Comment by garrettmoon** [comment]
I don't think there currently is one, but I'd be open to a pull request that added the option!

**Comment by dtorres** [comment]
This should be possible by setting the byteLimit in the PINDiskCache to 1 (after all,  no image will be shorter than a byte) and the costLimit of PINMemoryCache to 1 as well.. both properties are assignable son you can set them through your manager instance

**Comment by garrettmoon** [comment]
Good call @dtorres, I would think that should work! Closing this, but please let me know if it should be re-opened @christianselig.
