### ISSUE TITLE
-[UIImageView setPin_updateWithProgress:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by vijaytholpadi** [pinterest/PINRemoteImage#181]
I just switched from SDWebImage to PinRemoteImage for Progressive JPEG rendering. It works well most of the time but I saw a series of consecutive crashes happen when I was trying to load images progressively in my CollectionView. 

I then ran the application again on my phone and I am not able to reproduce this crash again. Will keep an eye out for it.

I am enclosing the crash report from Crashlytics from reference.
[Crashlytics link] (http://crashes.to/s/5b3609ef613)

**Comment by garrettmoon** [comment]
Thanks for the report @vijaytholpadi I've never heard about this one before.

What version of PINRemoteImage are you using?

**Comment by vijaytholpadi** [comment]
Hi Garett,

The versions is PINRemoteImage (2.1.2)

**Comment by garrettmoon** [comment]
Hmm, I don't see how this would occur unless client code was calling the wrong method. I'm going to close this issue, but please reply here if you can give more steps to help investigate.

**Comment by matheusleite** [comment]
I have the same issue. 
I do not calling the wrong method

**Comment by garrettmoon** [comment]
@matheusleite are you able to reproduce the issue? Can you provide a sample project? The crash is an unrecognized selector, so it should be reproducible reliably…

**Comment by matheusleite** [comment]
I installed PINRemoteImage through cocoapods and import the libraries:

`#import <PINRemoteImage/PINImageView+PINRemoteImage.h>`

then, when I try to run the app, in the cellForRow tableView delegate method, crash when I try to use pin_setImageURL on my UIImageView embed on my TableViewCell, look:

![screen shot 2016-05-18 at 14 01 49](https://cloud.githubusercontent.com/assets/7133438/15367898/681577fa-1d01-11e6-89a7-d25d16c89ec9.png)

**Comment by garrettmoon** [comment]
@matheusleite would you be willing to send me your project? garrett@pinterest.com. If so, I should be able to figure this out. It's quite strange! I'm guessing it's a problem with the configuration of the project.
