### ISSUE TITLE
Images May Be Removed from Disk Cache for Not Being in Memory Cache

### ISSUE THREAD

**Issue by Adlai-Holler** [pinterest/PINRemoteImage#186]
If we attempt to fetch an image from the memory cache but it isn't there, we will remove it from the disk cache:

<img width="1059" alt="screen shot 2016-04-12 at 7 49 16 pm" src="https://cloud.githubusercontent.com/assets/2466893/14481422/a8cacbb4-00e7-11e6-99c6-d1c8a4fdaba3.png">

<img width="724" alt="screen shot 2016-04-12 at 7 49 53 pm" src="https://cloud.githubusercontent.com/assets/2466893/14481432/bf448664-00e7-11e6-8efb-64e256e9d205.png">

This kills the disk cache 💀 . This issue is with version 2.1.2 which is currently shipping with AsyncDisplayKit. Not sure if it affects latest, sorry =/

**Comment by garrettmoon** [comment]
Dang, this is a bad one :( I'll get it fixed up immediately.

**Comment by garrettmoon** [comment]
Luckily it doesn't happen in many code paths.

**Comment by garrettmoon** [comment]
Fixed in 2.1.3 which just got published. Fix is here:

https://github.com/pinterest/PINRemoteImage/commit/f15ca03ece954b4712b2c669c849245617e73e08

Will fix in master next.

**Comment by Adlai-Holler** [comment]
Thanks for the fast fix!
