### ISSUE TITLE
Readme and code are out of sync

### ISSUE THREAD

**Issue by ZevEisenberg** [pinterest/PINRemoteImage#19]
I updated the readme in #3, but because there has not been a new release, the readme currently recommends using methods that are not available in the 1.0 release, which anyone using CocoaPods will be using.

**Comment by garrettmoon** [comment]
Looking to do a . release soon :)

**Comment by garrettmoon** [comment]
Dot release complete, looking to push new pod spec soon, however: https://twitter.com/garrettmoon/status/627650447537389568

**Comment by garrettmoon** [comment]
Finally got the new pod spec up!

**Comment by garrettmoon** [comment]
Please reopen if I missed something.

**Comment by ZevEisenberg** [comment]
I would remove the merge details from the past release names, but otherwise looking good!
