### ISSUE TITLE
PINRemoteImageManager timeout

### ISSUE THREAD

**Issue by taher-mosbah** [pinterest/PINRemoteImage#192]
Hello,
I'm using PINRemoteImage (2.1.4) through CocoaPods for downloading Images and PINCache for caching.
PINRemoteImageManager gives me a timeout for every request, the same image request works fine using NSUrlSession or even Safari. 
Testing the example project and a new project works fine.
Same behaviour on device using wifi and cellular.

`  [[PINRemoteImageManager sharedImageManager]
      downloadImageWithURL:
          [NSURL URLWithString:@"https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg"]
                   options:0
                completion:^(PINRemoteImageManagerResult *_Nonnull result){}];`
Here is the log : 
Task does not exist creating with key: https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg, URL: https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg, UUID: <__NSConcreteUUID 0x7f7fe07caa40> C7052204-2185-415B-A5CE-853753B5390F, task: 0x7f7fe28556a0

I think that the PINRemoteImageManagerDefaultTimeout default value of 60s is not used too.
I know this is not an easy issue to track, do you have any ideas ?

Thank you

**Comment by taher-mosbah** [comment]
My question is: is there any special configuration for using PinCache and PinRemoteImage in the same project ?

**Comment by garrettmoon** [comment]
@taher-mosbah PINRemoteImage *requires* PINCache. If you're using cocoa pods to include PINRemoteImage, PINCache will be included implicitly. So to answer your question, there shouldn't be any special requirements. Can you provide sample code? The log above doesn't really tell me anything; that log occurs when PINRemoteImage debugging is on and you request an image.

**Comment by taher-mosbah** [comment]
Thank you for you answer, I tracked down the issue to an external dependency that I'm using (HockeySDK 4.0.0-beta.1) using 3.8 solves the conflict.
