### ISSUE TITLE
Cache underlying image when using the processor

### ISSUE THREAD

**Issue by rounak** [pinterest/PINRemoteImage#194]
I don't think PINRemoteImage caches the actual unprocessed image when using it with a processor block. Is this an oversight or an intentional decision?

**Comment by garrettmoon** [comment]
That would definitely be a bug!

**Comment by garrettmoon** [comment]
@rounak would you be willing to write a unit test to show this behavior? That'd help us to getting closer to a fix and preventing another regression.

**Comment by garrettmoon** [comment]
@rounak I'm going to close this for now. If you can provide a test case or even better a unit test, I'll happily re-open.
