### ISSUE TITLE
CFBundleShortVersionString error when trying to upload to iTunes Connect

### ISSUE THREAD

**Issue by krezzoid** [pinterest/PINRemoteImage#198]
Hi ,

you have wrong format for CFBundleShortVersionString and in total impossible to upload app to iTunesconnect without changing this value to correct, for example "3.0.0.2" instead of "3.0.0-beta.2"

**Comment by garrettmoon** [comment]
@krezzoid iTunes connect won't allow 4 digit values either :(

This is also a beta release and needs to be indicated as such.

Can you give the exact logs that you hit when uploading to the app store?

**Comment by garrettmoon** [comment]
Found more context: https://github.com/CocoaPods/CocoaPods/issues/4421

**Comment by krezzoid** [comment]
Yep, seems like this is  the same issue … anyway, error message from iTunesConnect is the same.
Do you still need to have something additional from my side?

___________________________________________________________
Amudo SAS
Ilya Seliverstov
ilya@amudo.com <mailto:ilya@amudo.com>
amudo.com <http://amudo.com/>

**Comment by garrettmoon** [comment]
@krezzoid do any of the work arounds in the thread work? Have you tried using cocoa pods 1.0.0rc? It seems like this is a cocoa pods issue :( There's no good way for us to fix this without releasing 3.0 early.

**Comment by krezzoid** [comment]
I just changed CFBundleShortVersionString in .plist file of Xcode archive before submitting app ;)

> Have you tried using cocoa pods 1.0.0rc?

not yet, i prefer to wait for release version. Anyway, its not a problem for me to update .plist file before submitting  app, because this not happens often.

**Comment by gudjao** [comment]
Using cocoapods 1.0 fixes the problem for me.
