### ISSUE TITLE
FLAnimatedImage header not found if adding 3rd party pod with FLAnimatedImage dependency

### ISSUE THREAD

**Issue by maicki** [pinterest/PINRemoteImage#200]
Adding e.g. NYTPhotoViewer as new pod besides AsyncDisplayKit / PINRemotImage. NYTPhotoViewer adds FLAnimatedImage as dependency and installs it within the workspace. PINRemoteImage will set USE_FLANIMATED_IMAGE to 1, but for some reason cannot import the FLAnimatedImage headers. To fix this issue we have to explicitly add PINRemoteImage with FLAnimatedImage support to the Podfile:

```
# Before the fix
use_frameworks!

pod 'AsyncDisplayKit'
pod 'NYTPhotoViewer'


# After the fix
use_frameworks!

pod 'AsyncDisplayKit'
pod 'PINRemoteImage/FLAnimatedImage', '>= 3.0.0-beta.2'
pod 'NYTPhotoViewer'
```

[ASDKGalleryDummy.zip](https://github.com/pinterest/PINRemoteImage/files/261489/ASDKGalleryDummy.zip)

**Comment by garrettmoon** [comment]
Yeah, ASDK and PINRemoteImage don't include FLAnimatedImage support by default. You need to specify the subspace.

**Comment by 9you** [comment]
It should be document else where :D
