### ISSUE TITLE
What does srand([[NSDate date] timeIntervalSince1970]) do?

### ISSUE THREAD

**Issue by PhilCai1993** [pinterest/PINRemoteImage#201]
Why adding ```srand([[NSDate date] timeIntervalSince1970]);``` ?
I'm curious...

**Comment by garrettmoon** [comment]
Looks like you're referring to the example apps? I assume it's to ensure that the random numbers aren't deterministic on each run.

**Comment by PhilCai1993** [comment]
Thanks😃
I read your new post on Pinterest blog yesterday. I'm really curious about the techs referred in that. I wish new posts will come soon
在2016年05月20日 01:41，Garrett Moon 写道:

Looks like you're referring to the example apps? I assume it's to ensure that the random numbers aren't deterministic on each run.

**Comment by garrettmoon** [comment]
@PhilCai1993 We're working on more blog posts!

**Comment by PhilCai1993** [comment]
I've read your recent post [Behind the launch of Pinterest’s Design Standards](https://engineering.pinterest.com/blog/behind-launch-pinterest%E2%80%99s-design-standards).
And I'm facing similar issues. In our company, designs are made using Sketch. And when it comes to texts, it's hard to layout the UILabel or UITextview correctly. 

CJK languages are heavily used in our [app](https://itunes.apple.com/cn/app/e-le-me/id507161324?mt=8).  I'm considering adpoting AsyncDisplayKit for the benefit of its layoutspecs. And I'm really curious about how does Pinterest do the layout. 

According to this blog, does it mean that I have to maintain a dictionary mapping between fontsize and displaysize?
In this image, does ```Size``` mean ```[UIFont systemFontOfSize:Size]```? And what's the meaning of```Tracking``` ? 
  ![image](https://cloud.githubusercontent.com/assets/6828315/19431996/3dc69660-948d-11e6-9f6b-b9568f43051f.png)

I'm sorry for asking question here and for my English, but could you please give some suggestions?

Thanks a lot!

**Comment by appleguy** [comment]
Hey there!  Would be happy to help if you have AsyncDisplayKit questions.  Is this question about PINRemoteImage, or ASDK?  If you're wondering about the text layout, feel free to file a ticket on the AsyncDisplayKit GitHub, and come join us on Slack too!  (	http://asyncdisplaykit.org/slack.html)

**Comment by PhilCai1993** [comment]
@appleguy I'm sorry for leaving a comment here. It's not about PINRemoteImage, but it seems to be related to ASDK. But [here](https://engineering.pinterest.com/blog/behind-launch-pinterest%E2%80%99s-design-standards) is the blog from Pinterest about text bounding layout([maybe he is the auther of that article](https://github.com/rcancro)). 
Would that slack channel you metioned here help?
