### ISSUE TITLE
[Feature Proposal] URLRequest configuration

### ISSUE THREAD

**Issue by dtorres** [pinterest/PINRemoteImage#211]
I would like to manipulate some properties of the request before is sent to the session, specifically `allowsCellularAccess` but other developers may find this useful to authenticate their requests through custom HTTP headers.

Currently it is only possible to modify these values at the session level, applying them to every request.

Implementation ideas:
- Add a parameter to PINRemoteImageManager methods to supply a block to configure the request
- Convert the options argument to a dictionary where users can supply values to be applied afterwards

And of course retrofit the view categories to support this.

**Comment by garrettmoon** [comment]
I like the idea of a block which can be set which will be called to configure the request. Something like the  `authenticationChallenge` block that currently exists.

**Comment by dtorres** [comment]
Having a block property in the manager takes away all the context a user might need. And considering that the only input the user has is the URL, which is useless since at this point it could've come from anywhere in the app (or the network for that matter)

**Comment by garrettmoon** [comment]
We could also pass in the UUID? The concern I have with passing it in as part of the operation is that multiple areas of the app could be requesting the same image but with different request parameters. PINRemoteImage will only generate one request for multiple requests of a URL. How would it reconcile which set of request parameters to use?

**Comment by dtorres** [comment]
makes sense, and let the user reconcile according to their needs

**Comment by garrettmoon** [comment]
Hey, this got completed! Going to close this out.
