### ISSUE TITLE
Partial downloaded image not getting stored in cache

### ISSUE THREAD

**Issue by kalrashubham49** [pinterest/PINRemoteImage#212]
I am trying to fetch p-jpegs using this library . 

But if an image is partially downloaded it is not stored in cache and neither library is resuming download from the point it left.

**Comment by garrettmoon** [comment]
@kalrashubham49 that's correct, we don't store progressive renders in the cache (because they are bitmaps, they would be quite large).

Why would you want the progressive renders stored in the cache?

**Comment by carl-donath-tinroof** [comment]
If an image is partially downloaded, need a way to
- use (right now) the best image an incomplete progressive render can provide (lest have to re-fetch & wait for what has already been fetched)
- resume the partial download
and/or [why I'm actually posting this]
- mitigate multiple requests for the same image, none of which have completed yet (and some/all of which are under way, dividing effective bandwidth significantly).

**Comment by garrettmoon** [comment]
@carl-donath-tinroof 
If you try and download an image multiple times, only one download will ensue and if each download operation has a progressive block, each block will be called when there are progressive results. You are correct though, if you kick off one download option which begins rendering progressive results, starting another download operation will not immediately vend the last progressive result (it will get updated the next time a progressive render happens though).

**Comment by carl-donath-tinroof** [comment]
So to clarify a nuance I'm tangled in: if you request a single image (same URL) several times practically at the same time (no chance for any request to finish downloading any meaningful amount of data), perhaps interleaved with several other similarly multiple requests, it will - or won't - start only one download stream (recognizing there are several requests) per same URL? or might we get multiple download streams per same URL, sorting out the duplicated results when caching?

(Stopping multiple identical simultaneous requests from happening is my problem; I'm just wondering  how PINRemoteImage is reacting to it if/when it does happen. My case may or may not include progressive images.)

**Comment by garrettmoon** [comment]
Correct, only one download for many download requests of the same URL. If an existing download is running (task) any additional calls with the same URL will get attached to that task. If any of the download requests requested progressive callbacks, those will occur when enough data has been downloaded to generate one, regardless of when a request was attached to a task.

**Comment by garrettmoon** [comment]
@carl-donath-tinroof there is now support for canceling and resuming image download requests. Can I close this issue out?

**Comment by garrettmoon** [comment]
Going to close this out since I haven't gotten a reply.
