### ISSUE TITLE
PINRemoteImageManager cancel task

### ISSUE THREAD

**Issue by alexcohn** [pinterest/PINRemoteImage#216]
My questions are about a specific line of code:

[`[strongSelf.canceledTasks removeAllObjects];`](https://github.com/pinterest/PINRemoteImage/blob/master/Pod/Classes/PINRemoteImageManager.m#L542)

1. Why do we remove all objects from the `canceledTasks` list on _any_ completion of `downloadImageWithURL` if its UUID is different?
2. Why don't we remove objects  from the `canceledTasks` list on completion of download operation if its UUID had been used in `cancelTaskWithUUID`?

**Comment by garrettmoon** [comment]
Hopefully the pull request answered your question, lemme know if not!

**Comment by alexcohn** [comment]
Thanks, this fix looks good
