### ISSUE TITLE
PINRemoteImageManager.setPriority

### ISSUE THREAD

**Issue by alexcohn** [pinterest/PINRemoteImage#217]
On the face of it, 
[`break`](https://github.com/pinterest/PINRemoteImage/blob/master/Pod/Classes/PINRemoteImageManager.m#L945) only stops the inner loop [`for NSUUID *blockUUID in [task.callbackBlocks allKeys]`](https://github.com/pinterest/PINRemoteImage/blob/master/Pod/Classes/PINRemoteImageManager.m#L942), but not the outer loop [`for (NSString *key in [strongSelf.tasks allKeys])`](https://github.com/pinterest/PINRemoteImage/blob/master/Pod/Classes/PINRemoteImageManager.m#L940).

Am I missing something?

**Comment by garrettmoon** [comment]
Sorry this wasn't looked at before. I think this code has been changed. Lemme know if I should reopen.
