### ISSUE TITLE
Can we make FLAnimatedImage optional?

### ISSUE THREAD

**Issue by chiahsien** [pinterest/PINRemoteImage#22]
For now, `FLAnimatedImage` is set as a dependency in podspec, is it possible to make it optional? Maybe make it a subspec?

**Comment by garrettmoon** [comment]
I'd be happy to accept a pull request that made it optional!

**Comment by derekargueta** [comment]
@garrettmoon is this issue closable with pull request #65 merged?

**Comment by garrettmoon** [comment]
Yes! I think so, thanks!
