### ISSUE TITLE
Application Crashing with Message (Exercised class for selector implementation needs to be pushed)

### ISSUE THREAD

**Issue by kalrashubham49** [pinterest/PINRemoteImage#224]
Application is crashing and giving error shown Below:

Fatal Exception: NSInternalInconsistencyException
Exercised class for selector implementation needs to be pushed

<img width="955" alt="screen shot 2016-07-27 at 3 59 08 pm" src="https://cloud.githubusercontent.com/assets/13597940/17172511/170e4866-5413-11e6-92f6-41a2239d5f09.png">

Lot of users are affected and i am not able to track this crash

**Comment by garrettmoon** [comment]
@kalrashubham49 can you give some more information? Any way to reproduce?

**Comment by kalrashubham49** [comment]
When I run this application in development environment, it never occurred ,
but I have received 65 such crashes for 55 users as per crashlytics record
for my Live Appstore build

**Comment by garrettmoon** [comment]
@kalrashubham49 hmm, I'm not sure how to investigate this further. What kind of images are being shown? Could the image format be unsupported?

**Comment by garrettmoon** [comment]
Going to close this for now, will re-open if more info is posted.
