### ISSUE TITLE
<PINRemoteImage/PINRemoteImageCaching.h> file not found

### ISSUE THREAD

**Issue by CavalcanteLeo** [pinterest/PINRemoteImage#228]
Installed with pod

![captura de tela 2016-08-09 as 12 16 14](https://cloud.githubusercontent.com/assets/1735944/17521851/4f5be094-5e2b-11e6-9a6f-addec0b1e8df.png)

![captura de tela 2016-08-09 as 12 16 59](https://cloud.githubusercontent.com/assets/1735944/17521850/4f322aba-5e2b-11e6-9d71-e9d6fb777979.png)

**Comment by CavalcanteLeo** [comment]
but with manually installing, worked!

**Comment by CavalcanteLeo** [comment]
no one?

**Comment by garrettmoon** [comment]
@CavalcanteLeo can you possibly give a bit more info?

**Comment by garrettmoon** [comment]
Let me know if you have any more information to add, I'll re-open the issue.

**Comment by CavalcanteLeo** [comment]
Sure, I installed PINRemoteImage with cocoapods.

But the pod folder doesn't have all files that the project have.

Should have all those files: https://github.com/pinterest/PINRemoteImage/tree/master/Pod/Classes

instead, have only the print above

**Comment by garrettmoon** [comment]
@CavalcanteLeo what version of cocoa pods (`pod --version`) do you have? Can you post your Podfile?

**Comment by CavalcanteLeo** [comment]
pod 'PINRemoteImage', '2.1.4'

**Comment by CavalcanteLeo** [comment]
also tried with 3 beta

**Comment by CavalcanteLeo** [comment]
i friend ( @leonardo-ferreira07 ) of mine had the same issue

**Comment by CavalcanteLeo** [comment]
cocoa pods version 1.0.1

**Comment by garrettmoon** [comment]
@CavalcanteLeo I just created a new test project with Xcode and a podfile (I also tried 2.1.4) on cocoa pods 1.0.1:
```
target 'test-pinremoteimage' do
  pod 'PINRemoteImage', '3.0.0-beta.3'
end
```
Both compiled fine for me. Are you sure you have the .xcworkspace open and not the .xcproject?

**Comment by CavalcanteLeo** [comment]
hehe, of course, it's an old project, with a lot of pods, i just switched from SDWebImage to PINRemoteImage

**Comment by leonardo-ferreira07** [comment]
@garrettmoon yeah, this compiled fine for us too. But, @CavalcanteLeo have a doubt if this class is used or not by the library, and in the main if this class is used to do a progressive loading.

**Comment by CavalcanteLeo** [comment]
I can't import the class PINRemoteImageCaching

**Comment by garrettmoon** [comment]
Ohhh, I see, you're trying to import PINRemoteImageCaching.h but you're not able to because it's not exposed via cocoa pods, that's the issue?

**Comment by CavalcanteLeo** [comment]
Yep, i tried to reproduce this example:
https://github.com/pinterest/PINRemoteImage/blob/master/Example/PINRemoteImage/ProgressiveViewController.m

**Comment by garrettmoon** [comment]
@CavalcanteLeo @leonardo-ferreira07

Ahh, ok, that file isn't in a release yet, it's only in master. Take a look at the Example in the actual repro that you're using:

https://github.com/pinterest/PINRemoteImage/blob/3.0.0-beta.3/Example/PINRemoteImage/ProgressiveViewController.m

**Comment by CavalcanteLeo** [comment]
damn, just got confused between the branches.. lol 😰  😰

Thank you @garrettmoon, and can't wait for the immutable data model open source

**Comment by garrettmoon** [comment]
No worries :) (immutable data model is coming… higher priority things have been prevailing 😀)
