### ISSUE TITLE
Image not found but error is (null)?

### ISSUE THREAD

**Issue by donnywals** [pinterest/PINRemoteImage#23]
When I attempt to load an image at an invalid URL and the completion block is called I would expect the error to contain information about why the image didn't load. Instead both the error and image contain `(null)`. Shouldn't a 404 result in a valid error?

console output when printing result:
```
<PINRemoteImageManagerResult: 0x7ff2996d5e40>image: (null)
animatedImage: (null)
requestDuration: 0.366901
error: (null)
resultType: 3
UUID: <__NSConcreteUUID 0x7ff29ba06db0> 8264EB5B-4ADD-466E-9033-2A11BFDA2524
```

**Comment by garrettmoon** [comment]
Yup, it probably should!

**Comment by alexvimpekable** [comment]
This also the case if url is nil
