### ISSUE TITLE
High Memory use

### ISSUE THREAD

**Issue by CavalcanteLeo** [pinterest/PINRemoteImage#230]
Device: an older device (iPod touch 5th generation - ME643BZ/A) 

In a UICollectionView, with a lot of imagens the app crashes by exaggerated amount of memory used (usually when I scroll too fast)

In a quick debug, I found this:

![captura de tela 2016-08-10 as 14 04 46](https://cloud.githubusercontent.com/assets/1735944/17563163/6efb8baa-5f04-11e6-9972-981931f41780.png)

![captura de tela 2016-08-10 as 14 07 06](https://cloud.githubusercontent.com/assets/1735944/17563164/6effd5b6-5f04-11e6-918c-0e4589e37c4a.png)

**Comment by leonardo-ferreira07** [comment]
👍

**Comment by garrettmoon** [comment]
Let me know if you have any more information you'd like to add, I'll re-open the issue.
