### ISSUE TITLE
Try to use WebP file 

### ISSUE THREAD

**Issue by leonardo-ferreira07** [pinterest/PINRemoteImage#231]
Hello, @garrettmoon! 

Here is my problem: i'm trying to test the WebP image format in my project, i'm using the same method ```[self.imageView pin_setImageFromURL:[NSURL URLWithString:@"http://www.gstatic.com/webp/gallery/3.webp"];``` of your example in the repository, and doesn't work. I saw in another closed issue, that you said to add **pod 'libwebp'** to my ```.Podfile```, i added it and then the WebP image still doesn't appearing. I'm using the library by CocoaPods in the last stable version (2.1.4). My CocoaPods version is 1.0.1.

Can you help me? There's anything more that i have to do?

**Comment by garrettmoon** [comment]
@leonardo-ferreira07 did you figure it out? I saw your pull request (and merged)

**Comment by leonardo-ferreira07** [comment]
@garrettmoon i searched for issues closeds here, and i discover how to do the WebP images works perfectly. Just add a ```PINRemoteImage/WebP``` subspec to my ```Podfile```. Then, this is so related with issue #158. I suggested a little modification in README.md, and create a pull request #232.

**Comment by leonardo-ferreira07** [comment]
Yeah, problem solved! Thank you for this great repository, and thanks to for accepting my pull request. :)

**Comment by garrettmoon** [comment]
Glad to hear it! Thank you for improving the README :)
