### ISSUE TITLE
Impossible use setPin_updateWithProgress in Swift

### ISSUE THREAD

**Issue by ezefranca** [pinterest/PINRemoteImage#235]
Because the name of the class, its impossible to import in Swift.

**Comment by garrettmoon** [comment]
@ezefranca I believe it's the correct way to provide a property override for a category method which has a prefix in Objective-C. Any ideas for a solution?

**Comment by ezefranca** [comment]
It's one solution. But another approach are use the Macro **NS_SWIFT_NAME**
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by garrettmoon** [comment]
Neat! Would you be interested in putting up a PR to fix? I'd happily review :)

**Comment by lukeivers** [comment]
i seem to be able to set it via `imageView.pin_updateWithProgress = true`

**Comment by garrettmoon** [comment]
@ezefranca does lukeivers' solution work for you? If not would you be willing to provide a test app that shows the issue?

**Comment by maicki** [comment]
@ezefranca You have to use `imageView.pin_updateWithProgress = true` as @lukeivers said. The reason is that it's declared as a property in `PINRemoteImageCategory` and not as a method:

```objc
@property (nonatomic, assign) BOOL pin_updateWithProgress;
```

**Comment by garrettmoon** [comment]
@ezefranca Going to close this now, please let me know if there's something that still needs to be done.
