### ISSUE TITLE
Move from `pin_` prefix to a `pin.` proxy (for Swift 3) update ?

### ISSUE THREAD

**Issue by AndrewSB** [pinterest/PINRemoteImage#237]
I thought this would be nice for use in swift 3.
Incredibly similar to this change https://github.com/ReactiveX/RxSwift/issues/826

**Comment by garrettmoon** [comment]
Thanks for pointing to a fix! I'm out of the country for ~3 weeks. I'll look at putting up a PR when I'm back. If you want to put up a PR I can get one of my colleagues to look at it.

**Comment by AndrewSB** [comment]
Working on a PR for this today 👌

**Comment by garrettmoon** [comment]
Going to close this out for now, looking forward to the PR mentioned in #343 though!
