### ISSUE TITLE
How to avoid the  image being auto saved to the cache?

### ISSUE THREAD

**Issue by liaogang** [pinterest/PINRemoteImage#238]
I want to save the transformed image to the cache when download complete.
[PINRemoteImageManager downloadImageWithURL... ]

**Comment by garrettmoon** [comment]
If you use the Processing API:
downloadImageWithURL:(nonnull NSURL *)url
                                  options:(PINRemoteImageManagerDownloadOptions)options
                             processorKey:(nullable NSString *)processorKey
                                processor:(nullable PINRemoteImageManagerImageProcessor)processor
                               completion:(nullable PINRemoteImageManagerImageCompletion)completion;

the processed image will automatically be cached. If you want to avoid caching completely, you can set a limit of zero on the cache object (you'll need to cast it to a PINCache object)

Hope this helps!
