### ISSUE TITLE
Feature request: support Base64 inlined images

### ISSUE THREAD

**Issue by k06a** [pinterest/PINRemoteImage#239]
Some `NSURL`s can contain inlined images like this:

>data:image/jpeg;base64,%2F9j%2F4AAQSkZJRgABAQAAAQABAAD%2F2wCEAAkGBxITEhUTExIVFhUVFRUVFhUVFRUVFhYYFRUWGBcVFxUYHSggGBolGxUVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGxAQGi0eHR8tLS0rLSstKy0rLS0tLS0tLS0tLS0tLSstLS0tLS0tLS0tKy0tNy0tLSsuLS0rNzctK%2F%2FAABEIAMwAzAMBIgACEQEDEQH%2FxAAcAAABBQEBAQAAAAAAAAAAAAAGAgMEBQcBAAj%2FxABCEAABAwIDBAcECAUDBAMAAAABAAIDBBEFITEGEkFRBxMiYXGBkTKhscEUI0JSYnKy0SSi4fDxY5LCM1NzghY0Q%2F%2FEABoBAAIDAQEAAAAAAAAAAAAAAAIDAAEFBAb%2FxAAkEQACAgIDAQACAgMAAAAAAAAAAQIRAyEEEjFBMlETIgVxkf%2FaAAwDAQACEQMRAD8AsGhCvSEwmBtuBPvFrIsAQ%2Ftvb6M4c3NA8brXzfgzGwfmjNY490D+itMMo3SWFvNQ3MuQjfZaAEhYeR0jexq2Vc+zT+V%2FBNN2TkPCy0YMupBprC5XP%2FKzq%2Fij9MmxDZ6Vmdr+CqnUUgHsla9MwHIqK+jZmLDNGsv7FvEjI82kXHFLlNyFoNdgMbgckGV+GuY4gaBOjK%2FBM4UaB0aynq3tIyDgL88kexhZJsLjHVSNjdo4+%2FRa3EtbDK4Ixc8amx9oToCQwJwIwDoC9ZdSJZN0XKogieQNCqZZS45rs0pcbptMUaAbO2XQFwJShDq8F5dUCPJTCQkpSohZUdTfI68FMVJGbG6u43XAKXJBxYEoU2+ns2Nh4lzj5Cw+PuRbZCG2dG2TeewHfjLWuOdiM8gg5eRRhT+h8PE5zv8AQFUkJc8NbmTotM2ew0xN7WpVPsLhou55HgiiuqRGNCe4LFySt0jexRpWS2FOSONs0N%2F%2FAChjD2o3AKXT7TQSZB7Rfgcik9WO7olylR3nJOzztINiEh%2Fs+ShZCq5bNVFKAdVZVciqnlPxHPkB97SyoYB%2F3G29Qt4pdAsGxCYfSIzyew%2FzBb1S6A+C1uM%2F6mPzPyRLYEsJLUtPOU8quvmubcArCpk3WkofqKkN1KKIMmOroVRLinJNNxNyLZSL1dVMcYAGah1G1TB7PaPjklyyKPrGQhKXiCSR4ASGTg8UB121EzjlugeKgHHJCbu3vEG65Xy1ekdS4kq2ak03SggLD8SLrFkpvyuT6hFWHYoHWa%2FJ3PgUzHyIy0xeTBKBaBXFH7AVQ1XVM2zQmyehMQPAVQY3Of1YI3bFzxYZn+7K5TURbqLEgkG3vBXD%2Fkk%2F6s0%2F8U1UkRMFp9yPvdmf2TtZTbwyOfelw8lI3MllN7NaK0AmLYbOL2LT43zVDR4c8vAcMyfsrS54N7IjJIgwaNp3+KNZKWwHj2VdBhrmMc4km3AqnxDaG3ZbwRbi0obE7wWcOpgXgnLNSEb2yp60iTDtA0mzwQnZZw4bzTcKorYnhx3g1wvwGnhxt70qki3b2OVibLoikIlZJ2SohPWtB0aS8%2F8ArmFuVMMlmXRXhOUlQc95xY0eGq1CELWwx6wMbkS7TH2hLAXAmKqa2QRifCq2lrd1oA5oVllJ1KssdeS7wVSmJUB6z11Gq5y0ZaqQclTYk9xO43MnVc3Jz9FX06+Pg7u34VdbVF3tG%2FdwTVNIDkdOQU2owt9vYu3mDvW7ym2UZYRcf1Cy5ZLNNY6+EqGlY7ID5fFKdRlpzH9+KkwFlu00i%2FHgrER5DRw4X+fLxSuwygdkwsntxOIIzsP2VjhWNf8A51AA5PHzUpjQHXFwRqOP+O9JxDCWzDgHcDoD48lakDKIV0FU5oAcbtPsu19UXUkwLB4LINmsRkgk+i1AO672CdAe4ovjxCSPs71rHLvHNd+LNqmcGXDvQ6s1qa+elq3ta7J0gDgcxmRn42K0uyANt4x9Mhtq7cv%2FALsk%2FmxuAngTccgaMHFSYnKNE5SWrBkejj4NzPskl5PIDinH7vNV2I0jXdsucLZ9lxGir0IZ2ij+r1HqhWOK4Xccqpy4C3Z4eCcpr7ueq6I6Rzy2xxtE1zbkaZKurIrAga6DxOXzU+WosLJ3Z6l66dl82tO+7wGnvTsMXKVCc0lGNhxsnhYp6dkY1tvO%2FM7VEUai04yUuMLY80YLduxx7rC6rJHXUutfkAoStAspMdZax5qoIV3jhuPA%2FJU7W3KtypWXCNuhtxsMzYWuT3f3kn8LwXrCZLWBGXMjmU5DSCYsv7Ln28Qz+tkbQU7RawtZedz53ObZ6Lj4FCKB2jwRrDcA568QfFQMcwQNIcLhpPpfijqOMck1VUjZGuYeIy5pKbsbNIzMURbkRr6f4TfUvZ7On3T8kS1tJbsu1b8Ofgoz4AR380XYCijNS0+1drh6jy4hebO5mYsR6g%2FsU7iNNbVt+8a+SqQ4j2Tce8eLdUyKsXIsqxjKhlhk4aX1afmFPoq%2FeYN8DeGTvEIXdOWkXy5OHBW0NYxwu8drjbQ96NSr0CULDKyo8dwPrpIpQf8ApkXHMXvl4WV+AkSkBl76uLR4tF3egIW5ncVjdmLxlJ5FRWh1nEeidMvqkVsOVxwSKZ28vNvZ6ZOtECp+ksJeAxw+7nfxvxVZWYzLa0kVh+G6KJWkDIeSF68yXOVh3hFCvoapFbWYtHKRbIgWsdU6J27qgVNK1zrub56L0rmgAN0CdX6ES0x9kRkkaxv2iB+5+KP8BwZkAIaSS45uPwHch%2FYvDjnO4fhZf3lG8AyWtxsSjC36zG5eZyn1XhLiClRhRo1KjT2ciIda7NMBP1g7SYChRW43GNy%2FFDNVPa4GtviivFB2dLjkhSOHelb3m%2F7e5c%2FKb%2Fjo6eJFd7fwIaGHcdA3kL+uqKqcIIrK97Z7RM33BgtyBN1Mw7E6wO+tDQPIH0CwXDdm%2FGWqDKWRrASTkhjEdrGNdaNjnH3eXNXFQRJESdCEE4g2Rrd6KMk7xAsMzbgP3RLZGtBNO8TMDwN19r7p%2FSeaqHHcPaHZJt4dxVLLFWNu9jzvbx7Lg4C3m4ogw2SSRn18YBIsbZg96txoWkxmspwRbgdCgTF2bjjl4o+kHV3Y7Nh9k8QhraWky3rXyztxbzHemQYMkDsEYI3i5xb90a35X4BOse37Jc0cib+9Kw6LdPPiDwIUzqbXsQAc7FoOqJqy8bSWwk2o2mjpWEA70pB3WDhyLuQV7S4WRQUr8yWtu88SZQCXHzWBySE5kknmTcr6l2eLZKSLQtdEwEcxuhd2WbyppmfgxrFv6Brm3UB8BYd5voiDFcNMLrfZPsu59x71XPCymnF0zWVSVojDEG8VX1uJsN9Ezi0XJDU0bxpcooxTBcmOYlOHHLIKBT7peN++4M321DeJXJI3E2PoiLDsH3I3bw7T2kEcgRouvDC2jmzSpBnRRt3W7tt2w3baW4EKfGsc2X2zkpCYpAZImkgD7TLHgTw7kf4VtzQykDrerceEgLf5tPetSOWL9MWeKUWF0alxBQ6Z4cAWkEHiDcKdEibvwFEOvOajAKZXt4qEoimN1LRY3QtG36y44ZKwxnEMyxunEqviyaHd+fySOTFuGjp4rqZGr6iXfmEN98xjdtr2TnbvzUnZbD5wAZ3OLnXyJDjc2tcWytnx4p%2FAY71O+dLOHwRpTwtGYAWNkfV0jbxR7KyPUs3YiAm8Na0tDbf5SMdxGKOIku45qhwTHo3EdU%2Ff7QDhY5X8Qk06scFLcMYM7X8c0xVO3VKfX2yOSpcTqbqaDRX11QHdk+R5FUsklrsfw08%2FkpNQ06qDUPuLHXgUyDEZFsiU8AEhBtuOIt3fiXKuAB5a8Zty14Ksxare1osbZ5niiWaASCN51MbeacteiZP9GUuK+mNgZd6kjH3QAD3EXHxXzKc19B9ENWOoEbj7TWuZfwsRddaOVhxU07XtLXi4P93B5oPxfCnxZ6s4P5dzuXwR31a5JA0ixzB1BzHolzgpBwyOHhkVZHfgotPhZe4ANuToAiPaNlHC82mEbRfev2mg8Q0DPIKxwKWmdB1tNIJLkhz%2FALQPFu6dCkRwuzoeeNFG%2FBYoRYtD5jx4M8O%2FvUKsj3QRxIRGYNTxKb+ghofM%2FRjSbeGi7Yrqjkm+22fP+Ow7k7x3%2FwCVAJRJtxT7srHHWRhd%2FO5DgCEhaYPj9TTG8Ezmfh9pp8WuuFpGzfSq02bWM3T%2FAN2MEt8SzUeSyRoToaijNoXLFGR9K%2FTYp4xJFI17Txab+vJVWJ1gjZ3nIfusLw+vlgdvRSOYfwk5+I0Pmrtu2VQT9buv77bp92S6I519OWfHl82GL3KRSG4cPwkjyz%2FdD9BtBDLx3Hfddl6HirqllAcDwHzFvgUyTUo6AinB7LSliLAHjQu+IzV+2rsy6p2G0LOQe4e%2FJOYdNvFzTqDl4ahYXIjtm7xsmqZKqsHjlB3r3NiTdLgZTwCzS1thmeN+ZPNVGMQ1JeO2Gs4WBd7lGZhLHZOc+QnmS1voNUuMdHYofSxqtooN4MB6xxNg1oJPwUqqgtHvEWzyGq5hOEsjO8GNBtwAyXsXrR7PJDKvgLZU14AaEPyvU7Equ+SrWC6OOkKkVeMwFxjYNXmyK6wbjtwH2Gtb6BIwega+Zj3aRXkP%2FqNPVNVpcXk8TmfE5%2FNNbvRz%2FTKmBb50aUcZpopLHfa0EEE96wVgW89Ej70oadQLjwuV2I5zTo3bwuhDpAx98cToKd4bO9p7evVg8fzW0RA2ZzA7K+RIHfbL5IOGz7nv6yc9pzrkcdVCjCK3rGucyQuLmZZknvvnrfVWnR7tBNT1IawF0cmUrO7747wr7pnpWR1rN0Wc+AFwHEhxAPp8FF6N8JDmumOpdujwGqiRNGx04a4BzTdrswU1tBTOfG2Jmru04Xt2Wp%2FBYQImgcCfJJcHPqbkEANsPAcfVHZTRh%2FSpA5lUwOFvqW2Hg5yDQtM6c4LT07hxjePRwP%2FACWYgoCxdk4xyauV4OsVCEgLqaa9KDlCCkY7I15ewxuNyzS%2F3Togy6stmqrcqRnk67T8QmYpVIXlj2izToaw2bH3E+YN1ypqHMO+3n6i%2FwDVVr3HI8QVYstKxw+03PLwzHqqz4kpKX%2FSYMjqgkwvEWTttfPiOKuYaVgzsFkdXVSQSskYbWBJ5HLQomo9susa3skF%2FZaDxNr5LNyYnHzw0seW1T9CTG69sYOaBKmuc5xKfxB8jnHfv4KE9lkpDmhsklPwx9yTTxFzgAESxYdujIeavtRXWyNh53WSHnus+JKpetMl3N0JNvJX1TTnqy0cT8lQOo5Y+yyxGvgTqPcmY2n6c800zOWLd+iYfw0TvwuB9SsKYFvPQ+L0I7nH4laETlYf7qr5nDfHdr5KbJJZqH8en6ujqZjq2GQg8iWkD32UZRgm2uMmsrJp73bcsj7mMuG28Tc+aIOiuvH1kBNjffb4aEfBBD9LJ3Z2vMFTHIODwD+UkB3uVJ7JR9NYZDaMd+alNaouCy70Q7svmpj2omQx7p1j%2FwDru75B62PyWRrZenRn1VOf9R36f6LGyEJBbSkP1XQuO1VFi2pV0lq44qEHGlcpn2ka7k4G%2FgVxpXIjY3Vp7IzSoKyN7bhwOQOvxUilxSOJ7STe+TgCL2+8BxssxDuOngul5JBBzCZPL2VCY4urNPxyAG9vZsSORB0Kp6eCc7m4wgXbYuBAAbrZF2xOBSina6c3JALGOzLWngb%2FAARDLRh0jSRkP70WbPJRoQxjM+Hh4BIzIUM4P3+5EvU5JsQFcls614QsPw5jM7C%2FOykvhupkcKcEdlZTKY0iiT0djoiLqc10xBWnQDPmZi3Xoad%2FBW7z+pywtgW1dDcv8KB3u%2FUVrxM40CfPJDHSnL1eFyj75Yz1cEW08VzcrP8ApwqwKSNg+1MPcCVGUYe9RCpTimHhUiz6S2Bqd+mjd96Nh9yKC1BnRS6+Hx%2FlA9LoyKNlGU9OrLQQf+V36FirltXTq76qAf6jj%2FKsWKAhwJJ1SwkHVQsWF564CvEqEJFBSPmkZEwXc8ho8%2F7KlY1RdRIac7pdGSHvaSQ6+fHS17KfsNXNhmdL1Ze8McIwLCxOpJPkqWolc57nPN3FxJN+JPNCm+wbWhtxRr0ZbNfSJevkAMcfA%2FadqPIIKgjL3gDUmw8V9AbH4SKemYzdAcQC63EnUpWefWNIPDC3ZeBqU0JQYnGhcLOxIUy6dNkgyclxoQhDodkmnpzKySXKwRLVwhKCFNoNuqell6pwLzuhxLSLC5OXjYD1VpX4C2kYgRkte6Gc4Wj%2FAFHj5%2FMLIHLWOhapDYiP9R%2FvAWtEzzW6iYMasf6aJiWU4P2nyO%2F2tA%2F5LT6i7tVlfTi+0lKzlHK4+bmD5FRlGXFIcEtcVFm99Dzr0DPMejijlyAOhZ%2F8CB+J36ijxz0RRk%2FToezTjvefcFjjgte6cHZ047pP+KyIhCWJCbTp0TIUILuuJS4CoQmCYCIN6tocTfrM9633e4KO9eXHFQuww6McE6+pDy0FkXaIPOxtbzW4sisgfogoGtpTILbznG%2FMW4FH7gs7PK5HdhVRGwu2SmBObiSNGSUq665llxUQ9dcuuhVW02NxUcXWyusCd1oAuXOIJAA8AUSTbpFNpbZC22x9tJTuJaXOd2LNcGlpcCN48l8+SSXN8z36qXjWJGeZ8l3dtxPaNyLniogsMloYsfRHBkydmTHo%2FwCi6o3YnkcJfkFn70a9Gzvq5Pzj9ITkAbhfe3SONj6rIenST+Mhb92nB9Xv%2FZars5IXxN%2FDkfJY900Tb2IkfdijH6j81GUAK6F5eKohtPQy+1LbmXn+ZaJG3is66HmfUM7+s%2FUVolfLutsEbIZB01SXkg7myfFqypy0vpbB34SeLX%2FqCzR6AgiQ5JoJUxSAVZBd0lrs10JMftBQhIaFIwqkMszWczn4Jiym4E0dawuJAJOY1BtlYqn4WvTYeiwhrJ4QfYld5g6ZeSOi1Zr0eSmKrcw5ieMEG+jmXG742C05yzsi2d0HoQEq6S3VKlNgloYNPK4maipaxpe9wa1ouSdAgTF9vJnAmljaIxkZpNB4DQlXGDkVKSiF2P43DSxl8kjWE3DL3N3W5DPzXz1jWNz1D3GWVzt529ulziwHO260mwsDZLxnFpZXudK8vdfUm9u5vCyrYm3zP9hd2LEoe+nHkyd%2F9HmNsmpDmn3m102GDiniSa8oy6NT2ZR+NvwQW9GfRppL+cfBXEs2nZyQMhcfxfILC+kmp38QmP5R6ALXsLlO65vC4KxXbV166o%2F8n%2FFqjBKNeISlxCEbf0PC1Mw9zz%2FMUYVZLnWQZ0VOtSs%2FK79ZRtCEbKMr6ZY7Gn%2FLJ8WrKXLXOmsZ0%2F5ZPixZG5CQjyHNJXjqV5QgqyXG2wuksK67UBQh0nLxRHg2HGSIkatPZb942v8AEW8wh5jbk9yNNhhdst+DQR3EWOXmAgyaVhwVui+lqI42UtW0W3XNcbDVpGd+8HLyWsw1DZGNe03a5ocD3ELJKeIH6XTH%2Fpsc57RxBLN61+Vzoi7o1rXvpN1xuGHdb3DkuPItWdUPaC+E5qFjFeyFjpHmzWi5Py8SpMXFZt0iYnIJ2RAjcawy2tq+9gTztnbxSYrtoZJ9VZVbUbROmd9fJuRWL2QA2J+6ZDxJ5IRxvah00QgEbWxtILdS7IHU6cVXYlO58ji4k5qEBmfFaEIRijilNs4xlznknyUy%2FgvSGxTQBUq8WpBcuxyGyhD%2F2Q==

I think it would be perfect to support this URLs in `PINRemoteImage` not to handle this urls in a special way. What do you think? I think I am able to do this contribution myself.

https://en.wikipedia.org/wiki/Data_URI_scheme

**Comment by garrettmoon** [comment]
Thanks for putting up the PR!
