### ISSUE TITLE
Question: upgrade low quality image sometimes don't work

### ISSUE THREAD

**Issue by oferRounds** [pinterest/PINRemoteImage#250]
Hi,

I'm using the method which allows to download several URLs of varying quality and combine it with turning on the option to upgrade low quality images.

My question is regarding the last option - the `PINRemoteImageManager`'s `setShouldUpgradeLowQualityImages:completion`. The problem I'm seeing is that sometimes not all images are upgraded (even when the internet does seem to work well).

Maybe it's something that I have a misunderstanding about or I'm doing wrong. My questions/thoughts are:

1. Is setting the aforementioned method once, on app start, is enough? i.e., from this point it will try to do the upgrade on every download call which uses the varying quality URLs option? 

2. If that's true, then I'm not sure I understand the behaviour of the completion block, as if I call the `setShouldUpgradeLowQualityImages:completion` only once, then the block is called only one time. Alternatively, if I set it before each download call, then it's called many times.

3. Regarding the completion block - I think it worth adding more details, so it will be possible to know which upgraded image was just downloaded.

Anyhow, I'd love for your thoughts.

Thanks a lot!
Ofer

**Comment by oferRounds** [comment]
One more related question: is there a way to force the download of varying quality images? I.e., even if the bandwidth is not good, I would still like the client to try to download the highest quality image (even if it will take time).

Alternatively, if there is a way to adjust the values which are used to define what is considered to be a good and a bad network, that can also work out for me.

**Comment by oferRounds** [comment]
Ok, I'm sorry - I missed the relevant BPSThreshold methods.

But just to some up - I am trying to achieve the behaviour of which - given 3 URLs: low, medium, high - all 3 URLs are being tried to be download. My goal, if that makes sense, is to minimize the occurrences of situations of which the user sees a loading indicator, waiting for the image to arrive.

**Comment by garrettmoon** [comment]
@oferRounds for your use case, I'd recommend a progressive JPEG instead if possible. You can change the percentage download required to show a scan and possibly also encode your JPEG such that a lower quality scan exists.

The downloadImages: method sadly isn't designed for what you're trying to achieve.

**Comment by oferRounds** [comment]
@garrettmoon - thanks!
I actually use progressive JPEG, but I thought I can combine these two technics.
But sure - got you.

Regarding the `ProgressThresholds` array - a question just to make sure I understand: 
I see that the default value is set to [0.0, 0.35, 0.65]. So if I understand right, the first value, 0.0, means that the first progressive image will be generated after 0% of the image was downloaded and encoded (under the condition, that at least one scan was completed). Then, later on, when 35% was completed, and last - 65%.
Is that right?

**Comment by garrettmoon** [comment]
Yes, that's exactly correct. So I guess you can't make a change to get the first scan to show up earlier except re-encoding your JPEGs :/

**Comment by oferRounds** [comment]
Ok, got you :)
Then I'll look more into the re-encoding option.

Thanks for your response! :)
