### ISSUE TITLE
Using setAuthenticationChallenge?

### ISSUE THREAD

**Issue by AndrewSB** [pinterest/PINRemoteImage#251]
I'm currently using [Haneke](https://github.com/Haneke/HanekeSwift) for one of my projects, but was looking to switch over to this library 😄 

I had some trouble understanding the authentication procedure with PINRemoteImage, and I couldn't find any documentation or examples 😿

[Here's a gist](https://gist.github.com/AndrewSB/00d798a624466380715962c005008cef) of what I was doing with Haneke. My understanding is that I can assign my authentication headers inside of the authenticationChallenge block?

**Comment by garrettmoon** [comment]
Hey @AndrewSB, glad you're looking at PINRemoteImage!

So if you're doing basic authentication where you send a request and the server replies with a auth challenge, you'll want to look into `setAuthenticationChallenge:`

However, looking at your GIST it appears you just want to set an auth header? Setting custom headers is actually not possible currently (crazy no one has asked for this!), but it'd be pretty straightforward to implement. If you're interested, check out line [858](https://github.com/pinterest/PINRemoteImage/blob/master/Pod/Classes/PINRemoteImageManager.m#L858) in PINRemoteImageManager.m. You could add a block similar to the `setAuthenticationChallenge:` block which could further configure the request before it gets sent out (it'd probably need to be changed to an NSMutableURLRequest.

**Comment by AndrewSB** [comment]
You are correct, I do want to just set an auth header. Totally crazy that no one has asked yet!

I'm trying to push out a new release of an app by friday, so I'll be tied up until then, but I'll start a PR as soon as I'm free 😄

**Comment by garrettmoon** [comment]
@AndrewSB configuring a block to set custom headers are now supported in master! I'm going to close this out.

**Comment by AndrewSB** [comment]
Sounds good @garrettmoon 

Thank you PINRemoteImage contributors ❤️
