### ISSUE TITLE
PINRemoteImageManager's Disk Space Usage Too High

### ISSUE THREAD

**Issue by JoeFerrucci** [pinterest/PINRemoteImage#253]
My app's disk size grows seemingly unbounded. I would like to set a byte limit on PINRemoteImageManager. When investigating, I see this folder growing with each image downloaded: `com.pinterest.PINDiskCache.PINRemoteImageManagerCache` -- found at this path: `~/Library/Developer/CoreSimulator/Devices/<id>/data/Containers/Data/Application/<other-id>/Library/Caches/com.pinterest.PINDiskCache.PINRemoteImageManagerCache`

I see there exists `PINDiskCache.sharedCache().byteLimit` I have tried setting the byteLimit, but that has no effect on my problem.

Also tried setting this, with no luck solving my problem: `PINRemoteImageManager.sharedImageManager().defaultImageCache().diskCache.byteLimit`

The ways in which I'm using PINRemoteImage are:
1. `pin_setImageFromURL()` for each view I am setting. 
And then calling these next 2 just a single time on `viewDidLoad`
2. `PINRemoteImageManager.sharedImageManager().setMaxNumberOfConcurrentOperations()`
3. `PINRemoteImageManager.sharedImageManager().setMaxNumberOfConcurrentDownloads()`

Happens on Simulator and devices; iOS 8, 9 and 10; Xcode 7 and 8; Swift 2.3 and 3.0;

**Comment by JoeFerrucci** [comment]
I solved my problem by setting: `PINRemoteImageManager.sharedImageManager().cache.diskCache.byteLimit`

**Comment by garrettmoon** [comment]
Yeah, hmm, there's probably two learnings here:
1. We should probably set a default disk cache limit.
2. Default image cache is a bit confusing, it's intended only for override and should only ever be called once by the PINRemoteImageManager itself. That should be better documented.

**Comment by JoeFerrucci** [comment]
Is it safe for me to set it on app launch?

**Comment by garrettmoon** [comment]
@JoeFerrucci that's a good question, and why I'm now thinking we *shouldn't* set the cache limit by default.

When it's set it immediately trims to that size. So if we default to setting it to 50MB, and you later set it to 100MB, you'll lose 50MB of cache on every startup.

So I think I'll update the documentation and avoid setting a default limit at this time.

As far as setting it on app launch, it depends on how sensitive you are to performance. We don't set the beteLimit until x number of seconds after app launch (though that allows it to grow unrestrained until we do set the limit and then the disk cache has a lot of work to do to get back into shape).

Long term, and something that we're slowly working toward, we should have the disk cache trim on a lower priority than other operations.

**Comment by garrettmoon** [comment]
#254
