### ISSUE TITLE
Cached images duplicated

### ISSUE THREAD

**Issue by taher-mosbah** [pinterest/PINRemoteImage#256]
Hello,

I noticed that my app disk usage is too high, digging around with iExplorer I noticed that the same images are on two folders "com.pinterest.PINDiskCache.PINRemoteImageManagerCache" and "fsCachedData".
I limit my cache to 100 mb doing the following on startup :
`  NSUInteger maxImageCacheSize = 100 * 1024 * 1024;
  [[PINRemoteImageManager sharedImageManager].cache.diskCache trimToSize:maxImageCacheSize block:^(PINDiskCache * _Nonnull cache) {}];
`

but that does not seem to have any effect on fsCachedData (which is created by the NSURLSession I suppose).

Is this normal and fsCachedData is cleared by the OS later or is it a bug ?

**Comment by garrettmoon** [comment]
@taher-mosbah what version are you using? There was a bug for sadly quite a while where images would be cached twice, but that should be fixed in master (to disable NSURLSessionCaching).

**Comment by taher-mosbah** [comment]
@garrettmoon  I'm using version 2.1 from Cocoapods

**Comment by garrettmoon** [comment]
Yeah, this should be fixed in master or the latest 3.0 beta I believe.
