### ISSUE TITLE
Proper way to clean old images

### ISSUE THREAD

**Issue by taher-mosbah** [pinterest/PINRemoteImage#259]
Pre 3.0 I'm doing the following to limit the image cache to 100mb and clean the old ones : 
`  [[PINRemoteImageManager sharedImageManager].cache.diskCache trimToSize:maxImageCacheSize block:^(PINDiskCache * _Nonnull cache) {
  }];
`

This is not working anymore in 3.0, is this the proper way to do so ? 

`  PINDiskCache *tempDiskCache = [[PINDiskCache alloc] initWithName:@"PINRemoteImageManagerCache"];
  [tempDiskCache trimToSize:maxImageCacheSize block:^(PINDiskCache * _Nonnull cache) {}];
`

**Comment by garrettmoon** [comment]
@taher-mosbah You can either override defaultImageCache to return your own configured version of PINCache, or just cast: `[[(PINCache *)[[PINRemoteImageManager sharedImageManager] cache].diskCache trimToSize: maxImageCacheSize block:^(PINDiskCache * _Nonnull cache) { }];`

**Comment by garrettmoon** [comment]
It hasn't been documented yet well, but the cache is pluggable in PINRemoteImage so if you wanted to use a different caching system you could. By default however, PINRemoteImage will still use an instance of PINCache.

Let me know if this didn't work for you!
