### ISSUE TITLE
downloadImage without a UIImageView

### ISSUE THREAD

**Issue by AndrewSB** [pinterest/PINRemoteImage#264]
Hey! I'm having a little trouble downloading an image (to use for a `UINavigationBar.backgroundImage`, so I was thinking I'd just be able to use `PINRemoteImageManager.shared().downloadImage`, but I can't get the function signature to work out.

Here's what I tried:
![screen shot 2016-10-31 at 10 40 07 am](https://cloud.githubusercontent.com/assets/3814772/19864670/70630454-9f56-11e6-93d4-7adc2dc61957.png)

the error was: `Cannot convert value of type (PINRemoteImageManagerImageCompletion?) -> () to expected argument PINRemoteImageManagerImageCompletion?`

Am I using `downloadImage` incorrectly?

**Comment by garrettmoon** [comment]
I'm still learning Swift, but I *think* it should be `result: PINRemoteImageManagerResult?` instead of `result: PINRemoteImageManagerImageCompletion?`

**Comment by AndrewSB** [comment]
Hmm, thats what I was hoping for, but it isn't...
Here's the generated swift interface

<img width="1240" alt="screen shot 2016-11-02 at 5 12 09 pm" src="https://cloud.githubusercontent.com/assets/3814772/19952065/941620aa-a11f-11e6-9c7b-a512ac109b49.png">

and here's me trying to use it
<img width="1306" alt="screen shot 2016-11-02 at 5 11 12 pm" src="https://cloud.githubusercontent.com/assets/3814772/19952069/9a987a68-a11f-11e6-9c04-d096ad8c26ac.png">

I've even separated out the closure into a variable, so I know for a fact it matches the type `downloadImage` is expecting, but no luck.

**Comment by garrettmoon** [comment]
Do you have a sample project you could upload?

**Comment by zachwaugh** [comment]
In the first case, it's because the argument to completion handler has the wrong type, as @garrettmoon mentioned. In the second case, it's because PINRemoteImage exposes two similar methods here:

```swift
open func downloadImage(with url: URL, completion: PINRemoteImage.PINRemoteImageManagerImageCompletion? = nil) -> UUID?
open func downloadImage(with url: URL, options: PINRemoteImageManagerDownloadOptions = [], completion: PINRemoteImage.PINRemoteImageManagerImageCompletion? = nil) -> UUID?
```

Since the second method has a default value for the `options` parameter and parameters with default values can be omitted when calling, Swift doesn't know which method you're trying to call.

This will work:

```swift
PINRemoteImageManager.shared().downloadImage(with: url, options: []) { result in
  print("result: \(result)")
}
```

**Comment by maicki** [comment]
@AndrewSB Hey Andrew, currently PINRemoteImage's `downloadImage` method can be ambiguous. You can use this for now:

```Swift
        let url:URL = URL(string: "https://a2ua.com/alps/alps-020.jpg")!;
        PINRemoteImageManager.shared().downloadImage(with: url, options: []) {(result:PINRemoteImageManagerResult) -> Swift.Void in
            print("Received Image")
        }
```

**Comment by AndrewSB** [comment]
Ahh, that makes sense. An update would be cool in a while, but that workaround sounds perfect.

I can leave this open for you guys to track this, but please feel free to reopen this

I'm not touching that bit of code for ~2 weeks, since I found a temp fix. If after using the function signature that includes the `options`, it doesn't fix the problem I'll re-open this and create an example project for you guys 😄

**Comment by garrettmoon** [comment]
Cool, I'm going to close this out for now, please reply back to the thread if it's still an issue!
