### ISSUE TITLE
ARC Semantic issue in AsyncDisplayKit after upgrading to 3.0.0-beta-5

### ISSUE THREAD

**Issue by Sundin** [pinterest/PINRemoteImage#265]
Hello. 

I'm using AsyncDisplayKit together with PINRemoteImage, and after upgrading the latter to version 3.0.0-beta.5 I get the follow error in something called ASPINRemoteImageDownloader.m inside AsyncDisplayKit:

> ARC Semantic issue: No known instance method for selector 'memoryCache'

Downgrading PINRemoteImage to version 3.0.0-beta.3 solves the issue. 
(Don't know if this should have been posted in the AsyncDisplayKit repo instead, my apologies if it is in the wrong place!)

**Comment by garrettmoon** [comment]
@Sundin yup, the APIs have changed. If you use the latest AsyncDisplayKit master, you can use the latest PINRemoteImage. There will be a new release soon of AsyncDisplayKit, PINCache and PINRemoteImage to get them all into sync.
