### ISSUE TITLE
[Performance] Refactor use of -allKeys for a 1-2% global CPU optimization.

### ISSUE THREAD

**Issue by appleguy** [pinterest/PINRemoteImage#283]
In this trace, -allKeys and the retain / release costs account for >1% of global app CPU (in this case, a brief scroll in the Profile screen of Pinterest).

Considering that this trace includes substantial image decoding / drawing costs, other UIKit / UICollectionView costs, and also heavy cache reading and writing — this is a surprising % total for this call.

As a simple solution, it would probably be worth maintaining the keys as a separate, duplicated array alongside the NSDictionary to avoid this.  Alternatively, NSHashMap or a similar class might allow for accessing the keys as an array directly without a copy.

A fix for this would further extend PINRemoteImage's performance lead on many competing image downloaders :)

<img width="701" alt="screen shot 2016-12-07 at 11 38 38 pm" src="https://cloud.githubusercontent.com/assets/565251/21001734/f246457e-bcd6-11e6-8b07-8f55291c13e8.png">

**Comment by rahul-malik** [comment]
@appleguy - Rather than maintaining another data structure, wouldn't it be sufficient to replace `allKeys` with `keyEnumerator`? The large cost is likely due to the fact `allKeys` performance is going to degrade as the dictionary grows where the enumerator should be a fixed cost. Thoughts?

**Comment by appleguy** [comment]
Good idea!  Let's try that.  It may well be faster than a separate array, but mainly depends on the access patterns.
