### ISSUE TITLE
How do you manually insert an image into the cache?

### ISSUE THREAD

**Issue by zachwaugh** [pinterest/PINRemoteImage#284]
I have an image that I fetch from an API that's easier to grab directly than through PINRemoteImage since it requires authentication. Once I have that image, how I can insert it directly into the shared cache? I see there is the `PINRemoteImageCaching` protocol that has write methods, but it isn't clear exactly how to use it. What do I insert into the cache, the raw `NSData`? Do I insert into the memory or disk cache?

This looks like it would work, but wanted to double check:

```swift
let data = ... // NSData from HTTP request
let imageManager = PINRemoteImageManager.shared()
let cacheKey = imageManager.cacheKey(for: url, processorKey: nil)
imageManager.cache.setObjectInMemory(data, forKey: cacheKey, withCost: 0)
```

Thanks!

**Comment by garrettmoon** [comment]
@zachwaugh hmm, this isn't actually well supported now, but we absolutely could support it. Essentially we'd want to add a method to PINRemoteImage which is something like:

`insertImageDataIntoCache:(nonull NSData*)data withURL:(nonull NSURL *)url processingKey:(nullable NSString *)processingKey`

This would build and insert a PINRemoteImageMemoryContainer and insert into the memoryCache and  would store the data directly into the diskCache.

As a workaround, you could store the data directly to the disk cache with `cacheKeyForURL:processorKey:` and `setObjectOnDisk:forKey:` The disadvantage of this is it will need to be loaded into the memoryCache from disk on the next access.

Hope this helps! Going to close this, but please feel free to reply back if it's not clear.

**Comment by zachwaugh** [comment]
@garrettmoon thanks! I'll take a look at adding that functionality and opening a PR

**Comment by garrettmoon** [comment]
Awesome, thanks @zachwaugh !
