### ISSUE TITLE
How to make the loading picture is blur?

### ISSUE THREAD

**Issue by xhzengAIB** [pinterest/PINRemoteImage#29]
Hi! @garrettmoon  

Like this gif loading picture effect:

https://github.com/pinterest/PINRemoteImage/blob/master/progressive.gif

Jack

**Comment by garrettmoon** [comment]
Well, the image has to be a JPEG that is progressively encoded. Then it's just as the docs say:

UIImageView *imageView = [[UIImageView alloc] init];
[imageView pin_setUpdateWithProgress:YES];
[imageView pin_setImageFromURL:[NSURL URLWithString:@"http://pinterest.com/progressiveKitten.jpg"]];

You can see it in action by downloading the example app.

**Comment by xhzengAIB** [comment]
Thank！
Need specific photo element to reach the blur effect
