### ISSUE TITLE
[Question] Clearing the Disk Cache

### ISSUE THREAD

**Issue by hannahmbanana** [pinterest/PINRemoteImage#290]
Question from the ASDK slack channel:

To manually clear the disk cache, you must currently import the following file to be able to call `-removeAllObjects`. This may be new behavior?

`#import <PINRemoteImageCaching.h>`

Are `PINRemoteImage` and `PINCache` intentionally unpaired so that you don’t have to use `PINCache` if you don’t want it?

cc @lappp9

**Comment by lappp9** [comment]
Also, does setting a cache limit via `[[PINDiskCache sharedCache] setByteLimit:_]` affect the disk cache disk cache in `[[PINRemoteImageManager sharedImageManager] defaultImageCache]`?

**Comment by garrettmoon** [comment]
Yes, they are intentionally unpaired, by default PINRemoteImage will use PINCache (and you can cast calls to cache; there must be a better way to describe this… possibly a `PINCache` instance which returns nil if it's not being used?)

@lappp9 It appears the answer to you question is no, they will be different caches. Which is surprising to me and I don't think should be the case. Please open an issue in PINCache :)

**Comment by lappp9** [comment]
@garrettmoon ok cool thanks, 👍 will do
