### ISSUE TITLE
PINCache not used

### ISSUE THREAD

**Issue by docterd** [pinterest/PINRemoteImage#291]
Hey guys,

I can't get PINRemoteImage to use PINCache with 3.0.0-beta.7. I'm using following Cocoapods dependency.

> pod 'PINRemoteImage/Core', '~> 3.0.0-beta.7'
> pod 'PINRemoteImage/PINCache' 
> pod 'PINRemoteImage/WebP' 
> 

Unfortunately USE_PINCACHE is always set to false, so that it uses the PINRemoteImageBasicCache.

**Comment by appleguy** [comment]
@garrettmoon this is an interesting report.  Thanks for filing @docterd!  If you could try any of the example projects (maybe even one from AsyncDisplayKit/examples) to see if it also reproduces there, that would be helpful.

**Comment by garrettmoon** [comment]
@docterd are you still having this issue? Going to close this for now but please reply back if you still are!
