### ISSUE TITLE
Add method to return PINCache instance if the cache is an instance of PINCache.

### ISSUE THREAD

**Issue by plm75** [pinterest/PINRemoteImage#296]
Hi, 
Thanks for the great library.

I'm currently using ASDK + PINRemoteImage/PINCache in a couple of projects.  While this works great, the disk usage is just crazy:  after just a few launches, disk usage per app is several hundred megabytes ?! 

Am I correct to assume that out of the box and without any specific settings, PINCache does not set any limits of disk space usage ?

I looked at some old issues, but they refer to some APIs that seem to have been deprecated like `manager.cache.diskCache.byteLimit = 20_000_000` , 

All in all, documentation is really lacking in this area: all I want to do is set a diskLimit of say 100MB for caching images plus a TTL of 2 days.  How do I do that / where do I find the info to do it ?  Are there any specifics to be aware of when using PINRemoteImage/PINCache is Swift with ASDK ?

**Comment by baby03201** [comment]
+1 looking for alternative solution to set cost and byteLimit to cache

**Comment by ViaJables** [comment]
+1 How do you do this? Currently cache just grows until it throws an OOM.

**Comment by garrettmoon** [comment]
@ViaJables just cast the cache to a PINCache instance

**Comment by ViaJables** [comment]
@garrettmoon EUREKA IT WORKS!

**Comment by garrettmoon** [comment]
Yay! Trying to make this better now…

**Comment by garrettmoon** [comment]
You can now use the `pinCache` property after importing `PINCache+PINRemoteImageCaching.h`
