### ISSUE TITLE
Race condition when cleaning up and creating temporary directory

### ISSUE THREAD

**Issue by master-nevi** [pinterest/PINRemoteImage#298]
I'm experiencing a race condition where the temp directory cleanup [here](https://github.com/pinterest/PINRemoteImage/blob/3.0.0-beta.7/Pod/Classes/PINAnimatedImageManager.m#L50) will occur just after the check to see if the temp directory needs to be created in `init` [here](https://github.com/pinterest/PINRemoteImage/blob/3.0.0-beta.7/Pod/Classes/PINAnimatedImageManager.m#L85). Files then fail to be created for the duration of the application lifetime [here](https://github.com/pinterest/PINRemoteImage/blob/3.0.0-beta.7/Pod/Classes/PINAnimatedImageManager.m#L483) as the temp directory doesn't actually exist.

**Comment by garrettmoon** [comment]
Ah, yes, PINDiskCache solves this I think with an NSConditionLock:
https://github.com/pinterest/PINCache/blob/master/PINCache/PINDiskCache.m#L151

**Comment by master-nevi** [comment]
Just curious. Is there any reason `PINAnimatedImageManager` shouldn't just use `PINDiskCache` instead? Then there would only have to be a single cache to worry about.

**Comment by garrettmoon** [comment]
@master-nevi because we memory map these files in and rely on them to exist to back NSData objects. PINDiskCache doesn't guarantee files won't be deleted underneath it.

**Comment by garrettmoon** [comment]
Ah, this was fixed!
