### ISSUE TITLE
Feature request: pre-build framework (or static library)

### ISSUE THREAD

**Issue by alexvimpekable** [pinterest/PINRemoteImage#30]
Hi,

Your library is awesome! Yesterday I've replaced our own simple caching solution with PINRemoteImage and our app http://marqueemoviesapp.com got a really noticeable speed boost. But I can't say that was easy thing to do and IMHO most of the developers does not want to fiddle with sources and spend their time building external libraries.

Could you consider providing PINRemoteImage as a framework or static library?

Thanks,
Alex

**Comment by dcaunt** [comment]
Related: Carthage support #25

**Comment by garrettmoon** [comment]
Yeah, I think we're likely to add Carthage support as it would get us most if not all of the way there.

**Comment by alexvimpekable** [comment]
Guys, it's a pain to strip all examples, docs and other non-essential stuff from the sources if you don't using pods. Framework?

**Comment by garrettmoon** [comment]
@alexvimpekable would happily accept a pull request!

**Comment by garrettmoon** [comment]
Hey, we have this now! Going to close this out.
