### ISSUE TITLE
button.setImage doesn't set the image (ends up being the tint color)

### ISSUE THREAD

**Issue by SuperTango** [pinterest/PINRemoteImage#303]
I'm using PINRemoteImage 2.1.4 from a Pod, XCode 8.2, Swift 3. When doing:

    let url = URL(string: "https://placehold.it/300/ff3300")
    self.button.pin_setImage(from: url)

The button doesn't contain the image.  It just shows the tint color.  

Here's an example that calls button.pin_setImage at the same time as calling imageView.setImage on the same image.  This also happens if I just use the button.

![simulator_screenshot_fri jan 27 09 45 49 pst 2017](https://cloud.githubusercontent.com/assets/709342/22381164/688b74a0-e475-11e6-8047-4ba2f12621b8.png)

An example repo can be found at  https://github.com/SuperTango/PINRemoteImageButtonTint

**Comment by garrettmoon** [comment]
@SuperTango Did you intend to set it as a background image?

I downloaded the image manually and changed the code to:

```
let textImage = UIImage(named: "text.png")
self.button.setImage(textImage, for: .normal)
//self.button.pin_setImage(from: url)
```

And got the same results as your screenshot.

If you're intention is to download and set a background image, that functionality would need to be added.

I'm going to close this for now, but please feel free to reply back.

**Comment by SuperTango** [comment]
No, I just want to set the normal image instead of a button using PINRemoteImage.  So instead of 

    self.button.setImage(UIImage(...), for: .normal))

I want to set the image using a PINRemoteImage.  

If that API call isn't the one to use, which one should we use?  

And what are these methods defined in the UIButton category for?

```
@implementation PINImageView (PINRemoteImage)

- (void)pin_setImageFromURL:(NSURL *)url
{
    [PINRemoteImageCategoryManager setImageOnView:self fromURL:url];
}

- (void)pin_setImageFromURL:(NSURL *)url placeholderImage:(PINImage *)placeholderImage
{
    [PINRemoteImageCategoryManager setImageOnView:self fromURL:url placeholderImage:placeholderImage];
}

- (void)pin_setImageFromURL:(NSURL *)url completion:(PINRemoteImageManagerImageCompletion)completion
{
    [PINRemoteImageCategoryManager setImageOnView:self fromURL:url completion:completion];
}

- (void)pin_setImageFromURL:(NSURL *)url placeholderImage:(PINImage *)placeholderImage completion:(PINRemoteImageManagerImageCompletion)completion
{
    [PINRemoteImageCategoryManager setImageOnView:self fromURL:url placeholderImage:placeholderImage completion:completion];
}

- (void)pin_setImageFromURL:(NSURL *)url processorKey:(NSString *)processorKey processor:(PINRemoteImageManagerImageProcessor)processor
{
    [PINRemoteImageCategoryManager setImageOnView:self fromURL:url processorKey:processorKey processor:processor];
}

- (void)pin_setImageFromURL:(NSURL *)url placeholderImage:(PINImage *)placeholderImage processorKey:(NSString *)processorKey processor:(PINRemoteImageManagerImageProcessor)processor
{
    [PINRemoteImageCategoryManager setImageOnView:self fromURL:url placeholderImage:placeholderImage processorKey:processorKey processor:processor];
}

- (void)pin_setImageFromURL:(NSURL *)url processorKey:(NSString *)processorKey processor:(PINRemoteImageManagerImageProcessor)processor completion:(PINRemoteImageManagerImageCompletion)completion
{
    [PINRemoteImageCategoryManager setImageOnView:self fromURL:url processorKey:processorKey processor:processor completion:completion];
}

- (void)pin_setImageFromURL:(NSURL *)url placeholderImage:(PINImage *)placeholderImage processorKey:(NSString *)processorKey processor:(PINRemoteImageManagerImageProcessor)processor completion:(PINRemoteImageManagerImageCompletion)completion
{
    [PINRemoteImageCategoryManager setImageOnView:self fromURLs:url?@[url]:nil placeholderImage:placeholderImage processorKey:processorKey processor:processor completion:completion];
}

- (void)pin_setImageFromURLs:(NSArray <NSURL *> *)urls
{
    [PINRemoteImageCategoryManager setImageOnView:self fromURLs:urls];
}

- (void)pin_setImageFromURLs:(NSArray <NSURL *> *)urls placeholderImage:(PINImage *)placeholderImage
{
    [PINRemoteImageCategoryManager setImageOnView:self fromURLs:urls placeholderImage:placeholderImage];
}
```

**Comment by garrettmoon** [comment]
@SuperTango That's the correct one, but as I said, if you download the image manually and try and set it via setImage it doesn't work either (it produces the exact same results as your screenshot), so I don't believe this is a PINRemoteImage issue.

**Comment by alibasta** [comment]
@garrettmoon nope - just tested it and:

`tile1.setImage(UIImage(named: "PlayButton"), for: .normal)`

works as designed and shows the image. I'm also interested in using PINRemoteImage for async image loading for UIButton.

**Comment by garrettmoon** [comment]
@alibasta can you upload a sample app that demonstrates this please?

**Comment by garrettmoon** [comment]
I'm going to close this for now. I'll re-open if you upload a sample app.
