### ISSUE TITLE
Crash possibly related to upgrade from Beta 2 to Beta 7

### ISSUE THREAD

**Issue by KristopherGBaker** [pinterest/PINRemoteImage#304]
I recently released a new version of my company's app and some users have run into a crash when the app starts.  I personally haven't been able to reproduce the crash, but it happened to my manager and part of the crash log is below.  The new version upgrades ASDK to 2.0.2 (from 1.9.81) and PINRemote Image from Beta 2 to Beta 7.  It seems like it might be related to the way defaultImageCache in PINRemoteImageManager changed to delete the disk cache.  Based on the stacktrace, it would appear to occur at  https://github.com/pinterest/PINRemoteImage/blob/ed2e439faf2462097c8cbe5ce7a526299a2f2267/Pod/Classes/PINRemoteImageManager.m#L251 , since that's the only place removeItemAtURL is used by PINRemoteImage.

Do you have any insight as to why this might happen, or if it might be something on my end that's not correct?

Partial crash log attached, we had trouble getting it to symbolicate.
[crashlog.txt](https://github.com/pinterest/PINRemoteImage/files/740003/crashlog.txt)

**Comment by garrettmoon** [comment]
@KristopherGBaker it's really hard to tell without a stack trace. I would be more inclined to guess this has something to do with the race condition in PINAnimatedImageManager. Was your manager loading any GIFs?

**Comment by KristopherGBaker** [comment]
I'll see if I can get the full stack trace.  We aren't loading any GIFs.

**Comment by KristopherGBaker** [comment]
Full desymbolicated crash log attached.  Based on the exception code 0x8badf00d, the problem is that the app is taking too long to start and thus being killed by the system.  My best guess at this point is if the old disk cache is large, it may be taking too long to remove it while the app is starting in some cases.

[crashlog-full.txt](https://github.com/pinterest/PINRemoteImage/files/740152/crashlog-full.txt)

**Comment by garrettmoon** [comment]
@KristopherGBaker are you still seeing this crash? Beta 9 has attempted to address this.

**Comment by KristopherGBaker** [comment]
@garrettmoon I am no longer seeing this crash, and am currently using beta 9.

**Comment by garrettmoon** [comment]
Awesome! Thanks for reporting back.

**Comment by yoichitgy** [comment]
Just information for anyone who faced this issue:
I also experienced this issue, and PR #391 and `3.0 beta 12` fixed it.
