### ISSUE TITLE
Change image cache class

### ISSUE THREAD

**Issue by fonkadelic** [pinterest/PINRemoteImage#31]
I would like to use multiple image caches with different parameters (e.g. `ageLimit`). What is the preferred way to accomplish this?

Subclassing `PINRemoteImageManager` is not that easy, because it's shared instance is used for all view categories.

**Comment by garrettmoon** [comment]
This would require a pretty big change. One idea I had while writing the library was to have a caching delegate. This could move us towards removing the dependency on PINCache which would also be a nice benefit. Happy to see a pull request!

**Comment by skeeet** [comment]
@garrettmoon is this still a thing? 
Because if it is, then i'd suggest to extend feature scope to having customizable downloader as well, and have working implementation with pluggable cache/download manager, which i'll gladly cleanup and submit as PR.

**Comment by garrettmoon** [comment]
@skeeet That'd be great!

**Comment by skeeet** [comment]
PR #225 does not include customizable downloader for now.

**Comment by garrettmoon** [comment]
Going to close this one out since there's now support for plugging in an arbitrary cache.
