### ISSUE TITLE
Images mixed up while using with UICollectionView

### ISSUE THREAD

**Issue by itspradhan** [pinterest/PINRemoteImage#32]
When Collectionview reuses the view then images get mixed up. 
Let suppose there is cell A, and code made a request for IMG_URL_1 that is 43KB It will take time to load CollectionView while scrolling reuses cell A again and this time code made a request for IMG_URL_6 for this cell, and this image is only of 6KB, so it will load faster while IMG_URL_1 still in loading process. First view gets updated with IMG_URL_6 image because it loaded early, but after few mili seconds IMG_URL_1 also get loaded so cell will get updated again with IMG_URL_1 this time. But it should display IMG_URL_6 image instead of IMG_URL_1 image.

**Comment by itspradhan** [comment]
Found placeholder image which fixed it.
 
cell.OfferImage.pin_setImageFromURL(imageURL, placeholderImage:(UIImage(named: "placeholder.png")))

**Comment by garrettmoon** [comment]
Out of curiosity, were you using setImageFromURL or were you downloading the images directly and setting them on the image view. If you were doing the former, this shouldn't have happened, regardless of if there is a placeholder image set.

**Comment by itspradhan** [comment]
Hi Garrett,

I was using pin_setImageFromURL method as I was getting error while using setImageFromURL method. But I wasn't downloading the images directly and setting them on image view.

**Comment by garrettmoon** [comment]
That sounds like a real bug then, do you think you could send a sample project to garrett@pinterest.com? It'd be greatly appreciated :)

**Comment by itspradhan** [comment]
Sure Garrett I would be happy to help I will send them to you by tmr :)

**Comment by claudiagrilli** [comment]
Hi! Any news about it? It is still there...I used the Network Link Conditioner to simulate a slow network. I have version 3.0.0 beta 7 and the images are coming mixed in a collection view. Thanks.

**Comment by garrettmoon** [comment]
@claudiagrilli would you mind sending me a sample project to garrett@pinterest.com?

**Comment by claudiagrilli** [comment]
Actually I managed to solve it just cancelling the download in prepareForReuse and setting the image to nil. But now I have the problem that when I scroll back the download needs to restart from the beginning..Is there a better way? Thanks!

**Comment by garrettmoon** [comment]
@claudiagrilli Changing the URL in prepareForReuse should actually have the same effect, if it's not, I'd still love to see a sample project.

Separately, instead of canceling the download, if you want to allow it to continue but not report the result (i.e. it should be cached), you should be able to call pin_setDownloadImageOperationUUID:nil *before* setting a new image URL. This will make it so the image view ignores the result of the current download operation (i.e. it will get cached, but the results won't be set on the image view).
