### ISSUE TITLE
(3.0.0-beta.8) how to download gif?

### ISSUE THREAD

**Issue by aimobier** [pinterest/PINRemoteImage#324]
Hello, I put our library version upgraded to (3.0.0-beta.8). One way before but I found I can't use.

````
    [[PINRemoteImageManager sharedImageManager] downloadImageWithURL:[[NSURL alloc]initWithString:self] options:PINRemoteImageManagerDownloadOptionsNone completion:^(PINRemoteImageManagerResult * _Nonnull result) {
        
        if( result.image ) {
            
        }
        
        if ( result.animatedImage ) {
            
        }
    }];
````

What I want to download a gif, not possible, please let's now how to handle dynamic picture now?

**Comment by maicki** [comment]
@aimobier Did you link `FLAnimateImage` in your project? @garrettmoon correct me if I'm wrong, but you need `FLAnimateImage` in your project to support handling of gifs.

**Comment by garrettmoon** [comment]
Yes, at the current time you need FLAnimatedImage. In the future we may support native GIF handling, but it's still a WIP.

**Comment by aimobier** [comment]
I'm sorry ,I didn't explain clearly, I'm not just showing gif. If you just show GIF using the `FLAnimateImage ` is ok. 
Now I want to download GIF, get the `NSData` for this gif. After the operation of the gif. Your previous approach may have supported me, but the new version seems to have removed this method

Before:

`PINRemoteImageManagerResult`has a `animatedImage`
````objective-c
    [[PINRemoteImageManager sharedImageManager] downloadImageWithURL:[[NSURL alloc]initWithString:self] options:PINRemoteImageManagerDownloadOptionsNone completion:^(PINRemoteImageManagerResult * _Nonnull result) {
     
        if( result.image ) {
              // handle normal image balabala~~~
        }
        if ( result.animatedImage ) {
             // handle gif image balabala~~~
        }
    }];
````

but now,the `animatedImage` Disappeared……

**Comment by maicki** [comment]
@aimobier `animagedImage` was renamed to `alternativeRepresentation`. Also look into the `testGIFDownload` test in `PINRemoteImage_Tests` for an example.

**Comment by aimobier** [comment]
Thank you very much, to cause unnecessary trouble, I'm sorry.  🍻🍻🍻🍻
