### ISSUE TITLE
[carthage] [3.0.0-beta.3] value of type 'UIImageView?' has no member 'pin_setImage'

### ISSUE THREAD

**Issue by dodikk** [pinterest/PINRemoteImage#327]
The `PinRemoteImage.framework` does not expose `UIImage` dependency as a public header.

P.S. I am targeting iOS and using `github "pinterest/PINRemoteImage" "3.0.0-beta.3"` in my cartfile

**Comment by dodikk** [comment]
> There are built-in categories on UIImageView, FLAnimatedImageView and UIButton

The header for `UIImageView` is missing in a framework's umbrella header. For this reason the build fails for me.

**Comment by dodikk** [comment]
Sorry. I was missing `import PINRemoteImage`.
I also was confused by the `PINImage` macro replacements as the `UIImage` category lookup has not given any results.

**Comment by garrettmoon** [comment]
@dodikk no worries, glad you figured it out!
