### ISSUE TITLE
[Feature] PINAnimatedImage as a replacement for FLAnimatedImage

### ISSUE THREAD

**Issue by jverdi** [pinterest/PINRemoteImage#330]
I see that PINAnimatedImage has been added to the project - awesome. As far as I can tell, it is only being used in conjunction with AsyncDisplayKit at present. 

Is there a plan to make PINAnimatedImage also work as a stand-in for FLAnimatedImage for those using PINRemoteImage but not AsyncDisplayKit? 

It seems like creating something akin to FLAnimatedImageView would allow you to drop the FLAnimatedImage dependency (which sadly, doesn't seem to be a very actively maintained project anymore).

**Comment by garrettmoon** [comment]
@jverdi it's on the map but low priority. The intention would be to actually create a hybrid solution which, depending on the GIF size uses the technique that FLAnimatedImage uses or the PINAnimatedImage version.

**Comment by garrettmoon** [comment]
I did this! Please give it a try on master!

**Comment by jverdi** [comment]
@garrettmoon great! We'll give it a try soon
