### ISSUE TITLE
Caching question

### ISSUE THREAD

**Issue by alibasta** [pinterest/PINRemoteImage#332]
Hi guys,

thank you very much for your work! Awesome!

I want to use PINRemoteImage in my current project but need to solve the problem that images are updated on the server side using the same image url.

I looked in the code and PINRemoteImage is just checking locally if the image is inside the device cache. If that is true it returns the image and ignores perhaps newer images on the url. Is that true? Best would be if PINRemoteImage would use the caching headers like modified-since or just show the locally cached image as a placeholder and downloads the new image and updates the view.

Any ideas how I could use PINRemoteImage to also check for images if the user is online, the url is the same and the image exists locally already?

Thank you very much!

Best

Alex

**Comment by garrettmoon** [comment]
Hey @alibasta sorry for the super late reply :(

PINRemoteImage doesn't really have a good solution for this currently. The only work around is to ignore the cache on a request. I'd be open to pull requests that added support for this though!
