### ISSUE TITLE
Downloading Gif returns a UIImage instead of animated image.

### ISSUE THREAD

**Issue by Myrenkar** [pinterest/PINRemoteImage#334]
Hello :)

I'm using your library to fetch some gifs. I got interested that your library can return `FLAnimatedImage`

My setup:

* I'm using Carthage 
* Project is uses iOS 9.3+ issue is spotted on 10.2, but it probably would happen on both.
* I have collectionView cell with FLAnimatedImageView 
* My ViewController imports both 
```objc
#import <FLAnimatedImage/FLAnimatedImageView.h>
#import <PINRemoteImage/PINRemoteImage.h>
```
* I use method as you mentioned: 
```objc
    [cell.gifImageView pin_setImageFromURL:self.posts[indexPath.row].photoURL completion:^(PINRemoteImageManagerResult *result) {
        if (result.requestDuration > 0.25) {
            [UIView animateWithDuration:0.3 animations:^{
                weakCell.gifImageView.alpha = 1.0f;
            }];
        } else {
            weakCell.gifImageView.alpha = 1.0f;
        }
    }];
```
or simply 
```objc
 [cell.gifImageView pin_setImageFromURL:self.posts[indexPath.row].photoURL];
```
and my cell has an image fetched but it is not moving.
Maybe it is beacuase:
```
(lldb) po result.animatedImage
 nil
(lldb) po result.image
<UIImage: 0x600000280ff0>, {175, 128}
```

Could you please check it?

**Comment by maicki** [comment]
@Myrenkar Hey! Would it be possible to either provide a small example app that shows the problem or add a link to a URL for a gif to this issue so we reproduce the issue. Thanks!

**Comment by Myrenkar** [comment]
I'm using tumblr api for this and this is one of URL's :)

```url
http://68.media.tumblr.com/tumblr_m2ekw5lseA1rth4ijo1_250.gif
```

**Comment by maicki** [comment]
Hey @Myrenkar I just tried your link out in our Swift Example. I change the scroll view controller to have a `FLAnimatedImageView` in the cell and also change one tab to just show an `FLAnimatedImageView`. Both of them work as expected.

Can you please look over this code and see what could be the problem on your side:
[Swift-Example.zip](https://github.com/pinterest/PINRemoteImage/files/856492/Swift-Example.zip)

Thanks!

**Comment by garrettmoon** [comment]
I'm going to close this for now, please feel free to ping if you're still having issues.
