### ISSUE TITLE
Does not compile when using pod 'PinRemoteImage/WebP' in a Swift project with use_frameworks!

### ISSUE THREAD

**Issue by Cen92** [pinterest/PINRemoteImage#337]
When compiling it can't find "libwebp/webp/decode.h". I have added $(SRCROOT)/libwebp/webp as a recursive user header search path but it still doesn't work. 

from PinImage+WebP.m

`#ifdef PIN_WEBP
#if !COCOAPODS
#import "webp/decode.h"
#else
#import "libwebp/webp/decode.h"
#endif
`

**Comment by garrettmoon** [comment]
@Cen92 sorry for the late reply, are you using cocoa pods? Have you tried the latest beta?
