### ISSUE TITLE
Feature request: progressive jpeg on iOS 7

### ISSUE THREAD

**Issue by chiahsien** [pinterest/PINRemoteImage#34]
I dig into the source and try to disable iOS 8 checking, but my app crashes when displaying the jpeg.
I try to fix this but failed.
Is there any ways to support progressive jpeg on iOS 7?

**Comment by mheras** [comment]
I also need this in iOS7! Please!!

**Comment by garrettmoon** [comment]
I don't think we're realistically ever going to support this, sorry :(
