### ISSUE TITLE
xcode 8.3.x won't build PINRemoteImage with FLAnimatedImage 

### ISSUE THREAD

**Issue by jonathanduty** [pinterest/PINRemoteImage#347]
Hi There,
We are including PINRemoteImage using cocoapods.  
things work fine in xcode 8.2.x.  However, when upgrading to xcode 8.3 and 8.3.1 I get the followng build error when building with FLAnimatedImage included:

/Users/jonathanduty/Development/arcivr/ceremony-ios/Pods/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:71:12: Duplicate definition of category 'Logging' on interface 'FLAnimatedImage'

/Users/jonathanduty/Development/arcivr/ceremony-ios/Pods/PINRemoteImage/Pod/Classes/PINRemoteImageManagerResult.h:19:2: In module 'FLAnimatedImage' imported from /Users/jonathanduty/Library/Developer/Xcode/DerivedData/Ceremony-gncdaompymwavtbxxgskhwmdiagc/Build/Products/Debug-iphonesimulator/PINRemoteImage/PINRemoteImage.framework/Headers/PINRemoteImageManagerResult.h:19:

I've verified that downgrading to xcode 8.2 still builds correctly.  Here is my podfile.lock
[Podfile.lock.zip](https://github.com/pinterest/PINRemoteImage/files/943536/Podfile.lock.zip)

**Comment by garrettmoon** [comment]
@jonathanduty are you using the latest beta of PINRemoteImage? Can you upload a sample project somewhere?

**Comment by jonathanduty** [comment]
hi @garrettmoon  thanks for the reply.  We are on version:
  - PINRemoteImage (~> 2.1.4)
  PINRemoteImage: 4ac4011c5caefd6befd99758e09becede05d3226

**Comment by garrettmoon** [comment]
@jonathanduty I just tried modifying the Example project in the repo to:
```
xcodeproj 'PINRemoteImage.xcodeproj'

def shared_pods
  pod "PINRemoteImage", '~> 2.1.4'
  pod "FLAnimatedImage", '~> 1.0'
end

target 'PINRemoteImage' do
  shared_pods
end
```

And was able to build fine. Can you upload a sample project that reproduces the issue?

**Comment by jonathanduty** [comment]
I generated a new project and it builds ok.  I even added all the pods we are using from my old project and it still works.  Looking at the projects side-by-side I noticed that the project that builds does not have the "Framework Search Paths" variable in the build settings.  Could this be it?  
![ceremony_xcodeproj](https://cloud.githubusercontent.com/assets/49163/25847464/e77823fc-347b-11e7-85a2-3b3875a4b81c.png)

**Comment by jonathanduty** [comment]
Ok, I figured it out.  I needed to remove all direct imports in our code 
#import "FLAnimatedImage.h"

We were using FLAnimatedImage directly in some places.  So change all places where we had this:

#import "FLAnimatedImage.h"
#import "PINImageView+PINRemoteImage.h"

to this

#import "PINImageView+PINRemoteImage.h"

And it builds.  

An interesting note is this only happens in Code 8.3 and above.  XCode 8.2 builds just fine with both of those files imported.

**Comment by garrettmoon** [comment]
Super weird! Glad you figured it out!
