### ISSUE TITLE
Set FLAnimatedImage as an optional dependency

### ISSUE THREAD

**Issue by lexrus** [pinterest/PINRemoteImage#35]
Since they don't update FLAnimatedImage for a while. The [issues list](https://github.com/Flipboard/FLAnimatedImage/issues) just getting longer. And it's [not compatible with Swift project](https://github.com/Flipboard/FLAnimatedImage/issues/75). I'd recommend set FLAnimatedImage as an optional dependency.

**Comment by garrettmoon** [comment]
This is a duplicate of #22
