### ISSUE TITLE
Question: Cached image returned instead of downloading new one

### ISSUE THREAD

**Issue by AngeloGiurano** [pinterest/PINRemoteImage#352]
Hello,

I've got a problem I'm uploading a new image to the new url so after successful upload to the server I'm doing as follows:

```
let cacheKey = PINRemoteImageManager.shared().cacheKey(for: url, processorKey: "UserProfile")
                PINRemoteImageManager.shared().cache.removeObject(forKey: cacheKey, block: { (_, _, _) in
                    let object = PINRemoteImageManager.shared().cache.object(forKey: cacheKey)
                    print(object)
                    self.hideLoadingHUD()
})
```

Everything is fine since in the block the object is nil.

After that in my profile image I'm trying to get the new image by:

```
profileImage.pin_setImage(from: thumbnailURL, processorKey: "UserProfile") { [unowned self] (result, unsafePointer) -> UIImage? in
                    guard let image = result.image else { return nil }
                    let croppedImage = Toucan(image: image).resize(self.profileImage.frame.size, fitMode: .clip).image
                    return croppedImage
                }
```
But I still get the previous image.

I can ensure the url is the same and the image is actually on the server, am I missing something?

**Comment by garrettmoon** [comment]
@AngeloGiurano Hmm, I'm wondering if it has something to do with the processing… Would you be able to upload a sample project that shows this issue?

**Comment by AngeloGiurano** [comment]
@garrettmoon It actually does have something to do with the processorKey, I've changed it to nil and everything works fine, I'll try to create a sample project this weekend

**Comment by garrettmoon** [comment]
Cool, thanks in advance :)

**Comment by garrettmoon** [comment]
I'm going to close this for now, I'll re-open when you upload a sample project.
