### ISSUE TITLE
Sometimes pin_setImage for gif, but sometimes it is showing gif file rotated.

### ISSUE THREAD

**Issue by superdev89** [pinterest/PINRemoteImage#359]
Is there any orientation option?

**Comment by garrettmoon** [comment]
@superdev89 I haven't heard any reports of rotated GIFs… are you using Texture?

**Comment by superdev89** [comment]
No

**Comment by garrettmoon** [comment]
@superdev89 yeah, uploading a sample project which reproduces would greatly help diagnose the issue.

**Comment by garrettmoon** [comment]
Going to close this, please feel free to post a sample project and I'll take a look!
