### ISSUE TITLE
use of @import when modules are disabled

### ISSUE THREAD

**Issue by Mattr-eden** [pinterest/PINRemoteImage#36]
Not sure if it's because I'm developing in swift using a bridging header, or because my project is running on top of Unity but the @import lines at the top of some of your source code cause the error "use of @import when modules are disabled". I've gone through my project settings as well as the cocoapods settings and enabled modules but I eventually had to go through and hack out the @import with the old style #import, which we will have to do again if cocoa pods updates the pod! 

I think it's probably the Unity aspect of my project as we have to use Objective-C++.  

Other than that great job on the library, far quicker and more robust than the solution we were using previously.

**Comment by garrettmoon** [comment]
Thanks for reporting this! I'm going to close the issue because you're suggesting it's probably unity, but if anyone else stumbles upon this and can attribute it to PINRemoteImage, please re-open.

**Comment by aleksgapp** [comment]
+1 Faced the same issue with Objective-C++ project without unity.

**Comment by garrettmoon** [comment]
Lame, looks like modules aren't available with objective c++

I'll have to think about a solution, I'm open to suggestions :)

**Comment by aleksgapp** [comment]
You can use standard `#import`, as it will be automatically mapped to an `@import` if modules are enabled. So there is no need to use `@import` explicitly. See [this](http://clang.llvm.org/docs/Modules.html#includes-as-imports).

Also I found [this](http://stackoverflow.com/a/20708695/1752675) old answer on stackoverflow that point to some experimental command-line parameter for llvm. 
```
-fcxx-modules
    Enable the modules feature for C++ (EXPERIMENTAL and VERY BROKEN).
```
However, I didn't find it in llvm docs for now.

**Comment by garrettmoon** [comment]
Great! Mind putting up a pull request? Preferably with the #import, not the experimental very broken :)

**Comment by nap-sam-dean** [comment]
Hi everyone.

I've made a pull request that I think is what you're after : https://github.com/pinterest/PINRemoteImage/pull/64 - let me know if that's ok :)

**Comment by garrettmoon** [comment]
I think it should too!
