### ISSUE TITLE
forHTTPHeaderField  not working ,so how can we set custom headers ?

### ISSUE THREAD

**Issue by iOSUser110** [pinterest/PINRemoteImage#365]
PINRemoteImageManager.shared().setValue("1111", forHTTPHeaderField: "X-API-KEY")
with this new release

**Comment by iOSUser110** [comment]
actually the httpHeaderFIeld is provieded by Texture or Async Display Kit.

**Comment by garrettmoon** [comment]
@iOSUser110 Texture uses it's own version of PINRemoteImage, not the shared manager. Take a look at ASPINRemoteImageDownloader.h

**Comment by aimobier** [comment]
So how do I customize header? Is there any intuitive code or example?

@garrettmoon 

I found this, but I think the authentication information of header will change.

````objective-c
+ (void)setSharedImageManagerWithConfiguration:(NSURLSessionConfiguration *)configuration
{
    NSAssert(sharedImageManager == nil, @"sharedImageManager singleton is already configured");

    dispatch_once(&sharedDispatchToken, ^{
        sharedImageManager = [[[self class] alloc] initWithSessionConfiguration:configuration];
    });
}
````

**Comment by aimobier** [comment]
🙏
