### ISSUE TITLE
Crash on [PINAnimatedImage processAnimatedImage]

### ISSUE THREAD

**Issue by BanningLiu** [pinterest/PINRemoteImage#368]
![crash](https://user-images.githubusercontent.com/17246773/26958618-47bb74f4-4cfe-11e7-83d1-9524f824f684.png)
Attempt to allocate 8388608 bytes for NS/CFData failed.

**Comment by garrettmoon** [comment]
@BanningLiu this means your app ran out of memory, there's nothing PINRemoteImage can do about that :(
