### ISSUE TITLE
lexical or preprocessor issue libwebp/webp/decode.h file not found

### ISSUE THREAD

**Issue by hongdangodori** [pinterest/PINRemoteImage#375]
I put PINRemoteImage and PINRemoteImage / Webp in podfile and I get the following error.
`'libwebp/webp/decode.h' file not found`

my pod file is 
  ```
pod 'PINCache'
  pod 'PINRemoteImage'
  pod 'PINRemoteImage/WebP'

```
I use with use_frameworks! in podfile

Personally I have added "$ {PODS_ROOT}" to the Header Search Paths in the build setting of PINRemoteImage and I changed `#import "libwebp / webp / decode.h"` in the header of PINImage + WebP.m to `#import "libwebp / src / webp / decode.h"` to solve this problem. So it was solved.
But I do not think it is a neat solution. Can I solve it in a different way than this?

**Comment by garrettmoon** [comment]
@hongdangodori does it work without the `use_frameworks!` directive?

**Comment by hongdangodori** [comment]
I've never done that, I can not erase it because I have to use swift in my project.
According to github, it looks like this:
> use_frameworks tells CocoaPods that you want to use Frameworks instead of Static Libraries. Since Swift does not support Static Libraries you have to use frameworks.

**Comment by maicki** [comment]
@hongdangodori Hey! Currently if you just define `PINRemoteImage` in your podfile it fetches version 2.1.4 and not the latest version. This version has problems with the webp imports. To get the latest version please add the following to your Podfile and it should fix your errors:

```
pod 'PINRemoteImage', :git => 'https://github.com/Pinterest/PINRemoteImage.git', :tag => '3.0.0-beta.10'
  pod 'PINRemoteImage/WebP', :git => 'https://github.com/Pinterest/PINRemoteImage.git', :tag => '3.0.0-beta.10'
```

Please let me know in case this will not resolve your issues. Thanks!
