### ISSUE TITLE
Custom request retry strategy

### ISSUE THREAD

**Issue by hovox** [pinterest/PINRemoteImage#387]
Currently if request fails due to, let's say _no connection error_ , the the framework will try to retry after 4 seconds then after 16 seconds (4^2), then after 64 seconds (4^3) and only after that the framework will give up and call request failed callback. It means user will see error message after `4+16+64=84` seconds. In some cases would be great to be able to specify custom retry logic. I have created a version with older PINRemoteImage version, tried to make a pull request, seems a lot has been changed, here is the [link](https://github.com/hovox/PINRemoteImage/tree/custom-retry-strategy) to that implementation. I saw that there is a way to skip retrying, it could be the solution in some cases, but overall would be great to have more control on that.

**Comment by garrettmoon** [comment]
PR here: https://github.com/pinterest/PINRemoteImage/pull/386
