### ISSUE TITLE
Crash on [PINAnimatedImage frameCount]

### ISSUE THREAD

**Issue by zjmdp** [pinterest/PINRemoteImage#389]
v3.0.0-beta.11

crash log:
http://crashes.to/s/c0f8fc7c80e

**Comment by garrettmoon** [comment]
@zjmdp Are you displaying multiple GIFs at once? That's currently a known issue I haven't had time to look into.

**Comment by zjmdp** [comment]
YES, I have multiple GIFs on the same page.

**Comment by garrettmoon** [comment]
Yeah, sadly this is probably a duplicate of https://github.com/pinterest/PINRemoteImage/issues/203

**Comment by PatrickSCLin** [comment]
any solutions to avoid or reduce this happen ?

**Comment by garrettmoon** [comment]
I've completely rewritten GIF support, hopefully it will be landing soonish: https://github.com/pinterest/PINRemoteImage/pull/411
