### ISSUE TITLE
Add KVO to NSURLSessionTask may cause crash.

### ISSUE THREAD

**Issue by zjmdp** [pinterest/PINRemoteImage#390]
The crashes are here: http://crashes.to/s/45830cf8ec3

I found the same issue discussed about AFNetworking. https://github.com/AFNetworking/AFNetworking/issues/1477

I searched all the code in my project that the category `NSURLSessionTask+Timing` with the observer on the property of `NSURLSessionTask` may cause the crash.

**Comment by garrettmoon** [comment]
@zjmdp well that's just… terrible :( How frequently are you seeing this crash?

**Comment by zjmdp** [comment]
Not very frequent, but it's the most frequently crash for my app.
<img width="1549" alt="wx20170724-103409 2x" src="https://user-images.githubusercontent.com/1818763/28506127-a4745aa0-705b-11e7-9c21-ac13132767d5.png">

**Comment by garrettmoon** [comment]
Ok, it'll probably be a bit before I can look at this, but if you decide to jump in before then, happy to review a pull request!

**Comment by zjmdp** [comment]
I just come back to beta.9 for work round. Maybe I need sometime to learn the code before attempting to fix it.

**Comment by xilin** [comment]
@garrettmoon Same problem happens on my app, the top 1 crash.
After reading on the [AF issue 1477](https://github.com/AFNetworking/AFNetworking/issues/1477) , it seems that in the end they decided to use method swizzle instead of KVO ([PR 2411](https://github.com/AFNetworking/AFNetworking/pull/2411)) to fix it.

**Comment by workhardupc** [comment]
@zjmdp, We use 3.0.0-beta.11 has this problem, Does 3.0.0-beta.9 has this problem?

**Comment by garrettmoon** [comment]
@xilin Thank you for your heroic efforts attempting to fix this! It's really too bad this bug exists. Does anyone have confirmation it still exists in Beta 11?

**Comment by hovox** [comment]
It only happens on iOS 10.x, no iOS 9 or iOS 11.

**Comment by workhardupc** [comment]
@hovox same as us

**Comment by garrettmoon** [comment]
Aweeeeesome! I think I may suggest we wait this one out then 😬

**Comment by luohui8891** [comment]
Got same issue on iOS 11, see detail [here](http://crashes.to/s/fca981831b6)

**Comment by workhardupc** [comment]
@garrettmoon Is there any way to use Texture, but not use PINRemoteImage?

**Comment by garrettmoon** [comment]
@workhardupc yes, I wrote the integration into Texture to be entirely pluggable.

**Comment by garrettmoon** [comment]
Hopefully the PR I put up addresses this. It's a pretty significant change but removes the need for KVO with the limitation that iOS 9 users and below don't get the benefits of knowing time to first byte.

**Comment by luohui8891** [comment]
@garrettmoon which PR? Would you mind to provide the URL?

**Comment by xilin** [comment]
@luohui8891 See [PR#410](https://github.com/pinterest/PINRemoteImage/pull/410)

**Comment by luohui8891** [comment]
@xilin got it, thanks.
