### ISSUE TITLE
tvOS missing in main project "Supported Platforms" setting

### ISSUE THREAD

**Issue by jorystiefel** [pinterest/PINRemoteImage#400]
The PINRemoteImage main project is missing the `tvos` and `tvossimulator` values in the Supported Platforms setting.

If you're using a Git submodule, you cannot use PINRemoteImage with tvOS without adding these parameters, which means you have to fork and cannot pull directly from this repo.

**Comment by garrettmoon** [comment]
Good catch! Would you mind submitting a pull request to address?

**Comment by jorystiefel** [comment]
@garrettmoon Certainly! Give me a few mins.

**Comment by jorystiefel** [comment]
https://github.com/pinterest/PINRemoteImage/pull/401

**Comment by ay8s** [comment]
Thanks for the fix @jorystiefel. Saved me a bunch of time figuring out what was happening with it. Working on my side 👍

**Comment by jorystiefel** [comment]
@ay8s testing it right now, please hold...

**Comment by garrettmoon** [comment]
Going to close this out since I believe #408 addresses.
