### ISSUE TITLE
I have doubts. Self-signed https image how to load

### ISSUE THREAD

**Issue by CHENDONGY** [pinterest/PINRemoteImage#405]
Now i want to use your project, but can not the image be loaded, can there be any good solution

**Comment by garrettmoon** [comment]
@CHENDONGY have you correctly configured for app transport security: https://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

Or perhaps the issue is that the image is served using a self signed certificate. Have you tried setting an authentication challenge block on PINRemoteImageManager (`- (void)setAuthenticationChallenge:(nullable PINRemoteImageManagerAuthenticationChallenge)challengeBlock`)?

**Comment by CHENDONGY** [comment]
I used AsyncDisplayKit in my project, and AsyncDisplayKit relied on your project. I use the certificate is self-signed. Use ASNetworkImageNode to load the network image when loading does not come out
An error occurred `NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)`

I have tried it `PINRemoteImageManager (- (void)setAuthenticationChallenge:(nullable PINRemoteImageManagerAuthenticationChallenge)challengeBlock)`

like this

```
- (AFSecurityPolicy *)customSecurityPolicy {
  
    NSString *cerPath = [[NSBundle mainBundle] pathForResource:@"inpet" ofType:@"cer"];
    
    NSData *cerData = [NSData dataWithContentsOfFile:cerPath];
  
    AFSecurityPolicy *securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];
  
    securityPolicy.allowInvalidCertificates = YES;
  
    securityPolicy.validatesDomainName = NO;
    
    NSSet *cerDataSet = [NSSet setWithArray:@[cerData]];
    
    securityPolicy.pinnedCertificates = cerDataSet;
    
    return securityPolicy;
    
}

PINRemoteImageManager *pin = [PINRemoteImageManager sharedImageManager];
    
    [pin setAuthenticationChallenge:^(NSURLSessionTask * _Nullable task, NSURLAuthenticationChallenge * _Nonnull challenge, PINRemoteImageManagerAuthenticationChallengeCompletionHandler  _Nullable aHandler) {
        
        SecTrustRef serverTrust = [[challenge protectionSpace] serverTrust];
        
        [[self customSecurityPolicy] evaluateServerTrust:serverTrust forDomain:nil];
        
        NSURLCredential *credential = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];
        
        aHandler(NSURLSessionAuthChallengePerformDefaultHandling,credential);
        
        return [[challenge sender] useCredential: credential
                
                      forAuthenticationChallenge: challenge];
        
    }];

```

But still reported the same mistake, so I would like to know what good way?

**Comment by garrettmoon** [comment]
Hmm, I'm not sure, I don't know a lot about SSL validation. Are you able to download the images in Safari? If not, my guess is you won't be able to with PINRemoteImage either because iOS won't allow it :(
