### ISSUE TITLE
deprecation warning when deployment target is ios8

### ISSUE THREAD

**Issue by Sega-Zero** [pinterest/PINRemoteImage#41]
> /Pods/PINRemoteImage/Pod/Classes/PINRemoteImageManager.m:1245:19: 'threadPriority' is deprecated: first deprecated in iOS 8.0

**Comment by garrettmoon** [comment]
There's a runtime check to make sure it only gets called on iOS 7 or below. Maybe we should wrap in a pragma warning suppressor.

**Comment by Sega-Zero** [comment]
Suppressing warnings is not a good way. I think a better solution would be wrapping in 
```objective-c
#if  __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_8_0
//code
#endif
```
so this code will never gets included in ios8+ apps

**Comment by garrettmoon** [comment]
@Sega-Zero Hmm, but what if you want to support iOS 7 & 8? It only compiles one way or the other, thus the need for a runtime check?

**Comment by Sega-Zero** [comment]
If deployment target is lower than ``_IPHONE_8_0``, the code will be included and the deprecation warning will not be shown. That code will not throw an exception, for now it is just a warning, that ``threadPriority`` should no longer be set manually. There is a better way for this in ios8: the new ``qualityOfService`` property.

**Comment by garrettmoon** [comment]
We were already using qualityOfService with a runtime check :) I've submitted a PR that addresses the warning.
