### ISSUE TITLE
Progressive Jpeg Not Working

### ISSUE THREAD

**Issue by davieslee** [pinterest/PINRemoteImage#413]
I've tried the following code to iOS `9.3`, `10.3.1` and `11.0`:

```swift
 imageView.pin_updateWithProgress = true
 imageView.pin_setImage(from: URL(string: "http://www.pooyak.com/p/progjpeg/jpegload.cgi?o=1")!)
```

However, the image doesn't load progressively. Instead it loads after the image is fully downloaded.
Is there anything i done wrongly or it is a bug?

**Comment by garrettmoon** [comment]
@davieslee you mind uploading a sample project which reproduces this?

**Comment by davieslee** [comment]
@garrettmoon here you go
https://github.com/davieslee/pinterest-progressive-jpeg

**Comment by garrettmoon** [comment]
@davieslee took a bit but I tracked it down. Not well documented, but if you don't send a content length header the progressive image system doesn't know how much it's scanned and if it should render a scan or not. So, long story short, send a `Content-Length: 51434` header.

**Comment by garrettmoon** [comment]
Also of note, by default, it only renders a progressive scan after 65% has downloaded. You can change the percentages though.

**Comment by davieslee** [comment]
@garrettmoon how do i set the `Content-Length` with `PINRemoteImage` SDK?

**Comment by garrettmoon** [comment]
@davieslee The server must return a content-length header when it provides the jpeg.

**Comment by alvincrisuy** [comment]
I have the same issue and the server is sending a content-length header

**Comment by garrettmoon** [comment]
@alvincrisuy can you upload a sample project and I'll take a look?

**Comment by alvincrisuy** [comment]
@garrettmoon 

Here's the sample project that I made earlier.
[https://drive.google.com/open?id=0B75vUrnBTEXHYXBSTjQxT2Mtc3M](url)

**Comment by garrettmoon** [comment]
@alvincrisuy the JPEG must also be encoded with progressive support. There's a tool to test if a JPEG is encoded progressively here: http://techslides.com/demos/progressive-test.html

**Comment by alvincrisuy** [comment]
@garrettmoon Thank you I'll test it out and back to you once the images in the server are fixed.

**Comment by alvincrisuy** [comment]
It's working. Thanks @garrettmoon

**Comment by garrettmoon** [comment]
Yup! Glad I could help :)

**Comment by PD006** [comment]
Progressive Jpeg Not Working is not working in my case
