### ISSUE TITLE
tvOS - [UIImageView pin_setImageFromURL:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by TimOliver** [pinterest/PINRemoteImage#418]
Hi folks! I'm loving `PINRemoteImage`, but unfortunately I came across the same problem as issue #181.

Everything works fine and as expected in iOS, but whenever I try and call `[UIImageView pin_setImageFromURL:]` in tvOS, I get the exception: `[UIImageView pin_setImageFromURL:]: unrecognized selector sent to instance`.

![screen shot 2017-10-18 at 1 01 59 am](https://user-images.githubusercontent.com/429119/31678207-fb4c2100-b39f-11e7-88cd-9b7ae6c9efa4.png)

I'm guessing there must be some kind of configuration error occurring that's stopping the category from being properly registered with `UIImageView`.

In the meantime, is there a more 'manual' API I can call to try and mitigate this?

I'm running tvOS 11.1 beta in the Simulator, and using the very latest copy of `PINRemoteImage` via CocoaPods

**Comment by garrettmoon** [comment]
@TimOliver What version is Cocoapods fetching? The latest release or the latest beta (It won't get the beta automatically on newer versions of Cocoapods). Are you sure cell.imageView a subclass of UIImageView? Can you upload a sample project that demonstrates this?

**Comment by TimOliver** [comment]
Hi @garrettmoon! Thanks for the prompt reply! I just double-checked. It's version 2.1.4. And yep! That's a custom `UICollectionView` subclass that I implemented myself. It's definitely a `UIImageView`.

Sure! I'll have a play with it tomorrow to see if I can pull out these problematic views and put them in a separate demo app.

**Comment by TimOliver** [comment]
Aha! I think I found the problem. I tried making a tvOS only demo app and using CocoaPods to import `PINRemoteImage`. I also imported Realm for tvOS to make sure I'd set CocoaPods up right.

The CocoaPods import succeeded, however no source files were imported for `PINRemoteImage`. The folder in Xcode is empty.

<img width="268" alt="screen shot 2017-10-18 at 10 53 17 am" src="https://user-images.githubusercontent.com/429119/31698949-af9ba6a6-b3f2-11e7-8ced-94e36846bd00.png">

I think this would imply something's not configured correctly with the tvOS side of `PINRemoteImage`'s podspec. The files were being imported correctly with my main app project since there was an iOS component as well, however they weren't being linked with the tvOS build target, which would explain why it would cause a runtime error.

Attached is the demo project I made (I didn't even get as far as hooking up the cell) for you to try on your end. Let me know if I'm doing something wrong. :)

Thanks!

[RemoteImageTest.zip](https://github.com/pinterest/PINRemoteImage/files/1393276/RemoteImageTest.zip)

**Comment by garrettmoon** [comment]
Interesting! Thanks for reporting and uploading the sample project @TimOliver.

**Comment by TimOliver** [comment]
Hi @garrettmoon! My pleasure! Thanks for the response!

I've got a bit more to add now. :) I played with the subspecs (as well as the 3.0 version in `master` and came up with a few more notes.

This one doesn't work. No source files come down.

```
platform :tvos, '10.0'

target 'RemoteImageTest' do
  pod 'PINRemoteImage'
end
```

However specifying the tvOS subspecies (ostensibly just the iOS one) actually fixes the problem:

```
platform :tvos, '10.0'

target 'RemoteImageTest' do
  pod 'PINRemoteImage/tvOS'
end
```

I was wondering if this issue might have been changed in the latest podspec in `master`, so I also tried linking straight to the repo:

```
pod 'PINRemoteImage', :git => 'https://github.com/pinterest/PINRemoteImage.git'
```

That seemed to work, but unfortunately, the `FLAnimatedImage` class isn't imported by default, and that caused a linking issue.

However, declaring a subspec again seemed to fix it:

```
pod 'PINRemoteImage/iOS', :git => 'https://github.com/pinterest/PINRemoteImage.git'
```

In any case, I've got it working properly in my project, so I'm happy to close this. :)

**Comment by garrettmoon** [comment]
Glad it's working now for you! Let's leave it open for now in case someone else encounters it. I'll try and take a look when I get some time.

**Comment by garrettmoon** [comment]
I'm pretty sure tvOS is in a better state now, closing!

**Comment by TimOliver** [comment]
Thanks Garrett! Yeah, I got the project to a shippable state at the time and shipped.

If I ever see the issue again, I'll make a new ticket here.

Thanks again for all your hard work! :D
