### ISSUE TITLE
PINMemMapAnimatedImage not in umbrella header

### ISSUE THREAD

**Issue by justin** [pinterest/PINRemoteImage#423]
Is there a reason for `PINMemMapAnimatedImage.h` to not be included in the `PINRemoteImage.h` umbrella header? It's throwing a warning at us over it. Happy to PR it. Just want to verify there's not a specific reason for the current behavior.

Thanks!

**Comment by garrettmoon** [comment]
@justin it's actually being phased out. I left the file in because I may use some of the code to build a hybrid memory mapped / in memory cache system. Would gladly accept a PR to silence the warning though! Thank you!
