### ISSUE TITLE
A typo in source code && mem cache will not be refreshed.

### ISSUE THREAD

**Issue by lastcc** [pinterest/PINRemoteImage#425]
https://github.com/pinterest/PINRemoteImage/blob/0aec6d2bef2a720636044ff7cfa6947f42270ccb/Source/Classes/PINRemoteImageManager.m#L790-L807

https://github.com/pinterest/PINRemoteImage/blob/0aec6d2bef2a720636044ff7cfa6947f42270ccb/Source/Classes/PINRemoteImageManager.m#L799

the option is none because the `&`. i'm in the master branch i think.

    (lldb) po options
    PINRemoteImageManagerDownloadOptionsNone

And this code can't refresh memory cache because `updateMemoryCache` will be `NO`

https://github.com/pinterest/PINRemoteImage/issues/422#issuecomment-340197169

**Comment by lastcc** [comment]
And I have a question:

Although a processor block is provided, the original image that was  not processed by the processor is also cached in to disk.

https://github.com/pinterest/PINRemoteImage/blob/0aec6d2bef2a720636044ff7cfa6947f42270ccb/Source/Classes/PINRemoteImageManager.m#L776

is this behavior intended?

**Comment by garrettmoon** [comment]
@lastcc I'm not sure I understand. The & is doing a bitwise and operation here.

With regards to your question, yes it's intended that the original image is cached as well. Having the option to not cache it could be beneficial though.

**Comment by lastcc** [comment]
@garrettmoon Hi. 

Yes I understand you are doing bitwise op here. But what I don't get it is, the result of this bitwise op will be `.None`

so why don't you just `options = PINRemoteImageManagerDownloadOptionsNone`
instead you `options = PINRemoteImageManagerDownloadOptionsSkipDecode & PINRemoteImageManagerDownloadOptionsSkipEarlyCheck`

**Comment by garrettmoon** [comment]
Just opened a PR, thanks so much for taking the time to make me see my mistake!

**Comment by lastcc** [comment]
typo in objc is nothing unusual, thanks for fixing it!
I'm closing this.
