### ISSUE TITLE
Support for custom HTTP request headers

### ISSUE THREAD

**Issue by JaredCrawford** [pinterest/PINRemoteImage#43]
If an application is required to set additional HTTP headers on image requests, I don't see a way to either supply an ```NSURLRequest``` for each image request (with the appropriate headers already set) or to add the headers globally to all requests.

As one solution, ```PINRemoteImageManager``` uses ```[NSURLSessionConfiguration defaultConfiguration]``` in its initialization. If ```PINRemoteImageManager``` offered a way to customize that configuration, that could be configured to add the additional headers to all image requests made through that (shared) instance of ```PINRemoteImageManager```.

**Comment by garrettmoon** [comment]
Good idea! Would be happy to entertain any pull requests that implement this.
