### ISSUE TITLE
Infer analyse tool - potential bugs & memory leaks

### ISSUE THREAD

**Issue by Kaspik** [pinterest/PINRemoteImage#431]
Hey guys, thank you for this library.

I did run Infer ( http://fbinfer.com ) on our project and it found some issue with PINRemoteImage. Here is screenshot with some info if it helps:

```
Pods/PINRemoteImage/Source/Classes/Categories/PINImage+ScaledImage.m:18: error: DEAD_STORE
  The value written to &__assert_file__ is never used.
  16.   #if PIN_TARGET_IOS
  17.       
  18. >     NSCAssert(image.CGImage != NULL, @"CGImage should not be NULL");
  19.       
  20.       CGFloat scale = 1.0;

Pods/PINRemoteImage/Source/Classes/Categories/PINImage+ScaledImage.m:18: error: DEAD_STORE
  The value written to &__assert_fn__ is never used.
  16.   #if PIN_TARGET_IOS
  17.       
  18. >     NSCAssert(image.CGImage != NULL, @"CGImage should not be NULL");
  19.       
  20.       CGFloat scale = 1.0;
```

![screen shot 2017-11-29 at 14 09 34](https://user-images.githubusercontent.com/7204168/33401682-f537f5ce-d50e-11e7-80be-5de359764768.png)

Are you aware of these? If not, do you think it's something worth fixing / are you able to fix it? Or is Infer totally wrong? :)

Thank you for the response!

**Comment by garrettmoon** [comment]
I think these may be in the actual macros themselves? I'm guessing this isn't actually an issue in production since most everyone (and by default) compiles out asserts.

Thanks for taking the time to run infer on the project!
