### ISSUE TITLE
Download taking too much time to finish with placeholder

### ISSUE THREAD

**Issue by brurend** [pinterest/PINRemoteImage#436]
If I set a placeholder image to pin_setImageFromURL the download sometimes take considerably longer than the rest, every 20~ images it takes up to 10 times longer to download.

Also if I don't set a placeholder and I scroll through a lot of images (500+) it also starts to take a while to download the images.

**Comment by garrettmoon** [comment]
@brurend would you mind uploading a sample project that demonstrates this?

**Comment by brurend** [comment]
@garrettmoon I will try to upload a sample later today.

Also, I tried using ASNetworkNode instead of UIImageView to see if it would make any difference and the problem persisted. And I'm using IGListKit, not sure if it could have anything to do with it.

**Comment by brurend** [comment]
I couldn't reproduce the issue in a sample project so I did some more tests and I believe now that my issue isn't PINRemoteImage fault.

**Comment by garrettmoon** [comment]
@brurend glad you figured it out! I'm not sure why adding a placeholder would make the download take longer unless the placeholder is big and it's taking a long time to decode…

**Comment by brurend** [comment]
@garrettmoon Actually after some more research I believe the problem might be related to signed URLs, although it still might not be related to PINRemoteImage and maybe to NSURLSession. Have you ever experience or seen signed URLs taking considerably longer to fetch? It ranges from 1 second to up to 15 seconds sometimes.

**Comment by garrettmoon** [comment]
'signed URLs'? Do you mean HTTPs?

**Comment by brurend** [comment]
I mean AWS signed URLs. URLs with expire time and some other information.

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html

**Comment by garrettmoon** [comment]
Ah, don't know much about those. But since it's related to a CDN, the delay probably has to do with the image not being cached in the CDN? That'd be my first guess.

**Comment by brurend** [comment]
Yeah, it was indeed some configuration that wasn't right in the CDN, nothing related to PINRemoteImage at all. Thanks for helping out and sorry for opening an issue that in the end wasn't related to the repository.
