### ISSUE TITLE
When is 3.0 going to be officially released?

### ISSUE THREAD

**Issue by chuganzy** [pinterest/PINRemoteImage#438]
It has been a while since 3.0 beta was released but it is still in beta..
I want to know the timeline for the official release.

**Comment by garrettmoon** [comment]
He @chuganzy I really want to get 3.0 out the door, but we need a bit more time and we can't promise a date :(

**Comment by chuganzy** [comment]
Got it. Is it due to some issues remaining or internal stuffs inside Pinterest?

**Comment by garrettmoon** [comment]
@chuganzy mainly that someone needs to take the time to make sure the release is in good shape :) I.e. make sure Swift support is working correctly, Carthage support, Readme and documentation are up to date, that type of thing.

**Comment by chuganzy** [comment]
Got it. Thank you! Closing.
