### ISSUE TITLE
CFNetwork problem 

### ISSUE THREAD

**Issue by picturehit** [pinterest/PINRemoteImage#445]
Hello everybody, 

I'm using PINRemoteImage to download a lot of pictures in my app. 
My top bug issues in Fabric are 
Crashed: com.apple.CFNetwork.Connection
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
and 
Crashed: com.apple.CFNetwork.LoaderQ
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

I guess it's a problem with the image url download, right ?
Anyone already got this problem ? 
Am i missing something ? 
Is it a background download task problem ?
I notice that it only occurs on iOS 11.2.* 

Thank you very much !!! 

Complete log example : 

Crashed: com.apple.CFNetwork.LoaderQ
0  CFNetwork                      0x182ee3e6c _CFURLRequestCopyContentDispositionEncodingFallbackArray + 48
1  CFNetwork                      0x182fa239c HTTPProtocol::updateForHeader(__CFHTTPMessage*) + 260
2  CFNetwork                      0x182fa239c HTTPProtocol::updateForHeader(__CFHTTPMessage*) + 260
3  CFNetwork                      0x182fa0c70 HTTPProtocol::performHeaderReadPostProcessing(__CFHTTPMessage*, unsigned char) + 224
4  CFNetwork                      0x182f9c984 HTTPProtocol::performHeaderRead(__CFHTTPMessage*) + 1376
5  CFNetwork                      0x182f9c310 HTTPProtocol::handleStreamEvent(__CFHTTPMessage*, dispatch_data_s*, CFStreamError const*) + 188
6  CFNetwork                      0x182fc7350 HTTP2Stream::_onschedulingset_notifyDataAvailable(dispatch_data_s*) + 76
7  CFNetwork                      0x182fc72e4 invocation function for block in HTTP2Stream::_onqueue_notifyDataAvailable() + 28
8  CFNetwork                      0x1830b92e4 invocation function for block in QCoreSchedulingSet::performAsync(void () block_pointer) const + 52
9  libdispatch.dylib              0x182282a54 _dispatch_call_block_and_release + 24
10 libdispatch.dylib              0x182282a14 _dispatch_client_callout + 16
11 libdispatch.dylib              0x18228c96c _dispatch_queue_serial_drain$VARIANT$mp + 528
12 libdispatch.dylib              0x18228d2fc _dispatch_queue_invoke$VARIANT$mp + 340
13 libdispatch.dylib              0x18228c824 _dispatch_queue_serial_drain$VARIANT$mp + 200
14 libdispatch.dylib              0x18228d2fc _dispatch_queue_invoke$VARIANT$mp + 340
15 libdispatch.dylib              0x18228dd20 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 404
16 libdispatch.dylib              0x18229603c _dispatch_workloop_worker_thread$VARIANT$mp + 644
17 libsystem_pthread.dylib        0x18252af1c _pthread_wqthread + 932
18 libsystem_pthread.dylib        0x18252ab6c start_wqthread + 4

**Comment by garrettmoon** [comment]
This doesn't show PINRemoteImage anywhere in the stack trace so I'm going to close this. It's likely a bug in iOS and you should probably file a radar?
