### ISSUE TITLE
Progressive image loading not works in sample project

### ISSUE THREAD

**Issue by MikuZZZ** [pinterest/PINRemoteImage#447]
I'm trying to use PINRemoteImage for progressive jpg loading with iOS and Swift. I use the sample project in Swift-Example folder and set the network condition to 3G, but the progressive tab shows me the complete image after 5 second without progressive loading. 

I'm using iOS 11.3. Thanks

**Comment by garrettmoon** [comment]
@MikuZZZ let me know if it's still not working for you on master.
