### ISSUE TITLE
Found a race condition

### ISSUE THREAD

**Issue by tinder-quemarsekalantary** [pinterest/PINRemoteImage#448]
We have the thread sanitizer turned on and have been finding this sort of behavior:

![image](https://user-images.githubusercontent.com/32074248/38634455-6271fed4-3d77-11e8-9296-371f5b0fbdaa.png)

![image](https://user-images.githubusercontent.com/32074248/38634528-960e9284-3d77-11e8-9535-b3ece9dc5f0c.png)

**Comment by garrettmoon** [comment]
@tinder-quemarsekalantary Did it turn out not to be related to PINRemoteImage? Would love to figure this out if it's PINRemoteImage's fault.

**Comment by tinder-quemarsekalantary** [comment]
yeah it turns out we had a personal fork of the project so we'd need to check and see if this is in the up to date version

**Comment by garrettmoon** [comment]
Let us know!
