### ISSUE TITLE
Potential bug with PINRemoteImageBasicCache causing decoding of images on the main thread

### ISSUE THREAD

**Issue by kgaidis** [pinterest/PINRemoteImage#451]
I think there's a bug where images are decoded on the main thread when they are first downloaded IF `PINRemoteImageBasicCache` is used (AKA no PINCache).

When an image is downloaded, or pulled from cache, everything trickles down into `PINRemoteImageManager` method:
```
- (BOOL)materializeAndCacheObject:(id)object
                      cacheInDisk:(NSData *)diskData
                   additionalCost:(NSUInteger)additionalCost
                              url:(NSURL *)url
                              key:(NSString *)key
                          options:(PINRemoteImageManagerDownloadOptions)options
                         outImage:(PINImage **)outImage
                        outAltRep:(id *)outAlternateRepresentation
```

Also, when an image is FIRST downloaded, `object` is NSData, and `cacheInDisk` is also NSData.

The `materializeAndCacheObject:` keeps going and eventually saves `PINRemoteImageMemoryContainer` to memory:
```
if (updateMemoryCache) {
    [container.lock lockWithBlock:^{
        NSUInteger cacheCost = additionalCost;
        cacheCost += [container.data length];
        CGImageRef imageRef = container.image.CGImage;
        NSAssert(container.image == nil || imageRef != NULL, @"We only cache a decompressed image if we decompressed it ourselves. In that case, it should be backed by a CGImageRef.");
        if (imageRef) {
            cacheCost += CGImageGetHeight(imageRef) * CGImageGetBytesPerRow(imageRef);
        }
        [self.cache setObjectInMemory:container forKey:key withCost:cacheCost];
    }];
}
```

`PINRemoteImageBasicCache` implementation for `setObjectInMemory:`:
```
-(void)setObjectInMemory:(id)object forKey:(NSString *)key withCost:(NSUInteger)cost
{
    [self.cache setObject:object forKey:key cost:cost];
}
```

That all is great. 

Then the `materializeAndCacheObject:` keeps going and eventually saves `cacheInDisk` to "disk:"
```
if (diskData) {
    [self.cache setObjectOnDisk:diskData forKey:key];
}
```

`PINRemoteImageBasicCache` implementation for `setObjectOnDisk:`:
```
-(void)setObjectOnDisk:(id)object forKey:(NSString *)key
{
    [self.cache setObject:object forKey:key];
}
```

At that point, the previously saved `PINRemoteImageMemoryContainer` gets overriden by `NSData`.

THE NEXT time the image is fetched "from memory" because of the "early return functionality" the `object` is NOT `PINRemoteImageMemoryContainer`, it's NSData. This causes the image to be decoded on the main thread. However, `cacheInDisk` is NIL, so the `setObjectOnDisk` is not called a second time, and there is no override of `PINRemoteImageMemoryContainer`. So after the first decode on the main thread, it works as expected.

Hopefully its not too confusing. I'm not sure why `PINRemoteImageBasicCache ` is implemented the way it is so I didn't open a PR (also, I could be wrong about my analysis 😁 ). 

Thank you for the great library!

**Comment by garrettmoon** [comment]
That definitely looks like a mistake! I'd guess setObjectOnDisk should be a no-op. Feel free to open a pull request!

**Comment by kgaidis** [comment]
@garrettmoon 

The one potential issue I see with making `setObjectOnDisk` no-op is:

```
- (void)storeResumeData:(PINResume *)resume forURL:(NSURL *)URL
{
    NSString *resumeKey = [self resumeCacheKeyForURL:URL];
    [self.cache setObjectOnDisk:resume forKey:resumeKey];
}
```

it uses `setObjectOnDisk` (so resume functionality wouldn't work with PINRemoteImageBasicCache?)

which maybe is different from the documentation? If I understand correctly, documentation says it would be stored in memory:
```
/**
 @param storeResumeData if YES and the server indicates it supports resuming downloads, downloaded data will be stored in the memory
 cache and used to resume the download if the same URL is attempted to be downloaded in the future.
 */
- (void)cancelTaskWithUUID:(nonnull NSUUID *)UUID storeResumeData:(BOOL)storeResumeData;
```

**Comment by garrettmoon** [comment]
😬 we should update the documentation to say it will be stored on disk and that the basic cache does not support disk caching.

**Comment by garrettmoon** [comment]
Thanks for your help on this!

**Comment by kgaidis** [comment]
PR opened: 
- https://github.com/pinterest/PINRemoteImage/pull/457

**Comment by garrettmoon** [comment]
Going to close this now that the PR is merged, thanks again for putting up a fix!

**Comment by kgaidis** [comment]
@garrettmoon thank _you_ for the library! :)
