### ISSUE TITLE
JPEG not loading progressively

### ISSUE THREAD

**Issue by iamavikbagh** [pinterest/PINRemoteImage#452]
Could you please take a look at this url http://d5hqmnax9xmmh.cloudfront.net/2183ff66dc669f8ae7b509ec6bc75f84.jpg and tell me why it is not loading progressively? I have followed your documentation, and yet the jpg shows only once it is fully loaded.

I have tried creating progressive jpegs on the server using PHP's imageinterlace() and then using imagick too. Neither loaded progressively for me. Thereafter I created progressive jpeg directly from my UIImage using ImageIO in the app, before I uploaded it. Even then, it did not load progressively when it came to displaying it using PINRemoteImage.

I have checked the images generated via each of the above mentioned methods, using the tool at http://techslides.com/demos/progressive-test.html
All the images turned out to be progressive.

On the other hand, images like this https://tobias.is/content/1-blogging/7-even-faster-images-using-http2-and-progressive-jpegs/01-engage-enrage-encourage_compressed.jpg loads progressively (as expected), which makes me wonder if there's something wrong with the images that I am generating.

Could you point me in the right direction? Really confused right now.

**Comment by garrettmoon** [comment]
@iamavikbagh I'm guessing it's because the dimensions exceed the default maximum progressive render size which is 1024 x 1024. You can change this by calling `setProgressiveRendersMaxProgressiveRenderSize:completion:`

Lemme know if that's what it was!

**Comment by garrettmoon** [comment]
(Also be careful of crashes when rendering lots of very large images all at once!)

**Comment by iamavikbagh** [comment]
That's what it was!

I consider this issue solved now, thanks for your help.

**Comment by oferRounds** [comment]
Hi @garrettmoon 

Just wondered: what’s the rational behind this limitation? Is it because progressively downloading/presenting large images taking more resources then non-progressive (i.e., the crashes you mentioned)?
