### ISSUE TITLE
Bug initFileURLWithPath PINDiskCache

### ISSUE THREAD

**Issue by picturehit** [pinterest/PINRemoteImage#455]
Hello everybody, 

I saw a new bug, maybe you already seen it.

Fatal Exception: NSInvalidArgumentException
*** -[NSURL initFileURLWithPath:isDirectory:]: nil string parameter

line 229 in the file PINDiskCache.h 
        sharedTrashURL = [[[NSURL alloc] initFileURLWithPath:NSTemporaryDirectory()] URLByAppendingPathComponent:PINDiskCachePrefix isDirectory:YES];

Any idea ? 

thank you !

**Comment by garrettmoon** [comment]
@picturehit That would suggest NSTemporaryDirectory() is returning nil. Not sure why that would ever happen! Can you upload a sample project?

**Comment by garrettmoon** [comment]
Closing this out since I haven't heard back.
