### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by StarStartLee** [pinterest/PINRemoteImage#463]
There are something wrong with  the podfile  in the example.Could you update it?  Thank you.

**Comment by garrettmoon** [comment]
@StarStartLee I was able to get the example to work, here's what I did:
- `git checkout master`
- `cd Examples/Example`
- `pod update`
- `open PINRemoteImage.xcworkspace`
- Ran the build on an iPhone 8

The above worked for me, if you're having trouble can you tell me what you did?

**Comment by garrettmoon** [comment]
I'm going to close this out for now, I'll re-open if you provide more info.

**Comment by StarStartLee** [comment]
I follow these steps you did ,but terminal throw out these  errer messages:(pod version 1.5.3)
Fetching podspec for `PINRemoteImage` from `../../`
[!] CocoaPods could not find compatible versions for pod "PINCache":
  In snapshot (Podfile.lock):
    PINCache (= 3.0.1-beta.3)

  In Podfile:
    PINRemoteImage/PINCache (from `../../`) was resolved to 3.0.0-beta.13, which depends on
      PINCache (= 3.0.1-beta.6)

Due to the previous naïve CocoaPods resolver, you were using a pre-release version of `PINCache`, without explicitly asking for a pre-release version, which now leads to a conflict. Please decide to either use that pre-release version by adding the version requirement to your Podfile (e.g. `pod 'PINCache', '= 3.0.1-beta.3'`) or revert to a stable version by running `pod update PINCache`.

[!] `xcodeproj` was renamed to `project`. Please update your Podfile accordingly.

[!] Automatically assigning platform `ios` with version `7.1` on target `PINRemoteImage` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
