### ISSUE TITLE
[PINOperationGroup initWithOperationQueue:] memory leak

### ISSUE THREAD

**Issue by alvinyu2003** [pinterest/PINRemoteImage#464]
Has anyone encountered a memory leak for `3.0.0-beta.13` in `[PINOperationGroup initWithOperationQueue:]`? Also, when will 3.0 be released?

**Comment by garrettmoon** [comment]
@alvinyu2003 do you mind putting up an instruments trace with the leak?

**Comment by garrettmoon** [comment]
Going to close this since we can't really investigate without more details.
