### ISSUE TITLE
Setting diskCache.byteLimit does not work

### ISSUE THREAD

**Issue by romansorochak** [pinterest/PINRemoteImage#476]
Hi 

I tried to set maximum bytes that PINCache can use from disk.
PINRemoteImageManager.shared().pinCache?.diskCache.byteLimit = 50 * 1024 * 1024 // ~50 MB

But when I tried to reach this number I saw that the maximum space it took was just 20 MB. 
Then it started trimming previously cached images.

some test code to see the issue:
            
            PINRemoteImageManager.shared().pinCache?.diskCache.byteLimit = 50 * 1024 * 1024
            
            if let bytes = PINRemoteImageManager.shared().pinCache?.diskCache.byteLimit {
                let KBs = Double(bytes) / 1024
                let MBs = KBs / 1024
                print("PINRemoteImageManager diskCache.byteLimit: \(MBs))")
            }

            if let bytes = PINRemoteImageManager.shared().pinCache?.diskByteCount {
                let KBs = Double(bytes) / 1024
                let MBs = KBs / 1024
                print("PINRemoteImageManager MB used: \(MBs)")
            }

I am using PINRemoteImage as part of Texture framework.

Can anyone help please ?

Thanks in advance.

**Comment by romansorochak** [comment]
@wiseoldduck 
the code provided above goes one after another. There nothing happens between printing 'byteLimit' and 'diskByteCount'.

**Comment by wiseoldduck** [comment]
Oh, maybe I am missing something but I would not expect the diskByteCount to go up until you actually downloaded & cached some images.

**Comment by nguyenhuy** [comment]
This might be because `ASPINRemoteImageDownloader` has its own `PINRemoteImageManager` with a byte limit of 20MB ([here](https://github.com/TextureGroup/Texture/blob/master/Source/Details/ASPINRemoteImageDownloader.m#L90)).

**Comment by garrettmoon** [comment]
@romansorochak I'm going to close this for now because I think @nguyenhuy pointed out the issue. Please let me know if you think this is still something we need to keep open!

**Comment by romansorochak** [comment]
@garrettmoon Sorry for long response.
@nguyenhuy explained why it happens but that does not resolve my issue.
I still cannot increase diskCache.byteLimit to be more than 50.
So can you please reopen the issue ?

**Comment by garrettmoon** [comment]
Sorry, missed this :(

**Comment by garrettmoon** [comment]
Closing this for now, please reply if you're still having issues.

**Comment by trungnguyen1791** [comment]
> Closing this for now, please reply if you're still having issues.

I think I'm facing the same issue as @romansorochak.
For example, I tried to assign a bigger byteLimit value like 1000MB, then download some images. Then the next time running app, the Initialization of Diskcache will take 50MB as default and of course trim the cache by ```initializeDiskProperties``` after that. 

IMO, i think its better if we can persist the configured byteLimit value to UserDefault or somewhere else, then be able to load it in Initialization step. 

What do you think about that @garrettmoon ?
