### ISSUE TITLE
Check whether image is downloaded completed before pin_setImageFromURL

### ISSUE THREAD

**Issue by eJamesLin** [pinterest/PINRemoteImage#48]
Is there a way to check a given url image is loaded before actually download it using "pin_setImageFromURL"?
The usage model is to load thumbnail image as placeholder, but if actual image is downloaded before and is already in cache, use actual image directly.
Thank you .

**Comment by garrettmoon** [comment]
Hi @eJamesLin the library handles that all automatically! It will pull the image from the cache if it exists when you call pin_setImageFromURL. There's also a pin_setImageFromURL placeholder: method.

**Comment by garrettmoon** [comment]
If you need to directly check if the image is in the cache, you can check the cache directly (the code below may not compile, it's an approximation from the top of my head):

```
[[[PINRemoteImageManager sharedManager] cache] objectForKey:[[PINRemoteImageManager sharedManager cacheKeyForURL:[NSURL urlWithString:@"http://someimageurl.com/image.jpeg"] processor:nil]
```

**Comment by eJamesLin** [comment]
Thank you @garrettmoon !
