### ISSUE TITLE
What is the best way to erase cached images with pin_setImage?

### ISSUE THREAD

**Issue by akiporoyopida** [pinterest/PINRemoteImage#483]
Upload image process
view.imageview.pin_setImage(from: URL(string: u)!, processorKey: "rounded")  { (result, unsafePointer) -> UIImage? in
.
.

When I want to delete the cache, I use this process
let u= uploaded url
PINRemoteImageManager.shared().cache.removeObject(forKey: u)
let u2=PINRemoteImageManager.shared().cacheKey(for: URL(string:u)!, processorKey: "rounded")
PINRemoteImageManager.shared().cache.removeObject(forKey: u2)

Reasons to erase the cache twice
Because when using pin_setImage two images are cached.

please tell me your good advices.
Thanks

**Comment by garrettmoon** [comment]
@akiporoyopida I think you're doing this in the most efficient way – we don't have a nice way to remove processed images.

The only modification I would suggest for correctness is:
```
let url = uploaded url
key = PINRemoteImageManager.shared().cacheKey(for: URL(string:url)!, processorKey: nil)
PINRemoteImageManager.shared().cache.removeObject(forKey: key)
let key2=PINRemoteImageManager.shared().cacheKey(for: URL(string:u)!, processorKey: "rounded")
PINRemoteImageManager.shared().cache.removeObject(forKey: key2)
```

Hope that helps!

If you're doing this a lot you may want to make a category method on PINRemoteImageManager to do it for you?

**Comment by akiporoyopida** [comment]
Thank you!
