### ISSUE TITLE
I want to use a cache when I am offline

### ISSUE THREAD

**Issue by soushu** [pinterest/PINRemoteImage#484]
Hello.
When I retrieve images from the server, I get it normally if it is online, and when I am offline, I will try to display it if there is a cache, is it possible?

**Comment by MarcSteven** [comment]
https://github.com/pinterest/PINRemoteImage/blob/master/Source/Classes/PINCache/PINCache%2BPINRemoteImageCaching.m This is useful @soushu Come on

**Comment by garrettmoon** [comment]
Going to close this for now, PINRemoteImage supports cached images regardless of if the device is online or off.
