### ISSUE TITLE
The data received does not correctly match the corresponding PINRemoteImageDownloadTask

### ISSUE THREAD

**Issue by HXHinsHuang** [pinterest/PINRemoteImage#489]
### release 3.0.0-beta.7
>Due to my project, I cannot use the latest release to reproduce this problem. But I look at the latest source code does not seem to find a solution to this problem, you may have fixed.

Image data is received piece by piece while the image is being downloaded. In the process of image data download, I quickly back and forth scroll the view, the current download task will be cancelled, PINRemoteImageDownloadTask will be removed from the tasks, and then start a new task. This looks fine,  but the problem occurs when the URL of the new task is the same as the URL of the cancelled task.
Due to image data is returned piece by piece, it is possible that the server returning a piece of data. At this time, the task of this URL has been cancelled, and the PINRemoteImageDownloadTask of corresponding URL(as key) in tasks will be removed. And then start the download task of same URL, the tasks will store the PINRemoteImageDownloadTask of corresponding URL(as key) again. Now, the data of cancelled task was received, PINURLSessionManagerDelegate method according to PINRemoteImageCacheKey find the cacheKey(URL) in NSURLProtocol, and according to cacheKey find the PINRemoteImageDownloadTask in the tasks. This PINRemoteImageDownloadTask should belong to the new task, and the received data should belong to the cancelled task, the received data data will be added to the PINRemoteImageDownloadTask. This will be stored with the correct data for the new task, resulting in an image decoding exception.

```objc
// PINRemoteImageManager.m
- (void)didReceiveData:(NSData *)data forTask:(NSURLSessionDataTask *)dataTask
{
    [self lock];
        NSString *cacheKey = [NSURLProtocol propertyForKey:PINRemoteImageCacheKey inRequest:dataTask.originalRequest];
        PINRemoteImageDownloadTask *task = [self.tasks objectForKey:cacheKey];
    
        /********************************** Here is the NSAssert I added ***************************************************/
        NSAssert(dataTask.taskIdentifier == task.urlSessionTaskOperation.dataTask.taskIdentifier, @"The received data belong to cancelled task.")
        /*******************************************************************************************************************/
    
        if (task.progressImage == nil) {
            task.progressImage = [[PINProgressiveImage alloc] init];
            task.progressImage.startTime = task.sessionTaskStartTime;
            task.progressImage.estimatedRemainingTimeThreshold = self.estimatedRemainingTimeThreshold;
            if (self.progressThresholds) {
                task.progressImage.progressThresholds = self.progressThresholds;
            }
        }

        PINProgressiveImage *progressiveImage = task.progressImage;
        BOOL hasProgressBlocks = task.hasProgressBlocks;
        BOOL shouldBlur = self.shouldBlurProgressive;
        CGSize maxProgressiveRenderSize = self.maxProgressiveRenderSize;
    
        [task callProgressDownloadWithQueue:self.callbackQueue completedBytes:dataTask.countOfBytesReceived totalBytes:dataTask.countOfBytesExpectedToReceive];
    [self unlock];
    
    [progressiveImage updateProgressiveImageWithData:data expectedNumberOfBytes:[dataTask countOfBytesExpectedToReceive]];

    if (hasProgressBlocks && [NSOperation instancesRespondToSelector:@selector(qualityOfService)]) {
        __weak typeof(self) weakSelf = self;
        [_concurrentOperationQueue pin_addOperationWithQueuePriority:PINRemoteImageManagerPriorityLow block:^{
            typeof(self) strongSelf = weakSelf;
            CGFloat renderedImageQuality = 1.0;
            PINImage *progressImage = [progressiveImage currentImageBlurred:shouldBlur maxProgressiveRenderSize:maxProgressiveRenderSize renderedImageQuality:&renderedImageQuality];
            if (progressImage) {
                [strongSelf lock];
                    PINRemoteImageDownloadTask *task = strongSelf.tasks[cacheKey];
                    [task callProgressImageWithQueue:strongSelf.callbackQueue withImage:progressImage renderedImageQuality:renderedImageQuality];
                [strongSelf unlock];
            }
        }];
    }
}
```

I added an assertion, and then when I scroll back and forth quickly the view has a probability that it will hit.

**Comment by garrettmoon** [comment]
I think you may have caught something here! Would you mind uploading a sample project?

**Comment by garrettmoon** [comment]
@HXHinsHuang would you mind testing the fix here? https://github.com/pinterest/PINRemoteImage/pull/514
