### ISSUE TITLE
React Native support?

### ISSUE THREAD

**Issue by oferRounds** [pinterest/PINRemoteImage#525]
Hi, 
I really like PINRemoteImage, and I’m now using React Native. I read back then on your that Pinterest have started to use some React Native. Do you plan to export the library also to React Native?

**Comment by garrettmoon** [comment]
Hi @oferRounds no, we don't have any plans to open source and maintain that publicly at this time.

**Comment by oferRounds** [comment]
Hi @garrettmoon got you, thank you for the answer :)
