### ISSUE TITLE
Error with overloaded methods

### ISSUE THREAD

**Issue by mdamicoml** [pinterest/PINRemoteImage#532]
I tried to update to '3.0.0-beta.10' from 'release 2.1.4' but it crashed with error:

`Conflicting parameter types in declaration of 'setObjectAsync:forKey:completion:': 'id  _Nonnull __strong' vs 'id<NSCoding>  _Nonnull __strong'`

The problem it's about overloading methods like "setObjectAsync", "setObjectAsync", "setObjectAsync" that are in the "PINCaching" interface.

**Comment by garrettmoon** [comment]
@mdamicoml I'm not sure I understand, do you mind posting a sample project which reproduces?

**Comment by garrettmoon** [comment]
Going to close this since there hasn't been a reply.
