### ISSUE TITLE
crash on  [FLAnimatedImage addFrameIndexesToCache:]

### ISSUE THREAD

**Issue by dairuiquan** [pinterest/PINRemoteImage#535]
My app use this library . First, I think this Library is beautiful.  I find a crash with bulgy that is a crash    collect tool.  I show crash stack with bugly catch.    

ibsystem_platform.dylib
_platform_memmove + 112
1	ImageIO
GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 796
2	ImageIO
GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 796
3	ImageIO
GIFReadPlugin::CopyImageBlockSetProc(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 124
4	ImageIO
IIOImageProviderInfo::copyImageBlockSetWithOptions(CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 496
5	ImageIO
IIOImageProviderInfo::CopyImageBlockSetWithOptions(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 356
6	CoreGraphics
_img_blocks_create + 260
7	CoreGraphics
_img_data_lock + 1896
8	CoreGraphics
CGSImageDataLock + 152
9	CoreGraphics
_ripc_AcquireImage + 712
10	CoreGraphics
_ripc_DrawImage + 676
11	CoreGraphics
CGContextDrawImageWithOptions + 636
12	LoanPay
+[FLAnimatedImage predrawnImageFromImage:] (FLAnimatedImage.m:707)
13	LoanPay
-[FLAnimatedImage imageAtIndex:] (FLAnimatedImage.m:0)
14	LoanPay
__42-[FLAnimatedImage addFrameIndexesToCache:]_block_invoke_3 (FLAnimatedImage.m:0)
15	Foundation
___NSIndexSetEnumerate + 824
16	LoanPay
__42-[FLAnimatedImage addFrameIndexesToCache:]_block_invoke_2 (FLAnimatedImage.m:481)
17	libdispatch.dylib
__dispatch_call_block_and_release + 24
18	libdispatch.dylib
__dispatch_client_callout + 16
19	libdispatch.dylib
__dispatch_queue_serial_drain + 928

**Comment by garrettmoon** [comment]
@dairuiquan this is a crash occurring in [FLAnimatedImage](https://www.github.com/Flipboard/FLAnimatedImage), not PINRemoteImage
