### ISSUE TITLE
Publish PINRemoteImage 3.0.0

### ISSUE THREAD

**Issue by ZachOrr** [pinterest/PINRemoteImage#538]
Hey y'all - would it be possible to publish the new [PINRemoteImage 3.0.0 release](https://github.com/pinterest/PINRemoteImage/releases/tag/3.0.0) to [Cocoapods](https://cocoapods.org/pods/PINRemoteImage)?

Thanks!

**Comment by iwheelbuy** [comment]
Yeah... why not publishing?

**Comment by garrettmoon** [comment]
Published!
