### ISSUE TITLE
Swift example

### ISSUE THREAD

**Issue by babatripathy** [pinterest/PINRemoteImage#55]
Do you have any example with Swift?

**Comment by garrettmoon** [comment]
Check out this article: https://littlebitesofcocoa.com/51

**Comment by dodikk** [comment]
The swift example from article does not compile for me with `3.0.0-beta3` version


I've tried both : 
* `setImageFromURL(imageURL)` 
* `pin_setImage(from: imageUrl)`

**Comment by dodikk** [comment]
https://github.com/pinterest/PINRemoteImage/issues/327
