### ISSUE TITLE
Can you please bump the tag of the latest master version ?

### ISSUE THREAD

**Issue by petarbelokonski** [pinterest/PINRemoteImage#565]
@garrettmoon FYI :)

**Comment by JohnnyTseng** [comment]
+1 needed 3.0.1 enable to build on Xcode 12

**Comment by noremac** [comment]
With iOS 14 coming out tomorrow, it'd be amazing if this happened soon.

**Comment by bboyle18** [comment]
@garrettmoon 👋  Any idea when https://github.com/pinterest/PINRemoteImage/pull/567 will be merged? 
Thanks!

**Comment by garrettmoon** [comment]
Done!

**Comment by bboyle18** [comment]
Thanks @garrettmoon 🙇
