### ISSUE TITLE
Xcode 12 doesn't compile it successfully

### ISSUE THREAD

**Issue by gaikwadamit19** [pinterest/PINRemoteImage#566]
There are 4 compilation issues in PINRemoteImage pod for PINCache dependancy with 3.0.1, 
Updated the pods in app by deleting podfile.lock and again installing pod and found 4 compilation issues.
Looks like this this not compatible with Xcode 12.

**Comment by McsimumVelocity** [comment]
Hi! Yes, I'm seeing the same as @gaikwadamit19. Encountering a number of errors all similar to the following on Xcode 12 Beta 6. 

`Incompatible block pointer types sending 'PINMemoryCacheObjectBlock  _Nullable __strong' (aka 'void (^__strong)(PINMemoryCache * _Nonnull __strong, NSString * _Nonnull __strong, id  _Nullable __strong)') to parameter of type 'PINCacheObjectBlock _Nonnull' (aka 'void (^)(id<PINCaching>  _Nonnull __strong, NSString * _Nonnull __strong, id  _Nullable __strong)')`

**Comment by sagesse-cn** [comment]
add the flags into bulid config to disable check
```
-Xclang -fcompatibility-qualified-id-block-type-checking
```

**Comment by gaikwadamit19** [comment]
My project using pod for PINRemoteImage. In .podsec file though PINCache dependancy updated to "3.0.1" from "3.0.1-beta.8", somehow PINRemoteImage is still referring to "3.0.1-beta.8". 
Not sure from where it is pointing to beta version. 

When I explicitly added `pod 'PINCache', '~> 3.0.1'` along with `pod 'PINRemoteImage', '~> 3.0.0'` into pod file, I started getting error on pod install. 
screenshot - 
<img width="580" alt="Screenshot 2020-09-08 at 8 39 35 PM" src="https://user-images.githubusercontent.com/22238045/92494752-bbf64200-f213-11ea-9315-9731f153ef69.png">

Can somebody help me to understand why PINRemoteImage is still pointing to PINCache beta.

**Comment by esteluk** [comment]
Because the version is explicitly pinned, there needs to be a 3.0.1 release of `PINRemoteImage` that can be used with the updated `PINCache`. In the meantime you could point to PINRemoteImage's master branch if you want to resolve dependencies fully.

**Comment by garrettmoon** [comment]
We'll be doing a new release of PINRemoteImage soon. This is fixed in master.

**Comment by gaikwadamit19** [comment]
Thank you, I am waiting for it.

**Comment by McsimumVelocity** [comment]
Hi @garrettmoon. Thanks for your reply and its great to hear there is a fix coming. Really appreciate it. Do you have any approx timeline on a release... like days, weeks or months? It would just be helpful scheduling our own work.

**Comment by petarbelokonski** [comment]
Yes ... https://github.com/pinterest/PINRemoteImage/issues/565

**Comment by garrettmoon** [comment]
Done!

**Comment by timeview** [comment]
I am also having this issue - my pod file is using the following but I keep getting  above error
Incompatible block pointer types sending 'PINMemoryCacheObjectBlock  _Nullable __strong' (aka 'void (^__strong)(PINMemoryCache * _Nonnull __strong, NSString * _Nonnull __strong, id  _Nullable __strong)') to parameter of type 'PINCacheObjectBlock _Nonnull' (aka 'void (^)(id<PINCaching>  _Nonnull __strong, NSString * _Nonnull __strong, id  _Nullable __strong)')
in PINMemoryCache
I am lost at this point 

pod file is as follow
pod 'Texture'
pod 'AsyncDisplayKit', '~> 2.2'
#pod 'PINCache', '~> 3.0.3'
#pod 'PINCache', '~> 3.0.1'
#pod 'PINRemoteImage', '3.0.0-beta.8'
#pod 'PINRemoteImage', :git => 'https://github.com/pinterest/PINRemoteImage.git'
pod 'NMessenger'
