### ISSUE TITLE
error: umbrella header for module 'PINRemoteImage' does not include header 'PINRemoteImage.common-umbrella.h'

### ISSUE THREAD

**Issue by iDevPro** [pinterest/PINRemoteImage#577]
Hello.

I have trouble while build project
`error: umbrella header for module 'PINRemoteImage' does not include header 'PINRemoteImage.common-umbrella.h'`

PINRemoteImage installed from cocoapods (PINRemoteImage (3.0.1))

**Comment by garrettmoon** [comment]
Can you upload a sample project?

**Comment by iDevPro** [comment]
> Can you upload a sample project?

Sorry I could not do that... But I found resolution... 
1) Modern build in Xcode
2) Remove additional dependency of PINRemoteImage from my Lib and stay PINRemoteImage which in Texture as dependency... (ASDK)

I suppose or we need move to SwiftPM, or wait while CocoaPods fix this problem (I mean build with two dependency)

**Comment by garrettmoon** [comment]
Glad you got it fixed! I'm going to close this one out.
