### ISSUE TITLE
Download Progress

### ISSUE THREAD

**Issue by exherb** [pinterest/PINRemoteImage#59]
Is there any way to get how many data has been downloaded?

**Comment by jparise** [comment]
Yes. Have a look at the `progress:` argument that is available on many of the download methods.

> @param progress PINRemoteImageManagerImageCompletion block which will be called to update progress of the image download.

**Comment by exherb** [comment]
@jparise but I can't figure out how to caculate the progress percentage.

**Comment by AdamBCo** [comment]
@exherb how did you go about accomplishing this?

**Comment by garrettmoon** [comment]
@exherb I don't think there is a way to actually calculate the percentage of a download yet, the method @jparise points out gives you progressive renders, but not the amount of data loaded. Please feel free to open up a new issue of your own and we can track it there.
