### ISSUE TITLE
Consider using module-style imports for Foundation and UIKit, to fix this bug...

### ISSUE THREAD

**Issue by jaredsinclair** [pinterest/PINRemoteImage#6]
<img width="905" alt="screen shot 2015-07-26 at 6 08 31 pm" src="https://cloud.githubusercontent.com/assets/720600/8896158/6c9fba4e-33c1-11e5-8095-6c756473a858.png">

I'm not using CocoaPods, just imported the files manually from a submodule. Xcode 7 Beta 4. Swift project so there's no .pch file to auto-import UIKit everywhere.

**Comment by garrettmoon** [comment]
Good point! If you're willing to submit a pull request, I'll get it merged in on Monday!

**Comment by jparise** [comment]
Fixed by #7.
