### ISSUE TITLE
Xcode 7 warnings "Method override for the designated initializer not found"

### ISSUE THREAD

**Issue by alexvimpekable** [pinterest/PINRemoteImage#61]
Both PINCache and PINDiskCache triggers Xcode 7 warnings "Method override for the designated initializer of the superclass '-init' not found". They should probably just return shared instance on `init` or it might be marked as NS_UNAVAILABLE.

**Comment by jparise** [comment]
Those were fixed by pinterest/PINCache#25. We should do a new PINCache release shortly, and once that's out, we'll update the PINCache dependency in PINRemoteImage.

**Comment by jparise** [comment]
[PINCache 2.1](https://github.com/pinterest/PINCache/releases/tag/2.1) has been released with a fix for this. We should also updated PINRemoteImage's PINCache dependency.

**Comment by garrettmoon** [comment]
Updated to 1.2 with PINCache 2.1 dependency.
