### ISSUE TITLE
ios10 crash

### ISSUE THREAD

**Issue by jueduibishi** [pinterest/PINRemoteImage#612]
0   CoreFoundation                      0x000000018cf16ff8 <redacted> + 148
	1   libobjc.A.dylib                     0x000000018b978538 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018cf16eb4 <redacted> + 0
	3   Foundation                          0x000000018d9af760 <redacted> + 112
	4   Shiny                               0x0000000100e04abc -[PINURLSessionManager URLSession:task:didFinishCollectingMetrics:] + 428
	5   CFNetwork                           0x000000018d6f03c0 <redacted> + 36
	6   Foundation                          0x000000018d9e6854 <redacted> + 16
	7   Foundation                          0x000000018d92b7b0 <redacted> + 96
	8   Foundation                          0x000000018d91bb68 <redacted> + 612
	9   Foundation                          0x000000018d9e8bf0 <redacted> + 228
	10  libdispatch.dylib                   0x0000000102a69a10 _dispatch_client_callout + 16
	11  libdispatch.dylib                   0x0000000102a772e8 _dispatch_queue_serial_drain + 1140
	12  libdispatch.dylib                   0x0000000102a6d634 _dispatch_queue_invoke + 852
	13  libdispatch.dylib                   0x0000000102a79630 _dispatch_root_queue_drain + 552
	14  libdispatch.dylib                   0x0000000102a7939c _dispatch_worker_thread3 + 140
	15  libsystem_pthread.dylib             0x000000018bfd7100 _pthread_wqthread + 1096
	16  libsystem_pthread.dylib             0x000000018bfd6cac start_wqthread + 4
	
	
	
There seems to be an issue in iOS 9 where this can be nil. If you can reliably reproduce hitting this, *please* open an issue: https://github.com/pinterest/PINRemoteImage/issues

**Comment by garrettmoon** [comment]
Are you able to reproduce this? Can you provide steps?
