### ISSUE TITLE
'PINRemoteImage/PINRemoteImage.h' file not found

### ISSUE THREAD

**Issue by calaforrai** [pinterest/PINRemoteImage#626]
Hi, 
I Install PINRemoteImage with CocoaPods like this : 

  
```
        pod "PINRemoteImage", "3.0.3"
	pod "PINRemoteImage/WebP"
	pod "PINRemoteImage/PINCache"
```

When I do `#import <PINRemoteImage/PINRemoteImage.h>` I have this error : 
**'PINRemoteImage/PINRemoteImage.h' file not found**

<img width="895" alt="Capture d’écran 2023-03-26 à 1 48 18 PM" src="https://user-images.githubusercontent.com/14937011/227773689-635f09a5-81b5-40e2-81cf-a2497c8d8588.png">

I've been stuck for 2 days, does anyone have any ideas?
Thank @bdolman

**Comment by calaforrai** [comment]
Any help ?

**Comment by SAGESSE-CN** [comment]
Maybe you can put more logs

**Comment by calaforrai** [comment]
I have no other information except : 'PINRemoteImage/PINRemoteImage.h' file not found 🤷‍♂️

**Comment by garrettmoon** [comment]
@calaforrai Without more info I don't think anyone will be able to help.

**Comment by calaforrai** [comment]
Tell me where I can find more info I just installed the pod with pod install and I write #import <PINRemoteImage/PINRemoteImage.h> and it tells me that the import file not found I have no other info, where can I find some other ?

I tried deleting the pods with pod deintegrate and reinstalling the pods from scratch and still not working.

I created an empty project and installed the pods and still got the pod not found error.

Could this be because I'm on a macbook pro m1 ? I saw that it was necessary to launch the terminal in rosetta mode and I did it but something must not be correctly installed during the installation of the pods

**Comment by SAGESSE-CN** [comment]
> Tell me where I can find more info I just installed the pod with pod install and I write #import <PINRemoteImage/PINRemoteImage.h> and it tells me that the import file not found I have no other info, where can I find some other ?
> 
> I tried deleting the pods with pod deintegrate and reinstalling the pods from scratch and still not working.
> 
> I created an empty project and installed the pods and still got the pod not found error.
> 
> Could this be because I'm on a macbook pro m1 ? I saw that it was necessary to launch the terminal in rosetta mode and I did it but something must not be correctly installed during the installation of the pods

If you can't provide more logs, I suggest creating a demo project, then reproduce issue and upload it.
