### ISSUE TITLE
Receiving resultType of PINRemoteImageResultTypeDownload when offline and no image is downloaded

### ISSUE THREAD

**Issue by adamsp** [pinterest/PINRemoteImage#68]
I expect that when I get a result in my completion block with a non-nil `error`, and a nil `image`, the `resultType` should be `PINRemoteImageResultTypeNone` - no image was downloaded, after all.

However, with my iPad in Airplane mode, I get `PINRemoteImageResultTypeDownload`. 

This happens because the result type is [assumed to be a successful download if a cache miss occurs](https://github.com/pinterest/PINRemoteImage/blob/master/Pod/Classes/PINRemoteImageTask.m#L61), regardless of the error state or images existence.

Is this expected behaviour?

**Comment by garrettmoon** [comment]
It would be nicer to return PINRemoteImageResultTypeNone. I'd happily accept a pull request!

**Comment by adamsp** [comment]
Great, I'll get one your way this weekend.
