### ISSUE TITLE
The podspec published for 1.2 points to tag 1.1.2

### ISSUE THREAD

**Issue by waltflanagan** [pinterest/PINRemoteImage#69]
See [here](https://github.com/CocoaPods/Specs/blob/master/Specs/PINRemoteImage/1.2/PINRemoteImage.podspec.json#L12)

Similarly, the podspec at tag 1.2 has the incorrect version.

**Comment by garrettmoon** [comment]
Thanks for pointing this out. I *think* it's fixed with 1.2.1
