### ISSUE TITLE
Ability to track download progress

### ISSUE THREAD

**Issue by AdamBCo** [pinterest/PINRemoteImage#70]
Is there a way to track the download progress of a remote image?

For example, I would like to show a progress bar atop a UIImageView that shows the image is downloading from the web.

Issue #59 referred to it, but I think it was answered in reference to progressive renders as opposed to download percentages.

**Comment by exherb** [comment]
here https://gist.github.com/exherb/e0ad899fe5d3fc7ea2b3

**Comment by garrettmoon** [comment]
@exherb Nice! An easy way to solve the issue without modifying the library any :)

If we were to add this functionality to PINRemoteImage, my suggestion would be to add a progress percentage to PINRemoteImageManagerResult and modify how the progressive progress method calls back to have an option to disable progressive renders and to call back every time it gets data, not just when it has a progressive render.

**Comment by connor** [comment]
Closing this out since #134 added support for it and it's been published in 2.0 release.

**Comment by VictorZhang2014** [comment]
@exherb  Your gist link is not found, have you moved the code snippet to another place?
