### ISSUE TITLE
Using PINRemoteImageManager's initWithSessionConfiguration

### ISSUE THREAD

**Issue by bdorfman** [pinterest/PINRemoteImage#72]
I am unclear on how you are supposed to use the `initWithSessionConfiguration` init on `PINRemoteImageManager`, as there is no way to get your init'd manager into the result of the `sharedImageManager` method, which is used by several methods in `PINRemoteImageCategoryManager`. Possibly I am just not understanding its intended usage, but it seems like you need to either have a way to change/set the return value of sharedImageManager, or refactor `PINRemoteImageCategoryManager` to not rely on a singleton.

**Comment by garrettmoon** [comment]
That's a very good point. We should probably add a method for subclasses to specify the manager?

**Comment by bdorfman** [comment]
Not sure the best way to go about it. Possibly setting a "default" session configuration should be a class method and sharedImageManager will use that one the first time it creates the singleton? Or you could just have something like +setSharedImageManager that will let you use the specified instance for calls to shared.

**Comment by iDevPro** [comment]
When I try change default configuration:
```swift
 let config = URLSessionConfiguration.background(withIdentifier: "hahaha")
 PINRemoteImageManager.setSharedImageManagerWith(config)
```
I have this issue:
- "sharedImageManager singleton is already configured"

**Comment by garrettmoon** [comment]
@iDevPro you need to call the above code earlier in your app startup code, before PINRemoteImageManager sharedManager is accessed.

**Comment by iDevPro** [comment]
But then why this function, if everything can be perfectly set through the class initializer ?)
