### ISSUE TITLE
Readme missing instructions on setting up PINCache

### ISSUE THREAD

**Issue by bdorfman** [pinterest/PINRemoteImage#73]
This library relies on PINCache, but there are no instructions in the Readme that it needs to be added to your project or how to do so properly. Presumably it is set up for you if you are using Cocoapods, but further documentation should be added to the git submodules section.

**Comment by garrettmoon** [comment]
Yeah, we've always used cocoa pods. Would happily accept a pull request to provide others with more info!

**Comment by bdorfman** [comment]
Xcode is very confusing and I have not even been able to get it to work at all by dealing manually with submodules. -_- Trying to get PINCache working via Carthage now, may send you a pull request adding Carthage support to PINRemoteImage depending on my success.

**Comment by garrettmoon** [comment]
If you succeed, that would be awesome!

**Comment by bdorfman** [comment]
Carthage support added in this PR: https://github.com/pinterest/PINRemoteImage/pulls

Have it all working in our app. Possibly broke some Cocoapods support but hopefully not.

This should theoretically make it easier to add to your app. You can either just use Carthage, or just clone the repo and build the new framework target, then drag that target to your own app (which is basically what Carthage does). Might need to tweak some framework search paths if not using Carthage so that it can find where you put PINCache.

**Comment by bdorfman** [comment]
Carthage support added + I tweaked the manual installation instructions to hopefully make them a little bit clearer (although probably most people should still use Cocoapods or Carthage if they don't want to have a headache).
