### ISSUE TITLE
PINDiskCache.m:148:33: 'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in iOS 9.0 

### ISSUE THREAD

**Issue by 1taypan** [pinterest/PINRemoteImage#78]
- Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).

**Comment by jparise** [comment]
This is being tracked as pinterest/PINCache#28.
