### ISSUE TITLE
Memory Leak in UIIMage(PInDecodedImage)

### ISSUE THREAD

**Issue by mRs-** [pinterest/PINRemoteImage#79]
I maybe found a memory leak in the current implementation of decoding the images. It's clearly visible when you try to decode big images (2000x1000 px). The CG raster data in VM memory size is really high for each of my pictures (10,2 MB). And if I relaunch the app with local cached images the cg raster data for the image is only 1.34 MB each.

I can reproduce it myself when I try to scale my images with the processor. After switching from `UIGraphicsBeginImageContextWithOptions` to `CIImage` my memory footprint is now very low and my code is releasing it much better.

## CGGraphicsBeginImageContext Example ##
```
 let image = managerResult.image
 let scaleValue = UIScreen.mainScreen().bounds.size.height / managerResult.image.size.height
 let size = CGSizeApplyAffineTransform(image!.size, CGAffineTransformMakeScale(scaleValue, scaleValue))
 let hasAlpha = false
 let scale : CGFloat = 0.0
                
UIGraphicsBeginImageContextWithOptions(size, !hasAlpha, scale)
image!.drawInRect(CGRect(origin: CGPointZero, size: size))
               
 let scaledImage = UIGraphicsGetImageFromCurrentImageContext()
UIGraphicsEndImageContext()
                
return scaledImage;
```

This is leaking :(

## CIImage Example ##
```
 let image = CIImage(CGImage: managerResult.image.CGImage)
               
 let filter = CIFilter(name: "CILanczosScaleTransform")!
 filter.setValue(image, forKey: "inputImage")
 filter.setValue(scaleValue, forKey: "inputScale")
 filter.setValue(1.0, forKey: "inputAspectRatio")
 let outputImage = filter.valueForKey("outputImage") as! CIImage
                
 let context = CIContext(options: [kCIContextUseSoftwareRenderer : false])
 let scaledImage = UIImage(CGImage: context.createCGImage(outputImage, fromRect: outputImage.extent()))

 return scaledImage
```
This is fine :sunglasses: 
## Instrument Leaks ##
![screenshot 2015-10-19 16 46 33](https://cloud.githubusercontent.com/assets/736421/10581244/00aa576e-7682-11e5-800c-6a4ae5e54edd.png)
![screenshot 2015-10-19 16 53 13](https://cloud.githubusercontent.com/assets/736421/10581327/539107a2-7682-11e5-976e-4c1096e27a76.png)

**Comment by garrettmoon** [comment]
@mRs- 

By my rough calculations, an 2000 x 1000 image that's decompressed should be 8MB in size. So you're 'local' storage image may be compressed still? I.e. in JPEG or PNG and not BMP form? The decodedImageWithCGImage intentionally changes JPEG, etc to BMP to aid in drawing speed (to aid in fast scrolling for example).

So the ~10MB size sounds correct to me. Am I missing something else?

**Comment by mRs-** [comment]
When I set a image with PINRemoteImage there are following steps that are made:

## Download, Decompress, Cache and Display ##
1. Download the Image
2. Decompress the Image
3. Save the Image to cache
4. Display Image

With this approach the 2000x1000 image is holding like ~10 MB in CG raster data.

## Find local File in Cache and Display ##
1. Check the cache
2. Find the Image
3. Display Image

With this approach the same 2000x1000 image after restarting the application it's only holding ~1,3 MB in  CG raster data.

My observation is that we can optimize the way the image is using memory when I'm first downloading the image (~8 MB). And I think it has something to do with the current implementation of decompressing images via `UIGraphicsBeginImageContextWithOptions`, because the `processor` of PINRemoteImage is wasting with this function memory too. Because of this reasons I moved from  `UIGraphicsBeginImageContextWithOptions` to `CIImage`

**Comment by kerrmarin** [comment]
Could this be related to #63 ?

**Comment by garrettmoon** [comment]
@kerrmarin I don't think it is, if you follow the mitigation techniques I describe, the app doesn't crash, responds to the memory warning and it *doesn't* continue to grow in size. I think this issue is incorrectly described as a memory leak.

**Comment by garrettmoon** [comment]
But I could be wrong too! I plan to investigate the difference between disk access and network access when I get a chance.

**Comment by mRs-** [comment]
Maybe we need a method to decode the images without using so much memory. Maybe a switch to CGImageSource would be a solution.

**Comment by garrettmoon** [comment]
@mRs- It's not actually decoded if it's using any less memory :) The point of decoding it is so that the GPU doesn't have to decode it later, on the main thread (when it could cause stutters in scrolling). If it's in anything but bitmap format (which is a set number of bytes per pixel and therefore directly correlated with image size), it'll have to do that.

You *can* actually disable decoding of the image, it's one of the download options. Depending on your constraints, this might be a good idea if you don't mind waiting for the system to decode on the main thread.

**Comment by mRs-** [comment]
Disabling decode is not an option for my current solution, because the images are big and I don't want to do this on the main thread.

Decoding images with UIKit is not the best option we have here. UIKit is doubling the costs of decoding the image, which leads in a memory spike. 

I think a better solution is to go with `ImageIO` and the workflow would be something like that.

1. check image for memcache
2. check image for disk cache
3. download image from url
4. save the image temporary to disk
5. process the image if necessary (README should explain to use ImageIO or CIImage for this)
6. decode the image with ImageIO and save the processed image to disk
7. put it in memcache
8. display the image

I would like to write an example implementation for this, so you can prove this concept for this if you like to :smile:

**Comment by garrettmoon** [comment]
Cool! I haven't had a chance to see why there's a difference between reading from disk vs network. If you do come up with a change that reduces memory usage, that'd be amazing.

Something that may help your development: there's a unit test called testDecoding which tests the time it takes to draw an image when decoding is skipped vs when it's not. So any change you make that reduces memory usage *and* still achieves the speed of the existing decode methods would be *greatly* appreciated!

**Comment by mRs-** [comment]
Awesome, then I will give this definitely a try would be awesome to achieve something like that in this library

**Comment by garrettmoon** [comment]
@mRs- Hey! So I wasn't able to see the disk cache using less memory than the memory cache when playing around with it this morning. If you can give me a test case that gets this to happen I'd be happy to look into it.

Also would be cool to see if you can get the memory use down while keeping the speed of drawing our decoded images just as fast.

I'm going to close the issue, but feel free to reply here and I'll reopen if you're willing to put the time in to find a reproduction case or improvement to the image decompression!
