### ISSUE TITLE
Error when trying to use webp

### ISSUE THREAD

**Issue by donnywals** [pinterest/PINRemoteImage#8]
I have a Swift project that includes PINRemoteImage and webp. When I try to build my project I get this error:

```
Undefined symbols for architecture arm64:
  "_WebPGetFeaturesInternal", referenced from:
      _WebPGetFeatures in UIImage+WebP.o
  "_WebPDecodeRGBA", referenced from:
      +[UIImage(WebP) imageWithWebPData:] in UIImage+WebP.o
  "_WebPDecodeRGB", referenced from:
      +[UIImage(WebP) imageWithWebPData:] in UIImage+WebP.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm not sure where to go hunting for what exactly is wrong.. I've cleaned my project a bunch of times, deleted Derived Data, etc. No luck so far :(

**Comment by garrettmoon** [comment]
Have you tried just including WebP by itself to eliminate PINRemoteImage as the cause?

**Comment by donnywals** [comment]
@garrettmoon sorry, I meant to update this ticket but totally forgot about it... I think libwebp is the culprit because when my app does compile there's still a warning for libwebp about multiple build commands and PINRemoteImage doesn't recognize the existence of libwebp. So I'll close this ticket, I don't think PINRemoteImage is to blame here..
