### ISSUE TITLE
It's a great project but difficult to use

### ISSUE THREAD

**Issue by lqcjdx** [pinterest/PINRemoteImage#85]
As you say how to use:
Installation
Manually
Download the latest tag and drag the PINRemoteImage folder into your Xcode project.
Install the docs by double clicking the .docset file under docs/, or view them online at cocoadocs.org

First,i tried clone in desktop directly,but find the Contents is so complex that i do not know  how to 'drag the PINRemoteImage folder into your Xcode project'  .

Then,i use 'pod search PINRemoteImage‘ code,but  it shows:
[!] Unable to find a pod with name matching `PINRemoteImage'

I love this project but i really can not find how to put it in my Xcode project. I guess you should learn the SDWebImage's usage.Thank you!

My English is so pool,sorry  for that!

**Comment by garrettmoon** [comment]
Hi @lqcjdx when I run the command
```
pod search PINRemoteImage
```
it returns:
```
-> PINRemoteImage (1.2.1)
   A thread safe, performant, feature rich image fetcher
   pod 'PINRemoteImage', '~> 1.2.1'
   - Homepage: https://github.com/pinterest/PINRemoteImage
   - Source:   https://github.com/pinterest/PINRemoteImage.git
   - Versions: 1.2.1, 1.2, 1.1.2, 1.0 [master repo]
   - Subspecs:
     - PINRemoteImage/Core (1.2.1)
     - PINRemoteImage/FLAnimatedImage (1.2.1)
```

Maybe there's something wrong with your cocoapods install? You can try upgrading cocoapods with:

```
sudo gem install cocoapods
```
Also, the README has been updated with a bit more clarity on how to install. Hopefully this helps!
