### ISSUE TITLE
How to use with webp

### ISSUE THREAD

**Issue by zhouzizi** [pinterest/PINRemoteImage#94]
I have  add all of the PINRemoteImage files  to my project ，but use ```  pin_setImageFromURL(NSURL(string: "xxxx.jpg")!) ``` can not show the image ,my webp image	postfix is ".jpg",but it is wep image

**Comment by zhouzizi** [comment]
deal

**Comment by zhouzizi** [comment]
Sometimes it can be work ,but sometimes not...

**Comment by zhouzizi** [comment]
How to use with webp

**Comment by garrettmoon** [comment]
@zhouzizi we'll need more info to help you track down the issue. You say it works sometimes but not other times? Does it work with some images and not others?

**Comment by zhouzizi** [comment]
Sorry, It does not work with Webp image.Counld you give me a guild to install with webp  please ? I found the NSData+ImageDetectors.m file and other files has some codes  like 
![41454219-9d86-45ed-91aa-9e831d241c47](https://cloud.githubusercontent.com/assets/9103749/11081098/f77ab988-8854-11e5-9679-38e0bea14764.jpg)  ,I delete it ,but it also can not work ..

**Comment by garrettmoon** [comment]
You should look into the webp pod possibly?

**Comment by zhouzizi** [comment]
I am a newbie ..Could you told me more detail please ..

**Comment by garrettmoon** [comment]
Are you using cocoa pods, add

pod 'libwebp'

to your pod file.

**Comment by zhouzizi** [comment]
no.I install it with manually method ,i have drag all files to my project ,include libwebp 
![image](https://cloud.githubusercontent.com/assets/9103749/11081457/bde69f72-8857-11e5-8407-71061b0004ad.png)

**Comment by garrettmoon** [comment]
Hmm, I haven't done it that way, so I'd have to figure it out myself too. Maybe someone else in the community can help.

**Comment by zhouzizi** [comment]
Sorry to bother you.
